//! Issue 0446: **a view an older Intent rendered differs from today's render
//! only in text the renderer owns, and that is not a hand edit.**
//!
//! Rehearsing the fleet trawl, `organize` refused to dehydrate 68 views across
//! four estates. Every one was driven -- declared, realised from the store,
//! diffed -- and 65 differed ONLY in the footer's wording (the source it names
//! lost its backticks between releases) or in the Acceptance cover paragraph
//! the renderer writes, whose wording also moved. No human touched either, and
//! each refusal's remedy was a per-file decision. `st sync --write`'s
//! empty-estate guard read a 2-byte footer change on an EMPTY estate as "the
//! store is behind the estate".
//!
//! **THE OLDER RENDER IS BUILT FROM A REAL ONE**, so the arms are about the
//! renderer's actual text: today's render, with its footer and its cover
//! paragraph replaced by the words Intent 3.0.0 wrote -- taken verbatim from the
//! views the trawl rehearsal diffed.
//!
//! **BOTH HALVES ARE ARMS, BECAUSE THE FIX HAS AN OVER-CORRECTION ON ITS FAR
//! SIDE.** An older renderer's view must clear; a hand edit under an older
//! renderer's footer must still refuse, and so must text appended after the
//! banner, which is the author's.

use crate::common::{Fixture, ctx, sample_thread};
use intentsvcs::finding::FindingClass;
use intentsvcs::organize::{Action, OrganizeError, Step, gate};
use intentsvcs::sync::Scope;

/// What every version of the thread cover's Acceptance paragraph starts with.
const COVER: &str = "Acceptance Criteria and Acceptance Tests are RENDERED into `acceptance.md`";

/// The paragraph as Intent 3.0.0 wrote it, verbatim from a trawl diff.
const OLDER_COVER: &str = "Acceptance Criteria and Acceptance Tests are RENDERED into `acceptance.md`, which is a GENERATED VIEW -- a row authored there is discarded by the next sync. The contract is canon in this thread's model: change a state with the `intent ac` / `intent at` verbs, and mint or reword a row in `.canon/st/ST0001.json`, then `intent sync --to-store`. This cover never restates them.\n";

/// The footer as Intent 3.0.0 wrote it for a thread view.
const OLDER_FOOTER: &str = "_Generated by Intent v3.0.0 from `the thread canon`. Do not edit this file -- it is rendered from the model, and `intent doctor` reports any hand-edit as skew._";

const VIEW: &str = "intent/st/ST0001/info.md";

/// ST0001's cover as this binary renders it, written to disk.
fn rendered_cover(fx: &Fixture) -> String {
  fx.write_thread(&sample_thread("ST0001"));
  let project = fx.project();
  let canon = intentsvcs::ingest::read(&project).expect("canon reads");
  intentsvcs::views::write_all(&project, &canon, &ctx()).expect("the views render");
  let rendered = fx.read(VIEW);
  assert!(
    rendered.lines().any(|line| line.starts_with(COVER)),
    "the fixture's cover carries no Acceptance paragraph, so nothing below is about it: {rendered}"
  );
  rendered
}

/// The same cover as Intent 3.0.0 rendered it: the cover paragraph and the
/// footer in the older words, every other byte unchanged.
fn as_an_older_renderer_wrote_it(rendered: &str) -> String {
  let mut older = String::with_capacity(rendered.len());
  for line in rendered.split_inclusive('\n') {
    if line.starts_with(COVER) {
      older.push_str(OLDER_COVER);
    } else if line.starts_with("_Generated by Intent v") {
      older.push_str(OLDER_FOOTER);
      if line.ends_with('\n') {
        older.push('\n');
      }
    } else {
      older.push_str(line);
    }
  }
  assert!(
    older != rendered && older.contains(OLDER_COVER) && older.contains(OLDER_FOOTER),
    "the older render must differ in BOTH the cover and the footer, or an arm below is vacuous"
  );
  older
}

fn step(fx: &Fixture, rendered: &str) -> Step {
  Step {
    path: fx.path(VIEW),
    action: Action::Dehydrate,
    content: Some(rendered.as_bytes().to_vec()),
  }
}

#[test]
fn a_view_an_older_renderer_wrote_is_cleared_for_removal() {
  let fx = Fixture::new();
  let rendered = rendered_cover(&fx);
  fx.write_file(VIEW, &as_an_older_renderer_wrote_it(&rendered));
  assert!(
    gate(&step(&fx, &rendered)).is_ok(),
    "a view that differs only in the footer and cover paragraph an older Intent wrote was \
     refused as a possible hand edit -- the 65 refusals of issue 0446"
  );
}

#[test]
fn a_hand_edit_under_an_older_renderers_footer_is_still_refused() {
  let fx = Fixture::new();
  let rendered = rendered_cover(&fx);
  let older = as_an_older_renderer_wrote_it(&rendered);
  // One authored line changed, the renderer's text left as the older one wrote it.
  let first = older.lines().next().expect("the view has a first line");
  let edited = older.replacen(first, &format!("{first} (edited by hand)"), 1);
  assert_ne!(
    edited, older,
    "the fixture must actually edit an authored line"
  );
  fx.write_file(VIEW, &edited);
  assert!(
    matches!(
      gate(&step(&fx, &rendered)),
      Err(OrganizeError::HandEdited { .. })
    ),
    "a hand edit was cleared because the renderer's text around it had also moved -- the mask \
     reached past what the renderer owns"
  );
}

#[test]
fn text_appended_after_an_older_footer_is_the_authors_and_still_refuses() {
  let fx = Fixture::new();
  let rendered = rendered_cover(&fx);
  let appended = format!(
    "{}\nA line a script appended after the footer.\n",
    as_an_older_renderer_wrote_it(&rendered)
  );
  fx.write_file(VIEW, &appended);
  assert!(
    matches!(
      gate(&step(&fx, &rendered)),
      Err(OrganizeError::HandEdited { .. })
    ),
    "text after the banner's line is the author's, and masking the footer must not mask it"
  );
}

#[test]
fn doctor_reads_an_older_renderers_view_as_a_stale_render_and_not_as_skew() {
  let fx = Fixture::new();
  let rendered = rendered_cover(&fx);
  fx.write_file(VIEW, &as_an_older_renderer_wrote_it(&rendered));

  let report =
    intentsvcs::doctor::diagnose(&fx.project(), &ctx(), None, intentsvcs::doctor::Scope::All);
  let about_the_view: Vec<_> = report
    .findings
    .iter()
    .filter(|f| f.to_string().contains("ST0001/info.md"))
    .collect();
  assert!(
    about_the_view
      .iter()
      .any(|f| f.class == FindingClass::StaleRender),
    "an older renderer's view is a stale render: {about_the_view:?}"
  );
  assert!(
    !about_the_view
      .iter()
      .any(|f| f.class == FindingClass::ViewSkew),
    "and it is NOT skew, which would block every commit in an estate an older Intent rendered: \
     {about_the_view:?}"
  );
}

/// The `st sync --write` half: an EMPTY estate whose index an older Intent
/// rendered is 2 bytes longer than today's render, all of them in the footer.
#[test]
fn an_empty_estates_index_an_older_renderer_wrote_egests_without_complaint() {
  let fx = Fixture::new();
  fx.facade_on_disk()
    .sync_to_disk(&Scope::All)
    .expect("an empty project egests");
  let face = fx.project().steel_threads_view();
  let rendered = std::fs::read_to_string(&face).expect("the index view exists");
  let older = rendered.replace("from the thread canon", "from `the thread canon`");
  assert!(
    older.len() > rendered.len(),
    "the older index must be LONGER than the render, or the shrink guard is not reached"
  );
  std::fs::write(&face, &older).expect("an older renderer's index");

  fx.facade_on_disk().sync_to_disk(&Scope::All).expect(
    "an empty estate's index shrank by an older footer's backticks and was read as the store \
     being behind the estate",
  );
  assert_eq!(
    std::fs::read_to_string(&face).expect("still there"),
    rendered,
    "and the egest wrote today's render over it"
  );
}

/// **THE SAME VERSION, A DIFFERENT WORDING** (cc's known-defects re-drive,
/// `refs/bank/cc/kd/upgrade-footer`). A project the v3.0.3 keg rendered, read
/// by the 3.1.0 candidate -- which still calls itself 3.0.3 -- reported
/// `steel_threads.md` and `todo.md` as BLOCKING view-skew with the hand-edit
/// warning. The only difference is the footer's source phrase, which lost its
/// backticks (issue 0331). The footer-version predicate this replaced asked
/// only about a VERSION move and refused a same-version banner outright.
#[test]
fn a_same_version_footer_reworded_by_an_older_renderer_is_a_stale_render() {
  let fx = Fixture::new();
  fx.write_thread(&sample_thread("ST0001"));
  let project = fx.project();
  let canon = intentsvcs::ingest::read(&project).expect("canon reads");
  intentsvcs::views::write_all(&project, &canon, &ctx()).expect("the views render");

  for rel in ["intent/st/steel_threads.md", "intent/todo.md"] {
    let rendered = fx.read(rel);
    let older = rendered.replace("from the thread canon", "from `the thread canon`");
    assert_ne!(
      older, rendered,
      "{rel} does not name `the thread canon` in its footer, so this arm is about nothing"
    );
    assert_eq!(
      older.matches("_Generated by Intent v").count(),
      rendered.matches("_Generated by Intent v").count(),
      "the version must be left alone -- the case is a wording move at the SAME version"
    );
    fx.write_file(rel, &older);
  }

  let report =
    intentsvcs::doctor::diagnose(&fx.project(), &ctx(), None, intentsvcs::doctor::Scope::All);
  for rel in ["steel_threads.md", "todo.md"] {
    let about: Vec<_> = report
      .findings
      .iter()
      .filter(|f| f.to_string().contains(rel))
      .collect();
    assert!(
      about.iter().any(|f| f.class == FindingClass::StaleRender),
      "{rel}, reworded by an older renderer at the same version, is a stale render: {about:?}"
    );
    // **BLOCKING IS THE PROPERTY, NOT THE FIXTURE'S VERDICT.** `sample_thread`
    // carries model findings of its own (a criterion descoped to a thread the
    // fixture does not hold), so the report's exit code is about the fixture;
    // what matters here is that nothing about THESE views blocks a commit.
    assert!(
      !about.iter().any(|f| f.class.is_actionable()),
      "{rel} carries a finding that blocks the pre-commit gate: {about:?}"
    );
  }
}
