//! `intent claude upgrade` -- **the canon applier must preserve wiring it has
//! never heard of**, and must not overwrite a hand-authored file to cure
//! variation.
//!
//! # Why this file exists rather than a "does it write the files" test
//!
//! Writing the five artefacts is the easy half and a test of it would pass on
//! an implementation that regenerated the pre-commit hook wholesale. **The hard
//! half is everything the applier must NOT do**, and each arm here is a real
//! consumer's real file:
//!
//! - Lamplight wires four guards through its chain block and **two of them are
//!   not in Intent canon at all** (`whiteboard-inbox-guard`, `live-doc-budget`).
//!   A canon-aware regenerator writes the guards it knows and drops the rest,
//!   silently, in a file nobody reads until a guard stops firing.
//! - Lamplight's block sits at lines 4-9, **not at the top**, so an
//!   implementation keying off "the first N lines" passes on a fixture built
//!   top-down and destroys a consumer whose block sits lower.
//! - A project's `CLAUDE.md` may be entirely hand-authored. Overwriting it is
//!   the cure being worse than the disease hv's instruction names.
//!
//! # The negative control is the point
//!
//! Every arm below is written so that **deleting the behaviour it guards makes
//! it fail**. `a_regenerator_would_fail_this` states that explicitly: it is the
//! arm that separates "preserved because we were careful" from "preserved
//! because nothing was there to lose".

use intentsvcs::canon::{carry_user_block, insert_chain_block};

/// A consumer hook whose own guards Intent canon has never heard of, with a
/// header comment between the preamble and the first real command.
const CONSUMER_HOOK: &str = "\
#!/usr/bin/env bash
set -euo pipefail

# this project's own guards, not Intent's
bash \"$(dirname \"$0\")/whiteboard-inbox-guard.sh\" || exit 1
bash \"$(dirname \"$0\")/live-doc-budget.sh\" || exit 1
";

#[test]
fn wiring_canon_has_never_heard_of_survives() {
  let out = insert_chain_block(CONSUMER_HOOK).expect("a hook with no block is edited");
  for guard in ["whiteboard-inbox-guard", "live-doc-budget"] {
    assert!(
      out.contains(guard),
      "`{guard}` was dropped. It is not in Intent canon, which is exactly why a \
       regenerator loses it and a region edit keeps it.\n--- got ---\n{out}"
    );
  }
  assert!(out.contains("# intent-chain-block:start"));
  assert!(out.contains("# intent-chain-block:end"));
}

/// **THE ARM THAT MAKES THE ONE ABOVE MEAN SOMETHING.**
///
/// A test asserting "the guards are still there" passes trivially if the
/// implementation simply appends. This pins the property that actually
/// distinguishes a region edit: **every original line is still present, in its
/// original order**, and the only additions are the block's own lines.
#[test]
fn a_regenerator_would_fail_this() {
  let out = insert_chain_block(CONSUMER_HOOK).expect("edited");
  let original: Vec<&str> = CONSUMER_HOOK.lines().collect();
  let produced: Vec<&str> = out.lines().collect();

  let mut i = 0;
  for line in &original {
    match produced[i..].iter().position(|p| p == line) {
      Some(offset) => i += offset + 1,
      None => panic!(
        "original line {line:?} is absent or out of order in the result -- this is a \
         regeneration, not a region edit\n--- got ---\n{out}"
      ),
    }
  }

  // And nothing beyond the block was invented.
  let added = produced.len() - original.len();
  assert!(
    added <= 7,
    "the edit added {added} lines; the chain block is 6 plus a blank. Anything more \
     means content was synthesised into a consumer's hook.\n--- got ---\n{out}"
  );
}

/// A block that does NOT sit at the top must still be found.
///
/// **Lamplight's sits at lines 4-9.** An implementation that scans only the
/// first few lines reports "absent", inserts a second block, and the hook then
/// runs the chain twice -- which is not obviously wrong from the output.
#[test]
fn an_existing_block_below_the_top_is_recognised() {
  let already = "\
#!/usr/bin/env bash
set -euo pipefail

# intent-chain-block:start (generated by intent claude upgrade)
_intent_chain=\"$(git rev-parse --git-path hooks 2>/dev/null)/pre-commit.intent\"
if [ -x \"$_intent_chain\" ]; then
  \"$_intent_chain\" \"$@\" || exit $?
fi
# intent-chain-block:end

bash \"$(dirname \"$0\")/live-doc-budget.sh\" || exit 1
";
  assert!(
    insert_chain_block(already).is_none(),
    "a block below the top was not recognised, so a second one would be inserted and \
     the chain would run twice"
  );
}

/// Idempotence, stated as its own arm because it is the property that makes the
/// applier a converger rather than a writer: run it twice, change nothing.
#[test]
fn a_second_pass_changes_nothing() {
  let once = insert_chain_block(CONSUMER_HOOK).expect("first pass edits");
  assert!(
    insert_chain_block(&once).is_none(),
    "the second pass wanted to edit again, so the applier is not idempotent and every \
     run would move the hook's mtime"
  );
}

/// A hook that is nothing but preamble still gets the block.
///
/// The insertion point is "after the preamble", and a file that is ALL preamble
/// never reaches it. Without the fallback the block is silently not installed
/// into the very hooks most likely to be near-empty.
#[test]
fn a_preamble_only_hook_still_gets_the_block() {
  let out = insert_chain_block("#!/usr/bin/env bash\nset -euo pipefail\n").expect("edited");
  assert!(
    out.contains("# intent-chain-block:start"),
    "an all-preamble hook never reached the insertion point and got no block:\n{out}"
  );
}

/// An absent hook is a whole file, shebang included -- an inserted block with
/// no shebang above it is not executable as a hook.
#[test]
fn an_absent_hook_is_written_whole() {
  let out = insert_chain_block("").expect("an empty hook is written");
  assert!(
    out.starts_with("#!"),
    "no shebang, so git cannot execute it:\n{out}"
  );
  assert!(out.contains("# intent-chain-block:start"));
}

/// **BAIZE'S REAL `pre-commit`, BYTE FOR BYTE OFF DISK.** This is the arm that
/// would have caught the marker defect, and the reason it did not exist is the
/// finding worth keeping.
///
/// The constant and the fixture were authored together, from one assumption, so
/// the fixture wrote the angle form in and the assertion read the angle form
/// out. **The mutation proof was genuine and it proved a property of the
/// fixture.** Thirteen of the estate's sixteen projects carry a `pre-commit`;
/// thirteen carry the form below; zero carried the one the code was matching.
///
/// So this hook is COPIED, not composed. A fixture an author writes can only
/// encode what the author already believes.
const ESTATE_HOOK: &str = r#"#!/usr/bin/env bash
set -u

# intent-chain-block:start (generated by intent claude upgrade)
_intent_chain="$(git rev-parse --git-path hooks 2>/dev/null)/pre-commit.intent"
if [ -x "$_intent_chain" ]; then
  "$_intent_chain" "$@" || exit $?
fi
# intent-chain-block:end
"#;

#[test]
fn the_marker_the_estate_actually_carries_is_recognised() {
  assert!(
    insert_chain_block(ESTATE_HOOK).is_none(),
    "a real, already-chained consumer hook read as UNCHAINED. `--apply` therefore \
     writes a second block, `pre-commit.intent` runs twice on every commit, and the \
     NEXT pass reports `0 written` -- certifying the doubled state as canonical."
  );
}

/// A hook already doubled by the defect must not collect a THIRD block.
///
/// The angle form is recognised and never emitted. Repairing a doubled hook is a
/// human deleting one of two live invocations; this code's only job is to stop
/// adding to the pile.
#[test]
fn a_hook_carrying_the_retired_marker_gets_no_further_block() {
  let doubled = format!(
    "{ESTATE_HOOK}\n# >>> intent-chain-block >>>\n_intent_chain=\"x\"\n# <<< intent-chain-block <<<\n"
  );
  assert!(
    insert_chain_block(&doubled).is_none(),
    "a hook carrying the retired marker was not recognised, so a third block would land"
  );
}

/// **A PROSE MENTION OF THE MARKER IS NOT A BLOCK.**
///
/// Laksa's hook carries the line below verbatim, explaining the block above it.
/// A `contains("intent-chain-block")` predicate reads that comment as a block --
/// so a project whose block had been deleted while its comment survived would
/// silently never get one back, and the tool would report success.
#[test]
fn a_comment_mentioning_the_marker_does_not_count_as_one() {
  let prose_only = "\
#!/usr/bin/env bash
set -euo pipefail

# The intent-chain-block above is NOT folded in: `intent claude upgrade`
# regenerates it, and it must keep running before the project's own gate.
exec \"$(git rev-parse --show-toplevel)/bin/laksa\" precommit
";
  let out = insert_chain_block(prose_only)
    .expect("a hook that only MENTIONS the marker has no block and must get one");
  assert!(out.contains("# intent-chain-block:start"));
  assert!(
    out.contains("exec"),
    "the consumer's own dispatch was dropped:\n{out}"
  );
}

/// **WHAT IS EMITTED MUST BE WHAT IS RECOGNISED.** Stated as its own arm because
/// the two are separate constants: the emitted marker carries a parenthetical
/// the recogniser matches only the prefix of, and nothing else pins them
/// together. Drift here is silent and reintroduces the doubling exactly.
#[test]
fn the_emitted_block_is_recognised_by_the_next_pass() {
  let fresh = insert_chain_block("").expect("an empty hook is written whole");
  assert!(
    insert_chain_block(&fresh).is_none(),
    "the applier does not recognise its OWN output, so every run appends another \
     block:\n{fresh}"
  );
}

// ---------------------------------------------------------------------------
// The project's OWN directives, inside a file canon otherwise owns.
// ---------------------------------------------------------------------------

/// **INTENT'S OWN `CLAUDE.md` USER BLOCK, EXTRACTED FROM DISK, NOT TYPED.**
///
/// Copied by the script that added this arm, for the reason the chain-block
/// defect taught: a fixture an author writes can only encode what the author
/// already believes. Four projects in the estate carry content here -- 80 lines,
/// 25, 2, 1 -- and every one would have lost it to an ordinary `--apply`.
const REAL_USER_BLOCK: &str = r##"
<!-- Author: matts, created 2026-04-25. Intent dogfoods its own canon -- this CLAUDE.md is the reference example of the WP09 overlay template applied to a real project. Preserved across regeneration. -->

### Intent dev rules (extend the four agnostic rules above)

1. **Highlander Rule** -- search `intent/llm/MODULES.md` before creating any new module, helper, or template: `grep -n '<name>' intent/llm/MODULES.md`. **Search it, do not read it** -- the registry is ~354KB across ~367 rows, so "read it first" is not an instruction anyone can follow. (`intent modules find` is the intended verb: **drive it, and fall back to the grep above if it does not answer.** Which spelling works is a property of the tool version you are standing on, and pinning that answer here would make this a second home for a fact the tool already reports about itself.)
2. **Thin scripts** (concretises `IN-AG-THIN-COORD-001`) -- business logic lives in dedicated modules under `bin/` or `intent/plugins/`, never inline in command dispatch or heredocs.
3. **No silent failures** (concretises `IN-AG-NO-SILENT-001`) -- every error path uses `error()` from `bin/intent_helpers`.
4. **Check before you create** -- before adding a new script or function, search the registry as in rule 1.
5. **Register before you code** -- when you must create a new module, add the row to MODULES.md FIRST, then create the file.
6. **Single template source** -- all generated content comes from `lib/templates/` via `sed` substitution. No inline heredocs duplicating template content.

### Intent-specific files

- `intent/wip.md` -- current work in progress (read on session start).
- `intent/restart.md` -- session restart context (post-compact resume).
- `bin/` -- Intent CLI source.
- `lib/templates/` -- generated-content source of truth.
- `intent/plugins/` -- plugin canon (`claude/`, `agents/`).

### Internal authoring docs

The canon Critic dispatch section above already points at `intent/docs/critics.md`. Two more authoring guides live alongside:

- `intent/docs/rules.md` -- rule-library authoring guide (schema, Detection heuristics, attribution).
- `intent/docs/writing-extensions.md` -- user-extension authoring guide (subagents, skills, rule packs at `~/.intent/ext/`).

### Commit conventions

- DO NOT ADD CLAUDE TO GIT COMMITS. EVER. No `Co-Authored-By`, no Claude signatures, no AI attribution.
- T-shirt sizing only (XS / S / M / L / XL / XXL); never clock-time estimates.
- NEVER manually wrap lines in markdown files.

### Migration history

Intent originated as STP, migrated to Intent v2.0.0 on 2025-07-16, then through v2.1.0 -> v2.2.0 -> v2.3.0 -> v2.8.x -> v2.9.0 -> v2.10.0 -> v2.11.0 (current). v2.10.0 ships the canonical LLM config (this overlay pattern, three-file canon AGENTS.md / CLAUDE.md / usage-rules.md, session hooks, pre-commit critic gate) and relocates `.intent/` to `intent/.config/`. v2.11.0 (ST0037) replaces filesystem-marker language detection with an explicit `languages` config field. See `CHANGELOG.md` for per-version detail.

### Author

matts (hello@matthewsinclair.com)

"##;

fn generated(block: &str) -> String {
  format!(
    "# Project\n\n## Project-specific\n\n<!-- user:start -->{block}<!-- user:end -->\n\n---\n\n_Generated from `lib/templates/llm/_CLAUDE.md`._\n"
  )
}

/// **THE ARM THE TEMPLATE'S OWN TEXT ALREADY PROMISED.**
///
/// `_CLAUDE.md` says "Preserved across regeneration" inside the file every
/// project's authors read. Nothing implemented it. This is the code behind the
/// sentence.
#[test]
fn a_projects_own_directives_survive_regeneration() {
  let existing = generated(REAL_USER_BLOCK);
  let regenerated = generated(
    "\n<!-- Author: [[AUTHOR]]. Add project-specific Claude directives below this line. Preserved across regeneration. -->\n\n",
  );
  let out = carry_user_block(&existing, &regenerated);

  for line in REAL_USER_BLOCK.lines().filter(|l| l.trim().len() > 40) {
    assert!(
      out.contains(line),
      "a project directive was lost to regeneration:\n  {line}\n--- got ---\n{out}"
    );
  }
}

/// The carried block goes back BYTE FOR BYTE, blank lines and all.
///
/// Separate from the arm above because "every long line survives" passes on an
/// implementation that reflows or reorders. Formatting is content in a file of
/// instructions.
#[test]
fn the_block_is_carried_byte_for_byte() {
  let existing = generated(REAL_USER_BLOCK);
  let out = carry_user_block(&existing, &generated("\nplaceholder\n"));
  let s = out.find("<!-- user:start -->").expect("start") + "<!-- user:start -->".len();
  let e = out.find("<!-- user:end -->").expect("end");
  assert_eq!(
    &out[s..e],
    REAL_USER_BLOCK,
    "the block was altered in transit"
  );
}

/// **THE DISCRIMINATING CONTROL (vc, from devbin-vc's sentinel run).**
///
/// The failure is not that the block goes MISSING -- hop 3 substitutes the
/// template's own default block, well-formed, with an author line. **A check
/// asking "is there a user block?" is blind to that; only "is it THIS block?"
/// sees it.** So the fixture here is a MODIFIED block that must come back
/// modified: an implementation that reconstructs a pristine canonical block
/// passes every arm above and fails this one.
#[test]
fn a_modified_block_comes_back_modified() {
  let modified = format!("{REAL_USER_BLOCK}\n7. **A rule this project added after the fact.**\n");
  let out = carry_user_block(&generated(&modified), &generated("\nplaceholder\n"));
  assert!(
    out.contains("A rule this project added after the fact."),
    "the local modification was replaced by a well-formed block that is not the \
     project's own:\n{out}"
  );
}

/// An empty block is carried as it stands -- Baize's case, and the reason that
/// migration cost nothing.
#[test]
fn an_empty_block_is_carried_as_it_stands() {
  let out = carry_user_block(&generated("\n"), &generated("\nplaceholder\n"));
  assert!(
    !out.contains("placeholder"),
    "the existing empty block did not win:\n{out}"
  );
}

/// A file with no block is left entirely alone. **Inventing one would put
/// canon's placeholder into a file whose author never asked for it.**
#[test]
fn a_file_with_no_block_is_left_alone() {
  let regenerated = generated("\nplaceholder\n");
  assert_eq!(
    carry_user_block("# hand-authored, no markers\n", &regenerated),
    regenerated
  );
}

/// A regenerated file with no block does not gain one. **Appending the content
/// somewhere plausible is the canon-aware guessing this module refuses.**
#[test]
fn a_regenerated_file_with_no_block_does_not_gain_one() {
  let plain = "# Project\n\nno markers here\n".to_string();
  assert_eq!(carry_user_block(&generated(REAL_USER_BLOCK), &plain), plain);
}

/// A half-open block is not a block. An unterminated `user:start` must not make
/// the splice swallow the rest of the file.
#[test]
fn a_half_open_block_is_not_a_block() {
  let regenerated = generated("\nplaceholder\n");
  let half = "# Project\n<!-- user:start -->\nstranded\n";
  assert_eq!(carry_user_block(half, &regenerated), regenerated);
}
