//! Issue 0316: **`upgrade` removes the views of every thread its manifest
//! leaves undeclared, through organize's own plan and gate.**
//!
//! Measured by courses-vc on a dormant 3.0.0 estate: `upgrade` wrote
//! `.intentfiles` declaring the one WIP thread, so the two closed threads
//! became undeclared; `sync --to-disk` skipped them, as the manifest says it
//! should; and `organize` refused their eleven views, because each still
//! carried the 3.0.0 footer. Two correct rules left a view with no owner, and
//! the operator deleted eleven files by hand on an estate the tool had just
//! called upgraded.
//!
//! The gate now accepts the one difference that carries no hand edit, the
//! footer's version (vc's ruling, 2026-09-14) -- so the second arm holds the
//! other half of the same line: a one-byte body edit is still refused.

use crate::common::{Fixture, facade_ctx, v2_estate_in_git, v2_thread};
use intentsvcs::address::{Address, Entity};
use intentsvcs::facade::Facade;
use std::path::PathBuf;

/// A view's text with its footer naming an older Intent, the only change.
fn stale_footer(text: &str) -> String {
  let marker = "_Generated by Intent v";
  let at = text
    .rfind(marker)
    .expect("a generated view carries a footer");
  let rest = &text[at + marker.len()..];
  let end = rest.find(' ').expect("the version ends at a space");
  format!("{}{marker}2.99.0{}", &text[..at], &rest[end..])
}

/// A migrated estate whose closed thread ST0002 carries views an older Intent
/// rendered, and no manifest -- the dormant estate courses-vc measured. With
/// `edit_a_byte`, ST0002's info view also differs from the render by one body
/// byte. Returns the fixture, ST0002's views, and ST0002's canon as committed.
fn dormant_estate(edit_a_byte: bool) -> (Fixture, Vec<PathBuf>, String) {
  let fx = v2_estate_in_git();
  v2_thread(&fx, "ST0001", "WIP");
  v2_thread(&fx, "ST0002", "Completed");
  fx.git_commit_all();
  Facade::upgrade(&fx.project(), &facade_ctx()).expect("the v2 estate converts");

  // The v2 source `info.md` is still at the path the v3 view takes -- the v2
  // prune removes bucket files, not a flat thread directory -- so it is cleared
  // first, and the thread is realised as a v3 binary renders it.
  let project = fx.project();
  let generated = [
    project.info_view("ST0002"),
    project.acceptance_view("ST0002"),
  ];
  for view in &generated {
    let _ = std::fs::remove_file(view);
  }
  let views: Vec<PathBuf> = {
    let mut facade = Facade::open(fx.project(), facade_ctx()).expect("open the converted estate");
    let hydrated = facade
      .hydrate(&Address {
        authority: None,
        entity: Entity::Thread {
          id: "ST0002".to_string(),
        },
        format: None,
      })
      .expect("the closed thread realises");
    generated
      .iter()
      .filter(|v| hydrated.contains(v))
      .cloned()
      .collect()
  };
  assert!(!views.is_empty(), "the fixture realised no view for ST0002");
  std::fs::remove_file(fx.path("intent/.intentfiles")).expect("drop the manifest");
  for view in &views {
    let text = std::fs::read_to_string(view).expect("read the view");
    std::fs::write(view, stale_footer(&text)).expect("stale its footer");
  }
  if edit_a_byte {
    let info = fx.project().info_view("ST0002");
    let text = std::fs::read_to_string(&info).expect("read the info view");
    std::fs::write(&info, text.replacen("# ", "#  ", 1)).expect("edit one body byte");
  }
  fx.git_commit_all();
  let canon = fx.read("intent/.canon/st/ST0002.json");
  (fx, views, canon)
}

#[test]
fn a_footer_stale_view_of_an_undeclared_thread_is_removed_by_upgrade_and_its_canon_is_untouched() {
  let (fx, views, canon) = dormant_estate(false);
  let done = Facade::upgrade(&fx.project(), &facade_ctx()).expect("the re-run converges");

  assert!(
    done.dehydrate_refused.is_empty(),
    "a footer-only view was refused: {:?}",
    done.dehydrate_refused
  );
  for view in &views {
    assert!(
      !view.exists(),
      "{} is still on disk: an undeclared thread's footer-stale view has no owner",
      view.display()
    );
    assert!(
      done.dehydrated.contains(view),
      "{} went without being named in the report: {:?}",
      view.display(),
      done.dehydrated
    );
  }
  assert_eq!(
    fx.read("intent/.canon/st/ST0002.json"),
    canon,
    "removing ST0002's views changed ST0002's canon"
  );
}

#[test]
fn a_view_whose_body_differs_by_one_byte_is_still_refused_and_named() {
  let (fx, _views, _canon) = dormant_estate(true);
  let done = Facade::upgrade(&fx.project(), &facade_ctx()).expect("the re-run converges");

  let info = fx.project().info_view("ST0002");
  assert!(
    info.exists(),
    "a view carrying a one-byte body edit was removed: the gate took more than the footer"
  );
  assert!(
    !done.dehydrated.contains(&info),
    "the edited view is reported as dehydrated"
  );
  assert!(
    done
      .dehydrate_refused
      .iter()
      .any(|r| r.contains(&info.display().to_string())),
    "the refusal does not name the edited view: {:?}",
    done.dehydrate_refused
  );
}
