#!/usr/bin/env bash
# reconvert.sh <project-dir> [--commit] -- re-convert a LANDED project from its v2 source on the current dev pair.
#   1. find the migration commit (first commit adding intent/.canon/st); the v2 source is its parent
#   2. restore intent/st exactly as at that parent (v2 views + buckets); drop the committed canon and the store
#   3. config.json back to the parent's, then re-apply the hand-set fields the landing added (project_name, author, languages)
#   4. hop 2 (pair read in the same command), hop 3 x2, per-machine ignores
#   5. at-accounting (devbin/vc's) + verify-canonical; NO commit unless --commit, and then --only the intent paths
set -u; P="$1"; MODE="${2:-}"; cd "$P" || exit 1; N=$(basename "$P"); S=${VC_SCRATCH:-/tmp/vc-scratch}; mkdir -p "$S"; L="$S/reconv-$N"
I=~/Devel/prj/Intent/bin/intent3; AT=~/Devel/prj/Devbin/intent/whiteboard/vc/at-accounting.sh
mig=$(git log --diff-filter=A --format=%h -- intent/.canon/st | tail -1); [ -n "$mig" ] || { echo "$N: no migration commit"; exit 2; }
src="$mig^"; echo "## $N: migration $mig, v2 source at $src ($(git log -1 --format=%s "$src" | cut -c1-50)); dirty before: $(git status --porcelain | wc -l | tr -d ' ')"
[ "$(git status --porcelain | grep -vcE '^\?\? intent/events.jsonl$')" -eq 0 ] || { echo "$N: tree not clean -- refusing"; git status --porcelain | head -5; exit 3; }
keep=$(jq -c '{project_name, author, languages}' intent/.config/config.json)
git rm -r -q --cached intent/st intent/.canon 2>/dev/null; rm -rf intent/st intent/.canon intent/.cache
git checkout -q "$src" -- intent/st intent/.config/config.json && echo "restored: config $(jq -r .intent_version intent/.config/config.json), st dirs $(ls -d intent/st/ST[0-9]* 2>/dev/null | wc -l | tr -d ' '), buckets [$(ls -d intent/st/COMPLETED intent/st/CANCELLED intent/st/NOT-STARTED 2>/dev/null | xargs -n1 basename | tr '\n' ' ')]"
jq --argjson k "$keep" '. + ($k | with_entries(select(.value != null)))' intent/.config/config.json > "$L.cfg" && cp "$L.cfg" intent/.config/config.json; echo "re-applied: $(jq -c '{project_name, author, languages}' intent/.config/config.json)"
v=$(jq -r .intent_version intent/.config/config.json); case "$v" in 2.19.*|3.*) echo "hop1: not needed ($v)";; *) ~/Devel/prj/Intentv2/bin/intent upgrade < /dev/null > "$L.h1" 2>&1; rc=$?; echo "hop1 rc=$rc :: $(grep -E '^ok: upgraded' "$L.h1" | cut -c1-80)"; [ $rc -eq 0 ] || { tail -3 "$L.h1" | cut -c1-200; exit 5; }; git ls-tree -r --name-only "$src" -- intent/st | grep '/acceptance.md$' | xargs git checkout -q "$src" -- 2>/dev/null; echo "hop1: ratified acceptance.md files restored from $src (v2 re-punctuation reverted); config now $(jq -r .intent_version intent/.config/config.json)"; jq --argjson k "$keep" '. + ($k | with_entries(select(.value != null)))' intent/.config/config.json > "$L.cfg" && cp "$L.cfg" intent/.config/config.json;; esac
echo "pair: $($I --version 2>&1 | head -1)"; $I upgrade > "$L.h2" 2>&1; rc=$?; echo "hop2 rc=$rc :: $(grep -E '^(migrated|ok|error)' "$L.h2" | tr '\n' '|' | cut -c1-160)"; [ $rc -eq 0 ] || { tail -4 "$L.h2" | cut -c1-200; exit 4; }
$I claude upgrade --apply > "$L.h3" 2>&1; echo "hop3 rc=$? :: $(grep -E '^ok' "$L.h3")"; $I claude upgrade --apply > "$L.h3b" 2>&1; echo "hop3 again: $(grep -E '^ok' "$L.h3b")"
git check-ignore -q intent/events.jsonl || printf 'intent/events.jsonl\n' >> .gitignore; git check-ignore -q 'intent/.backup/x' || printf 'intent/.backup/\n' >> .gitignore
bash "$AT" "$P" > "$L.acct" 2>&1; arc=$?; echo "--- accounting rc=$arc:"; grep -E "SHORTFALL|VERDICT|NOT|ERROR" "$L.acct" | head -8 | cut -c1-140; vline=$(grep -E "^\s*VERDICT:" "$L.acct" | head -1); [ $arc -eq 0 ] && [ -n "$vline" ] && ACCT_OK=1 || ACCT_OK=0; echo "accounting gate: $([ $ACCT_OK -eq 1 ] && echo PASS || echo "NOT A PASS (rc $arc; verdict line: ${vline:-none})")"
echo "--- verifier: $(bash ~/Devel/prj/Intent/intent/whiteboard/vc/verify-canonical.sh "$P" 2>&1 | grep -E 'check\(s\)')"
acct=$vline; pairline=$($I --version 2>&1 | head -1)
{ printf 'intent: re-convert from the v2 source on %s -- hop 2 had dropped AC/AT rows silently\n\n' "$pairline"; printf 'The landing at %s ran hop 2 on a pair whose row parser dropped any\n`status:` or `satisfied:` value followed by a period, a sentence or a\nparenthetical, and printed ok (arca_cli lost 26 of 55 ATs; the fleet 49).\nRe-converted here from the v2 source at %s^: intent/st and config.json\nrestored as at that commit, the committed canon and the store dropped,\nhop 1 on the frozen v2 where the parent was below the floor (ratified\nacceptance.md files restored after it), hop 2 on the fixed pair, hop 3\ntwice. Accounting (devbin/vc at-accounting.sh, source = store = view):\n%s\nverify-canonical.sh: 0 failed.\n\n(C) hello@matthewsinclair.com\n' "$mig" "$mig" "$acct"; } > "$S/reconv-msg-$N.txt"
echo "--- changed: $(git status --porcelain | wc -l | tr -d ' ') paths; peer-owned among them: $(git status --porcelain | grep -cE 'whiteboard/(cc|ic|dc|ac|hv)/')"
if [ "$MODE" = "--commit" ]; then [ "${ACCT_OK:-0}" -eq 1 ] || { echo "NOT committing: accounting gate failed"; exit 6; }; git add -A -- intent/st intent/.canon intent/.config intent/todo.md intent/steel_threads.md .gitignore AGENTS.md CLAUDE.md .claude/settings.json usage-rules.md 2>/dev/null; git commit -q --only -F "$S/reconv-msg-$N.txt" -- intent/st intent/.canon intent/.config intent/todo.md intent/steel_threads.md .gitignore AGENTS.md CLAUDE.md .claude/settings.json usage-rules.md && echo "committed $(git log --oneline -1 | cut -c1-8) [$(git show --stat --format= HEAD | tail -1 | tr -s ' ')]"; fi
