project_name: "intent"
default_status: "todo"
statuses: ["todo", "wip", "done", "cancelled", "archived"]
labels: []
milestones: []
date_format: yyyy-mm-dd
max_column_width: 20
auto_open_browser: true
default_port: 6420
remote_operations: false
auto_commit: false
zero_padded_ids: 3
