#!/bin/bash
# drift_check.sh -- do the two descriptions of the command surface still agree?
#
# THE PROBLEM (EXP-02). Two artefacts carry the verb and flag sets:
#
#   parity/cmd-<command>.md   GENERATED by gen_inventory.sh from live probes
#   surface/dispatch-table.json   AUTHORED, then enriched with target /
#                                 disposition / invariants
#
# That is derive-then-enrich, not copy-paste, and it is fine. What is not fine
# is that nothing keeps them in agreement AFTERWARDS. They agreed exactly when
# the table was written. Agreement with no mechanism is the divergent-copy
# shape, and this file is the mechanism.
#
# IT REPORTS. IT DOES NOT RESOLVE. This is the whole design and it is not
# timidity:
#
#   the inventory is MEASUREMENT   -- what the tool did when we ran it
#   the table is JUDGEMENT         -- what we decided that means for v3
#
# So a divergence has two possible causes with OPPOSITE remedies. Either the
# v2 surface moved (the inventory is right, the table needs re-authoring) or a
# judgement in the table was wrong or deliberate (the table is right, and an
# alias or an internal function is being recorded differently on purpose). A
# tool that "fixed" the disagreement would pick one at random and silently
# destroy the other, which is strictly worse than the drift it set out to cure
# -- and worse than today's position, because today they agree.
#
# Exit 0 when they agree, 1 when they do not. Non-zero is NOT a failure of this
# script; it is the finding, and it wants a human.

set -uo pipefail

die() { echo "error: $1" >&2; exit 2; }

command -v jq >/dev/null 2>&1 || die "jq is required and was not found on PATH"

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARITY_DIR="$(cd "$HERE/.." && pwd)"
REPO_ROOT="$(cd "$PARITY_DIR/../../../.." && pwd)"

CANON="${CANON:-$REPO_ROOT/surface/dispatch-table.json}"
[ -f "$CANON" ] || die "dispatch-table canon not found: $CANON"
[ -d "$PARITY_DIR" ] || die "parity inventory dir not found: $PARITY_DIR"

# A file matching NO inventory is not a silent pass. The inventory covers the
# 26 `bin/intent_*` commands; families that have no cmd-*.md by construction
# (ac/at share one binary; agents is a plugin; claude is a dispatcher arm;
# version is a global) are named here rather than skipped by accident, because
# "no file, therefore agreed" is exactly the absence-as-meaning failure this
# toolchain keeps refusing.
NO_INVENTORY_BY_DESIGN="ac at version"

# EXPLAINED DIFFERENCES -- adjudicated once, with the cause named, so this check
# keeps its signal. A checker that always exits 1 is a checker nobody reads, and
# the cry-wolf failure is the one this toolchain keeps refusing.
#
# The hazard of an exceptions list is the mirror of that: a guard scoped to what
# is already clean certifies the status quo. So each entry names ONE token in
# ONE family and says WHY, and anything else in that family still reports. These
# were all found on the first real run, and one of the four was NOT explainable
# -- `todo list` was genuinely missing from the authored table and was added
# rather than excused. That is the ratio to watch: if a later run produces only
# excuses, the check has stopped working.
#
# Format: <family>:<token>|<side>|<reason>
EXPLAINED="
st:organise|table|An alias normalised at bin/intent_st:289-292 BEFORE dispatch, so the inventory's verb extractor cannot see it -- it reads case arms, and by then the spelling is gone. Real surface; the table is right and richer.
st_zero:install|inventory|The inventory reads it as a verb; the table records it as an ARGUMENT VALUE on the st_zero entry (\`subcommand\` arity 0..1, values [install]). Same fact, two defensible shapes -- the table's is right because \`install\` takes its own flags.
st_zero:st zero|table|The second spelling of the same family (bin/intent_st:1610 execs this binary). Recorded as an alias on the entry; the inventory has no concept of a cross-family alias.
st:zero|inventory|A RATIFIED CORRECTION, not drift, and the first entry here of that kind. v2 spells it \`st zero\`; v3 spells it \`st bootstrap\` (hv, 2026-08-15). \`zero\` was never a verb -- it is the name of the thing, Steel Thread Zero -- which is why \`st zero install\` parses noun-then-verb. The inventory is RIGHT about v2 and the table is RIGHT about v3; they are describing different surfaces on purpose. This pair is the reason the check must not auto-resolve.
st:bootstrap|table|The v3 spelling of the row above. Not a new command: \`intent bootstrap\` at top level is unrelated (global first-time setup) and coexists deliberately -- the same verb at two levels, bootstrap the machine and bootstrap the project's steel-thread structure.
agents:generate|inventory-is-wrong|cmd-agents.md says \"None -- single-action command\". That is FALSE: \`intent agents --help\` lists five verbs. agents is a PLUGIN command, so its dispatch is not in bin/intent_* and the static extractor never saw it. The inventory has a blind spot for plugin dispatch; the table is right. Same for init/sync/template/validate.
agents:init|inventory-is-wrong|See agents:generate -- the inventory's plugin blind spot.
agents:sync|inventory-is-wrong|See agents:generate -- the inventory's plugin blind spot.
agents:template|inventory-is-wrong|See agents:generate -- the inventory's plugin blind spot.
agents:validate|inventory-is-wrong|See agents:generate -- the inventory's plugin blind spot.
"

is_explained() { # family token
  printf '%s\n' "$EXPLAINED" | grep -qF "$1:$2|"
}

# Filter a NEWLINE-separated token list down to those with no explanation.
#
# Newline-separated, not space-separated, and that is load-bearing: a token can
# contain a space (`st zero` is a cross-family alias, one token, two words).
# The first version of this took "$@" and word-split, so `st zero` became `st`
# and `zero`, neither matched its explanation, and the row reported as drift
# forever while looking exactly like a real finding. Caught by the mutation
# test, not by reading -- the explained-list case passed and this one did not.
unexplained() { # family; tokens on stdin, one per line
  local fam="$1" t out=""
  while IFS= read -r t; do
    [ -n "$t" ] || continue
    is_explained "$fam" "$t" || out="$out$t"$'\n'
  done
  printf '%s' "$out"
}

drift=0
checked=0
skipped=""

for fam in $(jq -r '.families[].name' "$CANON"); do
  inv="$PARITY_DIR/cmd-$fam.md"
  if [ ! -f "$inv" ]; then
    case " $NO_INVENTORY_BY_DESIGN " in
      *" $fam "*) skipped="$skipped $fam(by-design)" ;;
      *) printf 'DRIFT  %-12s no cmd-%s.md, and it is not on the by-design list -- either the inventory did not regenerate it or this family is new\n' "$fam" "$fam"
         drift=$((drift + 1)) ;;
    esac
    continue
  fi
  checked=$((checked + 1))

  # Inventory verbs: the single-backticked cells of its Subcommands table.
  inv_verbs="$(awk '/^## Subcommands/,/^## Flags/' "$inv" |
    grep -oE '^\| `[a-z_][a-z_-]*`' | tr -d '|` ' | sort -u | tr '\n' ' ')"

  # Table verbs: entry paths minus the family prefix, plus any aliases, minus
  # the bare family row (which is the family itself, not a verb).
  tbl_verbs="$(jq -r --arg f "$fam" '
    .families[] | select(.name==$f) | .entries[] |
    ([.path] + (.aliases // []))[] ' "$CANON" |
    sed "s/^$fam *//" | grep -v "^$fam\$" | grep -v '^$' | sort -u)"

  # Both sides as newline-separated lists throughout: a token may contain a
  # space (`st zero`), so space-separation would split one token into two.
  inv_list="$(printf '%s\n' "$inv_verbs" | tr ' ' '\n' | grep -v '^$' | sort -u)"
  only_inv="$(comm -23 <(printf '%s\n' "$inv_list") <(printf '%s\n' "$tbl_verbs") )"
  only_tbl="$(comm -13 <(printf '%s\n' "$inv_list") <(printf '%s\n' "$tbl_verbs") )"

  new_inv="$(printf '%s\n' "$only_inv" | unexplained "$fam")"
  new_tbl="$(printf '%s\n' "$only_tbl" | unexplained "$fam")"

  if [ -n "${new_inv//[$'\n' ]/}" ] || [ -n "${new_tbl//[$'\n' ]/}" ]; then
    printf 'DRIFT  %-12s\n' "$fam"
    [ -n "$new_inv" ] && printf '         only in the MEASURED inventory: %s\n' "$(printf '%s' "$new_inv" | tr '\n' ' ')"
    [ -n "$new_tbl" ] && printf '         only in the AUTHORED table:     %s\n' "$(printf '%s' "$new_tbl" | tr '\n' ' ')"
    drift=$((drift + 1))
  elif [ -n "$only_inv" ] || [ -n "$only_tbl" ]; then
    # Differences exist but every one is adjudicated. Say so out loud: a silent
    # pass here would hide that the two artefacts are NOT identical, only
    # reconciled, and the next reader should know which.
    printf 'explained  %-12s %s\n' "$fam" "$(printf '%s\n%s' "$only_inv" "$only_tbl" | tr '\n' ' ' | tr -s ' ')"
  fi
done

echo
printf 'checked %s families; %s skipped by design (%s)\n' "$checked" "$(printf '%s' "$skipped" | wc -w | tr -d ' ')" "${skipped# }"

if [ "$drift" -gt 0 ]; then
  cat <<'EOF'

  DRIFT FOUND in the families above. This script deliberately does NOT fix it.

  The inventory is MEASUREMENT (what the tool did). The table is JUDGEMENT
  (what we decided that means for v3). A divergence has two causes with
  opposite remedies:

    the v2 surface MOVED   -> the inventory is right; re-author the table row
    a judgement DIFFERS    -> the table is right; an alias or internal
                              function is recorded differently on purpose,
                              and the difference should be stated on the row

  Picking one mechanically would silently destroy the other. Decide per row.
EOF
  exit 1
fi

echo "ok: the measured inventory and the authored dispatch table agree"
exit 0
