#!/bin/bash
# gen_inventory.sh -- emit the per-command parity inventory from measured data.
#
# The inventory is GENERATED, not written. It gets re-measured after the consumer
# sweeps and again during WP-06, and a hand-typed list cannot be diffed: the
# "314 AT rows" figure that was wrong by 5x sat in three documents precisely
# because nobody could re-run it. Every file below names the revision it was
# taken at.
#
# Sources, in order of authority:
#   1. runtime probes   -- what the tool actually did (probes/*.tsv)
#   2. dispatch arms    -- what the source intends (extract_verbs.sh)
#   3. arg-parsing arms -- the flag grammar (extract_flags.sh)
#   4. lib/help/*.help.md -- documentation, cross-checked for drift, never trusted
#
# Help is source 4 and last for a reason: it covers 11 of 27 commands, its
# @usage/@options/@arguments grammar is used by exactly one file, and it still
# describes `upgrade` as "Upgrade from STP to Intent v2.1.0" at v2.19.0.

set -uo pipefail

SP="${SP:?set SP}"
WT="${WT:-$SP/wt}"
OUTDIR="${OUTDIR:?set OUTDIR}"
REV="$(cd "$WT" && git rev-parse --short HEAD)"
DATE="$(date -u +%Y-%m-%d)"
TSV="$SP/probes/toplevel.tsv"

mkdir -p "$OUTDIR"

# probe_row <label> -> "rc|out|err|outfirst|errfirst"
probe_row() {
  awk -F'\t' -v L="$1" 'NR>1 && $1==L {printf "%s|%s|%s|%s|%s", $2,$3,$4,$5,$6; found=1} END{if(!found) printf "-|-|-|-|-"}' "$TSV"
}

emit_probe_table() {
  local cmd="$1" k r
  printf '| probe | exit | stdout | stderr | first line |\n'
  printf '| ----- | ---- | ------ | ------ | ---------- |\n'
  for k in bare help badflag noproj; do
    r="$(probe_row "$cmd.$k")"
    local rc ob eb of ef
    IFS='|' read -r rc ob eb of ef <<< "$r"
    [ "$rc" = "-" ] && continue
    local first="$of"; [ -z "$first" ] && first="$ef"
    [ -z "$first" ] && first="_(no output)_"
    local label="$k"
    case "$k" in
      bare)    label='`intent '"$cmd"'`' ;;
      help)    label='`--help`' ;;
      badflag) label='unknown flag' ;;
      noproj)  label='outside a project' ;;
    esac
    printf '| %s | %s | %sB | %sB | %s |\n' "$label" "$rc" "$ob" "$eb" "${first//|/\\|}"
  done
}

# gen <command> <script-path> [help-basename]
gen() {
  local cmd="$1" script="$2" helpname="${3:-$1}"
  # `cmd-` prefix, not a bare `<command>.md`. Two of these command names collide
  # with filenames the toolchain treats as special, and macOS matches filenames
  # case-insensitively: a generated `claude.md` is picked up as this directory's
  # CLAUDE.md and injected into every future session as instructions, and
  # `agents.md` shadows the AGENTS.md convention the same way. The prefix makes
  # the collision unconstructible rather than special-casing the two known names.
  local f="$OUTDIR/cmd-$cmd.md"
  local helpfile="$WT/lib/help/$helpname.help.md"
  local verbs flags

  # Three commands cannot be read off a single script's dispatch:
  #   ac/at  -- intent_acceptance dispatches on the NOUN first (ac|at), so the
  #             extractor returns "ac at" rather than either verb set. The real
  #             verbs are the inner case at intent_acceptance:1330 and :1343.
  #   claude -- dispatched in bin/intent:79-118, not in any one plugin script.
  # Each is stated explicitly and verified by invocation like every other row.
  case "$cmd" in
    ac)     verbs="list status satisfy gate descope withdraw rescope reinstate" ;;
    at)     verbs="list lint red green na done notdone" ;;
    claude) verbs="subagents skills upgrade prime rules hook ws start" ;;
    *)      verbs="$(bash "$SP/extract_verbs.sh" "$script" 2>/dev/null | grep -vE '^(help|--help|-h)$' | tr '\n' ' ')" ;;
  esac
  flags="$(bash "$SP/extract_flags.sh" "$script" 2>/dev/null | tr '\n' ' ')"

  {
    printf '# Parity inventory: `intent %s`\n\n' "$cmd"
    printf '> Measured at `%s`, %s. Generated by `parity/tools/gen_inventory.sh` -- re-run it rather than editing this file.\n\n' "$REV" "$DATE"

    # printf '- ...' would be parsed as an option: a leading dash in the FORMAT
    # string makes bash's builtin reject the whole call. Route these through %s.
    printf '%s\n' "- **v2 source**: \`${script#$WT/}\`"
    if [ -f "$helpfile" ]; then
      printf '%s\n' "- **help file**: \`lib/help/$helpname.help.md\`"
    else
      printf '%s\n' "- **help file**: none -- \`intent help $cmd\` falls through to the \"no help available\" path (\`bin/intent_help:37\`)"
    fi

    if [ -n "${verbs// /}" ]; then
      printf '\n## Subcommands\n\n'
      printf 'Taken from the main dispatch and verified by invocation. `help`/`--help`/`-h` arms are omitted; they are covered in the probe table.\n\n'
      printf '| verb |\n| ---- |\n'
      for v in $verbs; do printf '| `%s` |\n' "$v"; done
    else
      printf '\n## Subcommands\n\nNone -- single-action command (no dispatch `case` on a command variable).\n'
    fi

    if [ -n "${flags// /}" ]; then
      printf '\n## Flags\n\n'
      printf 'Parsed as `case` arms anywhere in the script, including nested arg loops.\n\n'
      printf '| flag |\n| ---- |\n'
      for v in $flags; do printf '| `%s` |\n' "$v"; done
    else
      printf '\n## Flags\n\nNone parsed.\n'
    fi

    printf '\n## Observed behaviour\n\n'
    emit_probe_table "$cmd"
    printf '\n'
  } > "$f"
  printf '  wrote %s\n' "${f#$OUTDIR/}"
}

for spec in \
  "st:$WT/bin/intent_st" \
  "wp:$WT/bin/intent_wp" \
  "issues:$WT/bin/intent_issues" \
  "todo:$WT/bin/intent_todo" \
  "info:$WT/bin/intent_info" \
  "init:$WT/bin/intent_init" \
  "bootstrap:$WT/bin/intent_bootstrap" \
  "config:$WT/bin/intent_config" \
  "doctor:$WT/bin/intent_doctor" \
  "upgrade:$WT/bin/intent_upgrade" \
  "critic:$WT/bin/intent_critic" \
  "lang:$WT/bin/intent_lang" \
  "llm:$WT/bin/intent_llm" \
  "learn:$WT/bin/intent_learn" \
  "modules:$WT/bin/intent_modules" \
  "organize:$WT/bin/intent_organize" \
  "plugin:$WT/bin/intent_plugin" \
  "ext:$WT/bin/intent_ext" \
  "treeindex:$WT/bin/intent_treeindex" \
  "fileindex:$WT/bin/intent_fileindex" \
  "help:$WT/bin/intent_help" \
  "st_zero:$WT/bin/intent_st_zero" \
  ; do
  gen "${spec%%:*}" "${spec#*:}"
done

# ac/at share one binary; st_zero's help file is spelled differently.
gen "ac" "$WT/bin/intent_acceptance"
gen "at" "$WT/bin/intent_acceptance"
gen "agents" "$WT/intent/plugins/agents/bin/intent_agents"
gen "claude" "$WT/intent/plugins/claude/bin/intent_claude_rules" "claude"
