#!/bin/bash
# gen_register.sh -- first-pass keep/retire/deviate register from burn data.
#
# Primary axis is the BURN RATIO from burn.sh: how many of a file's tests change
# result when INTENT_BIN is redirected to /usr/bin/false. That is empirical where
# assertion-parsing is inferential -- treeindex_commands.bats looks like 53 CLI
# tests and is in fact 53 tests that exec bin/intent_treeindex directly, bypassing
# the dispatcher; no amount of reading its assertions reveals that, and one
# redirected binary does.
#
# Files that never reach the CLI are then sub-classified mechanically by HOW they
# miss it. Nothing is guessed: a file matching no rule is emitted as UNCLASSIFIED
# for vc to adjudicate, per the work order.

set -uo pipefail
SP="${SP:?}"; WT="${WT:?}"
BURN="$SP/burn.tsv"
cd "$WT"

classify_none() {
  local f="$1"
  if grep -qE '\$\{INTENT_BIN_DIR\}/intent_[a-z_]+' "$f"; then
    echo "deviate|sub-script entry point|Invokes bin/intent_<sub> directly, bypassing the dispatcher (PROJECT_ROOT resolution, INTENT_ORIG_CWD, cd to root -- bin/intent:198-218). No equivalent under one binary; needs a semantic rewrite, not a path swap."
  elif grep -qE 'source "\$\{?(INTENT_PROJECT_ROOT|INTENT_HOME)\}?/bin/intent|source .*(rules_lib|critic_runner)\.sh' "$f"; then
    echo "retire|shell-function unit test|Sources a shell file and calls its functions directly. Dies with bash; there is no binary to retarget."
  elif ! grep -qE 'run_intent|\$INTENT_BIN\b' "$f"; then
    # Never invokes the CLI in any form. Not a conformance test at all: it pins
    # this repository's own content (skills, rules, docs, attribution) and
    # survives a binary swap untouched. This is the widened rule -- the first
    # version keyed on `git ls-files`/`grep -r` and left seven such files
    # UNCLASSIFIED, certifying the shapes it already knew about.
    echo "out-of-scope|no CLI invocation|Never invokes the CLI. Asserts this repository's own content, not the command surface; survives a binary swap untouched and is not a conformance test."
  else
    # Invokes the CLI and yet nothing changes when the binary is redirected.
    # That combination is genuinely odd and is flagged rather than guessed.
    echo "UNCLASSIFIED|invokes CLI, zero burn|Calls the CLI but no test changes result when the binary is redirected. Either the invocation is inert or the assertions do not depend on it. Needs adjudication."
  fi
}

REV="$(cd "$WT" && git rev-parse --short HEAD)"
DATE="$(date -u +%Y-%m-%d)"
OUT="${OUT:-$SP/register.md}"

{
  cat <<PREAMBLE
# Keep / retire / deviate register -- first pass (ST0056 / WP-01, AC-01.3)

> Measured at \`$REV\` on $DATE by ic. Regenerated by \`tools/gen_register.sh\` from \`tools/burn.sh\` output; do not hand-edit rows.

## How each row was decided

The classification axis is the **burn ratio**: each file is run twice, once with the default \`INTENT_BIN\` and once with \`INTENT_BIN=/usr/bin/false\`, and the delta is the number of tests that actually reach the top-level CLI.

This is empirical where reading assertions is inferential, and the difference is not academic. \`treeindex_commands.bats\` reads as 53 CLI tests and is in fact 53 tests that exec \`bin/intent_treeindex\` directly, bypassing the dispatcher entirely; its burn is zero. \`claude_with_intent.bats\` read as a CLI test, reported zero burn, and turned out to alias the binary through an unbraced \`\$INTENT_BIN_DIR/intent\` that the retarget sweep had missed -- **the burn measurement found a hole in the retarget that four separate grep passes did not.**

| burn | meaning | class |
| ---- | ------- | ----- |
| all tests | the file exercises the CLI and nothing else | **keep** -- runs unmodified against \`INTENT_BIN\` |
| zero, and it calls \`bin/intent_<sub>\` | tests an entry point v3 will not have | **deviate** -- semantic rewrite, not a path swap |
| zero, and it sources a shell file | unit-tests a bash function | **retire** -- dies with the shell |
| zero, and it never invokes the CLI | pins this repo's own content | **out-of-scope** -- not a conformance test |
| some | mixed concerns in one file | **split** -- needs per-test rows before WP-05 leans on it |
| any, but baseline not green | the delta carries no information | **UNCLASSIFIED** |

A file matching no rule is emitted UNCLASSIFIED rather than assigned a best guess. A wrong \`retire\` is coverage that disappears at the cut with nobody watching, which is the defect the AT grammar existed to kill; the refuse-lossy discipline applies to classification exactly as it applies to migration.

**Scope note:** \`split\` is a first-pass verdict, not a final one. Those files carry both portable and non-portable tests and need per-test rows; this pass deliberately stops at the file level rather than guessing which half is which.

## Rows

PREAMBLE
  printf '| test file | tests | burn | class | basis | notes |\n'
  printf '| --------- | ----- | ---- | ----- | ----- | ----- |\n'
  tail -n +2 "$BURN" | while IFS=$'\t' read -r f total dfail burn status; do
    case "$status" in
      FULL)
        printf '| `%s` | %s | %s/%s | keep | full burn | Every test changes result when the binary is redirected: the file exercises the CLI and nothing else. |\n' "$f" "$total" "$burn" "$total"
        ;;
      NONE)
        IFS='|' read -r cls basis note <<< "$(classify_none "$f")"
        printf '| `%s` | %s | 0/%s | %s | %s | %s |\n' "$f" "$total" "$total" "$cls" "$basis" "$note"
        ;;
      MIXED)
        printf '| `%s` | %s | %s/%s | split | partial burn | %s of %s tests reach the CLI; the remainder do not. Needs per-test rows before WP-05 relies on it. |\n' "$f" "$total" "$burn" "$total" "$burn" "$total"
        ;;
      UNSTABLE)
        printf '| `%s` | %s | -- | UNCLASSIFIED | unstable baseline | %s test(s) already fail with the default binding, so the burn delta carries no information. Fix or explain before classifying. |\n' "$f" "$total" "$dfail"
        ;;
    esac
  done

  # Summary is computed from the rows just emitted, not tallied by hand.
  TOT=$(awk -F'\t' 'NR>1{T+=$2} END{print T}' "$BURN")
  CLI=$(awk -F'\t' 'NR>1{B+=$4} END{print B}' "$BURN")
  printf '\n## Summary\n\n'
  printf '| class | files | what WP-05 does with them |\n'
  printf '| ----- | ----- | ------------------------- |\n'
  for k in keep split deviate retire out-of-scope UNCLASSIFIED; do
    n=$(awk -F'|' -v K="$k" '/^\| `tests\// {gsub(/^ +| +$/,"",$5); if ($5==K) c++} END{print c+0}' "$OUT" 2>/dev/null)
    [ "${n:-0}" = "0" ] && continue
    case "$k" in
      keep)         w='Run unmodified against the v3 binary. These are the conformance suite.' ;;
      split)        w='Need per-test rows first: each mixes tests that reach the CLI with tests that do not.' ;;
      deviate)      w='Rewrite against the single-binary entry point, or retire with the sub-script they exercise.' ;;
      retire)       w='Retire with the shell. No binary to point them at.' ;;
      out-of-scope) w='Leave alone. They pin this repo content and are unaffected by the binary swap.' ;;
      *)            w='Adjudicate before WP-05 relies on them.' ;;
    esac
    printf '| **%s** | %s | %s |\n' "$k" "$n" "$w"
  done
  printf '\n**%s of %s tests (%.0f%%) actually reach the CLI.** The remaining %s do not, and cannot serve as v3 conformance evidence whatever their assertions say. That number is the honest size of the conformance estate, and it is the figure WP-05 should plan against rather than the 1235 headline.\n' \
    "$CLI" "$TOT" "$(echo "$CLI $TOT" | awk '{print 100*$1/$2}')" "$((TOT - CLI))"
  printf '\nBaseline: all %s tests pass with the default `INTENT_BIN`, so the retarget is behaviour-neutral. That run was taken in a sacrificial worktree and is evidence, not certification -- the authoritative full-suite run is matts.\n' "$TOT"
} > "$OUT"

# Count only data rows: the preamble also contains tables, so anchor on the
# leading `tests/ path cell rather than on line position.
echo "rows: $(grep -c '^| `tests/' "$OUT")"
awk -F'|' '/^\| `tests\// {gsub(/^ +| +$/,"",$5); c[$5]++} END {for (k in c) printf "  %-14s %s\n", k, c[k]}' "$OUT"
# Field indices: a leading "|" makes $1 empty, so file=$2, tests=$3, burn=$4,
# class=$5. Reading burn from $3 silently reported "0 tests".
awk -F'|' '/^\| `tests\// {gsub(/[^0-9]/,"",$3); gsub(/[^0-9\/]/,"",$4); split($4,a,"/"); T+=$3; B+=a[1]} END {printf "  %s tests, %s reaching the CLI (%.0f%%)\n", T, B, 100*B/T}' "$OUT"
