#!/usr/bin/env bash
# reference_current_check.sh -- does the committed docs/reference describe HEAD,
# measured against the ruled baseline?
#
# WHY THIS EXISTS. v3.0.3's tag shipped the previous cut's reference pages: the
# regeneration landed twenty-four minutes after the tag, and nothing reported
# it. intent/docs/releasing.md moved the step onto a page, which still depends
# on somebody reading the page at the right moment. hv ruled 2026-09-18 (vc
# decision 38, Q5) that the cut refuses a stale set instead. The release
# preflight calls this; it writes nothing and hands back the command that fixes
# what it finds, so the write stays in a human's hands.
#
# WHAT "CURRENT" MEANS. Both halves regenerated into a scratch directory at
# HEAD, with the baseline hv ruled 2026-09-17 (decision 25) -- the previous
# release tag -- and compared with the committed set. TWO LINES ARE MASKED ON
# BOTH SIDES AND NOTHING ELSE: the `Generated by ... at <time>` stamp and the
# `Revision this describes` row. The second one is not optional. The pages are
# committed ON TOP OF the revision they describe (releasing.md explains why that
# is the only self-consistent order), so they can never name the HEAD they are
# checked at, and an unmasked diff refuses every correct estate.
#
# `--tags` IS LOAD-BEARING. `git describe` without it reads annotated tags only,
# and every annotated tag here is v1 or v2, so the bare form answers v2.3.2 at
# every cut.
#
# EXITS: 0 current; 1 stale, with the diff and the fix command; 2 no verdict --
# a generator refused, or either side came back empty. An empty set against an
# empty set compares equal, so emptiness is a refusal and never a pass.
#
# Driven 2026-09-18 at efb44044b, both directions: the committed set (reported
# against v3.0.1) exits 1, and a set regenerated at HEAD against v3.0.3 exits 0
# with its time stamps different from the check's own regeneration.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(git -C "$HERE" rev-parse --show-toplevel)"
REFDIR="$ROOT/docs/reference"

no_verdict() {
  echo "error: reference_current_check: NO VERDICT -- $*" >&2
  exit 2
}

# The generators resolve revisions in the CURRENT directory's repository.
cd "$ROOT"

BASE="$(git describe --tags --abbrev=0 2>/dev/null)" || no_verdict "no release tag reachable from HEAD, so there is no ruled baseline"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
mkdir -p "$TMP/fresh" "$TMP/a" "$TMP/b"

"$HERE/gen_reference.sh" --rev HEAD --baseline "$BASE" --out "$TMP/fresh" > "$TMP/gen.log" 2>&1 \
  || no_verdict "gen_reference.sh refused: $(tail -1 "$TMP/gen.log")"
"$HERE/gen_cut_surface.sh" --rev HEAD --baseline "$BASE" --out "$TMP/fresh/cut-surface.md" > "$TMP/gen.log" 2>&1 \
  || no_verdict "gen_cut_surface.sh refused: $(tail -1 "$TMP/gen.log")"

[ -n "$(ls -A "$TMP/fresh")" ] || no_verdict "the regeneration wrote nothing"
[ -d "$REFDIR" ] && [ -n "$(ls -A "$REFDIR")" ] || no_verdict "no committed set at $REFDIR"

mask() {
  # shellcheck disable=SC2016  # the backticks are literal page text, not an expansion
  sed -e 's/^\*\*Generated by \(`[^`]*`\) at [^.]*\. Do not edit/**Generated by \1 at <time>. Do not edit/' \
      -e 's/^| Revision this describes .*/| Revision this describes <masked>/' "$1"
}

for f in "$TMP/fresh"/*; do mask "$f" > "$TMP/b/$(basename "$f")"; done
for f in "$REFDIR"/*; do mask "$f" > "$TMP/a/$(basename "$f")"; done

if diff -ru "$TMP/a" "$TMP/b" > "$TMP/diff" 2>&1; then
  echo "ok: docs/reference describes HEAD against $BASE"
  exit 0
fi

sed -e "s|$TMP/a|docs/reference|g" -e "s|$TMP/b|regenerated|g" "$TMP/diff"
cat <<EOF

stale: docs/reference does not describe HEAD against $BASE (diff above, committed on the - side).
  remedy: regenerate both halves and commit them BEFORE the release runs (intent/docs/releasing.md):
    BASE=\$(git describe --tags --abbrev=0)
    intent/st/ST0056/parity/tools/gen_reference.sh   --rev HEAD --baseline "\$BASE"
    intent/st/ST0056/parity/tools/gen_cut_surface.sh --rev HEAD --baseline "\$BASE" --out docs/reference/cut-surface.md
EOF
exit 1
