#!/bin/bash
# same_end_state_check.sh -- does a re-run over an INTERRUPTED estate reach the
# same end state as a CLEAN run?
#
# This is the gate hv authorised for the cutover. hv ruled the hoist "big bang
# and fix forward", which makes RE-RUNNING the normal recovery path rather than
# an exceptional one -- so the property the migrator must have is not rollback
# but re-runnability, and this is what measures it.
#
# WHY THE VERDICT IS A TREE DIFF AND NOT A CONSERVATION RUN. vc's correction,
# taken, and it is load-bearing rather than a preference. `conservation_check.sh`
# compares an ESTATE against CANON; "same end state as a clean run" compares two
# OUTPUTS. Every conservation predicate is anchored on the estate side, so two
# trees can differ in ways no such predicate reads. That is measured, not
# theoretical: ic's accretion passed reachability, presence, DOUBLED **and prose
# conservation itself**, because prose conservation iterates the ESTATE's
# sections and finds each one intact with generated bytes interleaved between
# them. PROSE GAINED IS INVISIBLE TO A CHECK THAT ONLY ASKS WHETHER WHAT LEFT
# ARRIVED. So the diff is the verdict and conservation is corroboration; the
# other way round, this gate would inherit that blind spot with nothing saying
# so.
#
# WHY IT IS A SIBLING OF conservation_check.sh AND NOT AN ARM OF IT (vc's
# ruling, with vc's test rather than vc's verdict, so the next reader can
# re-derive it): DO THE TWO TOOLS HAVE INPUTS THAT OVERLAP? Theirs takes a
# census and a tree; this takes trees. `--out-of-model` means nothing for a
# tree-to-tree comparison, and a census means nothing for one. There is no
# invocation of either that the other could serve, so folding them would not
# merge two checks -- it would put a second unrelated mode behind one name and
# one exit code, and a reader hitting exit 1 could not tell which question had
# failed without parsing the body. Same shape as provenance_check.sh /
# self_provenance_check.sh.
#
# NEITHER SUBSUMES THE OTHER ON ACCRETION, WHICH IS THE ONE PLACE THEY LOOK
# ALIKE. vc's ADDED-PROSE arm catches a section the canon holds that the estate
# never had -- on a FIRST run, with no second run in existence. This catches
# every-file-grew-and-none-shrank across TWO runs, including growth in files
# with no sections at all. Theirs cannot see this (there is only one tree) and
# this cannot see theirs (both trees are equally wrong).
#
# NO DUPLICATED MECHANISM, CHECKED RATHER THAN ASSERTED, because hv's constraint
# is about duped code and not about file count. Measured against
# conservation_check.sh with comments stripped, so prose about a mechanism is
# not counted as one: section extraction vc 6 / here 0; trim normalisation vc 11
# / here 0; path-to-owning-entity 0 / 0; hashing 2 / 2 -- and the hashing
# overlap is a bare `shasum -a 256` invocation on different subjects (vc hashes
# a trimmed section body, this hashes one relative path in two trees). A call to
# a standard tool with no logic in it cannot drift into two wrong behaviours,
# which is what lib_corpus.sh's precedent exists to prevent. If that judgement
# is wrong the remedy is a lib_, not a copy.
#
# EVERY SUBJECT IS NAMED FIRST AND UNCONDITIONALLY. vc's census had four
# members producing four files indistinguishable by inspection, and a consumer
# compared two unrelated estates and reported a NUMBER instead of refusing.
# Migration outputs are likewise anonymous trees. A verdict that cannot say
# which things it describes is not a verdict.
#
# ---------------------------------------------------------------------------
# THE INPUT ESTATE IS A REQUIRED SUBJECT, AND IT CLOSES A FALSE GREEN THIS FILE
# ARGUED ITS WAY TO AND THEN MISSED (dc, 2026-08-18).
#
# The empty-tree refusal below reasons that "an empty tree and a matching tree
# compare equal, so an empty subject REFUSES rather than passing", and states
# the general form: THE WAYS THIS TOOL CAN BE SILENTLY USELESS BOTH LOOK LIKE
# SUCCESS. That argument was written here, the EMPTY case was closed, and the
# UNCHANGED case was left open -- and the unchanged case is the reachable one,
# because two UNMIGRATED trees are not empty. They are full, and equal.
#
# It was reachable the day this landed and nobody had run it yet. Measured at
# `f5b5918c`: `intent upgrade` is advertised in `--help` and returns `error:
# 'upgrade' is a known command that is not implemented yet` at exit 2, because
# `Facade::upgrade` was uncommitted and the dispatch row unwired. Run the rig
# against that binary and every invocation writes nothing, so both outputs are
# byte-identical to the pristine input and this tool reports IDENTICAL, exit 0.
# A GREEN FROM A DOOR THAT NEVER OPENED -- ic's unfired-fixture trap one level
# up: not a kill landing too early, but a migrator that never ran.
#
# EXIT 2 AND NOT 1, DELIBERATELY. A migrator that changed nothing is a defect,
# but it is not the question THIS tool asks, and exit 1 would assert "the re-run
# did NOT reach the same end state", which is false -- both runs agree perfectly.
# Cannot-measure is the honest code and the same family as the empty arm.
#
# DERIVED, NOT NAMED. The cheap version looks for `thread.json` in the clean
# tree and refuses if there is none. That needle stops discriminating silently
# the day canon is renamed -- the allowlist lesson in a different hat. "Did the
# migration change ANYTHING" needs no knowledge of what canon looks like, and it
# reuses the comparison already here rather than adding a second mechanism.
#
# THE ALTERED COUNT PRINTS ON EVERY RUN, PASS OR FAIL, as this tool's own
# positive control -- self_provenance_check.sh's `27 matched` reasoning, which
# is the better form of the rule. A run reporting a plausible number of altered
# files is evidence the instrument reached its subject; a verdict alone is not.
# ---------------------------------------------------------------------------
#
# ROSTER: manual. It takes three tree arguments, so there is no bare invocation
# for a gate to make -- the same clause as guide_refs_check.sh. The run belongs
# to ic, whose harness kills the process for real (`intent upgrade &`, `kill -9`
# mid-run, `intent upgrade` again -- cc ruled against widening `facade::apply`
# or adding a test seam, because a migration dies when the PROCESS dies, not
# inside a function, and a real SIGKILL can leave a stray `.name.intent-tmp`
# from temp-and-rename that a hand-rolled partial write never would; a re-run
# has to be indifferent to that).
#
# Exit codes follow the family: 0 clean, 1 a finding, 2 cannot measure.

set -uo pipefail

die() { echo "same-end-state: $*" >&2; exit 2; }

INPUT="${1:-}"; A="${2:-}"; B="${3:-}"
[ -n "$INPUT" ] && [ -n "$A" ] && [ -n "$B" ] ||
  die "usage: same_end_state_check.sh <input-estate> <clean-run-tree> <rerun-tree>"
[ -d "$INPUT" ] || die "no tree at $INPUT -- the INPUT estate is missing"
[ -d "$A" ]     || die "no tree at $A -- the CLEAN-run subject is missing"
[ -d "$B" ]     || die "no tree at $B -- the RE-RUN subject is missing"

# TWO SUBJECTS THAT ARE ONE DIRECTORY REFUSE WITH THEIR OWN MESSAGE (vc, 2026-08-18,
# on the first version of the arm below). THE MIGRATION RUNS IN PLACE, so after a
# clean run there is no pristine input left -- `<input-estate>` has to be a copy
# taken BEFORE the run, not the path handed to the migrator. A rig that passes the
# migrated path as both input and clean-run makes the unchanged-arm compare a tree
# with itself, and it then refuses CORRECTLY FOR THE WRONG REASON: the message says
# "the migrator did nothing" and sends someone to debug a migrator that worked, when
# the defect is in the rig. Same axis as naming ACCRETION apart from non-determinism
# -- two conditions with different remedies must not share one message.
ri="$(cd "$INPUT" && pwd -P)"
ra="$(cd "$A" && pwd -P)"
rb="$(cd "$B" && pwd -P)"
[ "$ri" != "$ra" ] || die "the INPUT estate and the CLEAN-run tree are ONE directory ($ri) -- the migration runs in place, so the input must be a copy taken BEFORE the run"
[ "$ri" != "$rb" ] || die "the INPUT estate and the RE-RUN tree are ONE directory ($ri) -- same reason"
[ "$ra" != "$rb" ] || die "the CLEAN-run and RE-RUN trees are ONE directory ($ra) -- a tree compared with itself is IDENTICAL by construction and says nothing about the re-run"

# A PATH CONTAINING A NEWLINE WOULD SPLIT INTO TWO ENTRIES AND BE MISCOMPARED IN
# SILENCE, so it REFUSES instead (cc, 2026-08-18, from the same class in their own
# comparison: `find | xargs shasum` split on a filename with spaces and reported
# IDENTICAL over 1360 of 1361 files -- the skip was symmetric, so the verdict
# survived by luck rather than by method). A COMPARISON THAT SILENTLY OMITS A FILE
# READS EXACTLY LIKE ONE THAT COVERED EVERYTHING, which is this tool's own false
# green one layer down. Spaces and non-ASCII bytes are handled and canaried -- the
# estate really contains them, vc having measured two Lamplight paths carrying a
# curly quote -- and only a literal newline is refused, because that is the one
# `comm` and `read` cannot survive.
line_count() { find "$1" -type f | wc -l | tr -d ' '; }
nul_count()  { find "$1" -type f -print0 | tr -dc '\0' | wc -c | tr -d ' '; }

for subj in "$INPUT" "$A" "$B"; do
  [ "$(line_count "$subj")" = "$(nul_count "$subj")" ] ||
    die "a path under $subj contains a NEWLINE -- this compares line by line, so it would silently miscompare rather than measure"
done

ni="$(nul_count "$INPUT")"
na="$(nul_count "$A")"
nb="$(nul_count "$B")"

# AN EMPTY TREE AND A MATCHING TREE COMPARE EQUAL, so an empty subject REFUSES
# rather than passing. Same instinct as the unchanged-input arm below and as the
# identical-trees arm further down: the ways this tool can be silently useless
# all look like success.
[ "$ni" -gt 0 ] || die "the INPUT estate $INPUT holds no files -- there is nothing for a migration to have done"
[ "$na" -gt 0 ] || die "the CLEAN-run tree $A holds no files -- an empty tree and a matching tree compare equal, so this refuses rather than passes"
[ "$nb" -gt 0 ] || die "the RE-RUN tree $B holds no files -- same reason"

echo "SUBJECT input estate  $INPUT   ($ni files)"
echo "SUBJECT clean-run     $A   ($na files)"
echo "SUBJECT re-run        $B   ($nb files)"
echo

# ONE COMPARISON, TWO CALLERS. There are now two questions of the same shape --
# did the migration change the estate at all, and did the re-run land where the
# clean run did -- and a second inline copy is how two answers to one question
# drift into disagreeing with each other.
CMP_ONLY_A=0
CMP_ONLY_B=0
CMP_DIFFERING=0
CMP_GROWN=0
CMP_SHRUNK=0
CMP_DELTA=0
CMP_REPORT=""
CMP_PATHS=""

tree_delta() {
  local X="$1" Y="$2"
  local only_x only_y both f rc sx sy d

  only_x="$(comm -23 <(cd "$X" && find . -type f | sort) <(cd "$Y" && find . -type f | sort))"
  only_y="$(comm -13 <(cd "$X" && find . -type f | sort) <(cd "$Y" && find . -type f | sort))"
  both="$(comm -12 <(cd "$X" && find . -type f | sort) <(cd "$Y" && find . -type f | sort))"

  CMP_ONLY_A="$(printf '%s' "$only_x" | grep -c . || true)"
  CMP_ONLY_B="$(printf '%s' "$only_y" | grep -c . || true)"
  CMP_DIFFERING=0
  CMP_GROWN=0
  CMP_SHRUNK=0
  CMP_DELTA=0
  CMP_REPORT=""
  CMP_PATHS="$(printf '%s\n%s\n' "$only_x" "$only_y" | grep . || true)"

  while IFS= read -r f; do
    [ -n "$f" ] || continue
    # `cmp -s` RATHER THAN TWO `shasum` INVOCATIONS, and the speed is the lesser
    # of the two reasons.
    #
    # THE REASON THAT IS ABOUT CORRECTNESS: the hash was never read, only
    # compared, and an UNREADABLE file made `shasum` print nothing -- so `hx` and
    # `hy` were both the empty string, compared EQUAL, and the file was counted
    # as UNCHANGED. A silent skip reading as identical. That is cc's own class,
    # which this file refuses for newline paths four screens up, sitting one line
    # away from the refusal that quotes it -- the same "argued to the general
    # form, closed only the instance that prompted it" defect this commit is
    # named for, third instance today. `cmp` separates the three outcomes (0
    # same, 1 differ, 2 cannot read) so unreadable REFUSES instead of passing.
    #
    # AND THE ARM MOST LIKELY TO MEET IT IS THE ONE WHOSE GREEN YOU WOULD MOST
    # WANT TO TRUST (ic). A `kill -9` mid-write is the best generator of a file
    # in a strange state this project has, and their rig exists to make them --
    # so the INTERRUPTED arm, the only arm that produces a green, is exactly
    # where an unreadable file arises. Every run to date was over readable
    # trees, which is luck about the inputs and not a property of the tool.
    #
    # The reason that is about speed: measured on 400 files, two `shasum` runs
    # 12.35s against one `cmp` 4.24s -- 2.9x, because macOS `shasum` is a Perl
    # script and this spawns one interpreter per file per tree. ic hit a
    # five-minute ceiling on the canary once the input arm doubled the file
    # count, and spent minutes reading a working run as a hang.
    cmp -s "$X/$f" "$Y/$f"
    rc=$?
    case "$rc" in
      0) continue ;;
      1) ;;
      *) die "cannot read $f in both trees -- refusing rather than counting an unreadable file as unchanged" ;;
    esac
    CMP_DIFFERING=$((CMP_DIFFERING + 1))
    CMP_PATHS="${CMP_PATHS}
${f}"
    sx="$(wc -c < "$X/$f" | tr -d ' ')"
    sy="$(wc -c < "$Y/$f" | tr -d ' ')"
    d=$((sy - sx))
    CMP_DELTA=$((CMP_DELTA + d))
    if   [ "$d" -gt 0 ]; then CMP_GROWN=$((CMP_GROWN + 1))
    elif [ "$d" -lt 0 ]; then CMP_SHRUNK=$((CMP_SHRUNK + 1)); fi
    CMP_REPORT="${CMP_REPORT}  ${f#./}  ${sx} -> ${sy} (${d})
"
  done <<EOF
$both
EOF
}

cmp_changed_total() { echo $((CMP_ONLY_A + CMP_ONLY_B + CMP_DIFFERING)); }

# ARM 1 -- DID THE MIGRATION DO ANYTHING AT ALL? See the header block. The count
# is printed unconditionally: it is this tool's positive control, and a verdict
# with no measurement behind it cannot be distinguished from a verdict about
# nothing.
tree_delta "$INPUT" "$A"
altered="$(cmp_changed_total)"
migrated_paths="$(printf '%s\n' "$CMP_PATHS" | grep . | sort || true)"
echo "the clean run altered $altered file(s) of the input estate"
echo "  (added $CMP_ONLY_B, removed $CMP_ONLY_A, rewrote $CMP_DIFFERING)"
echo

if [ "$altered" -eq 0 ]; then
  echo "CANNOT MEASURE -- the clean run left the input estate byte-identical." >&2
  echo "  The migrator did nothing, so both output trees are the input and they" >&2
  echo "  compare equal. IDENTICAL here would be a green from a door that never" >&2
  echo "  opened, which is what this arm exists to refuse." >&2
  echo "  Check that the migration door is wired and reachable from a process." >&2
  exit 2
fi

# ARM 2 -- THE VERDICT. Does the re-run land where the clean run did?
tree_delta "$A" "$B"
differing="$CMP_DIFFERING"
grown="$CMP_GROWN"
shrunk="$CMP_SHRUNK"
delta_total="$CMP_DELTA"
n_only_a="$CMP_ONLY_A"
n_only_b="$CMP_ONLY_B"
report="$CMP_REPORT"
diff_paths="$(printf '%s\n' "$CMP_PATHS" | grep . | sort || true)"

if [ "$differing" -eq 0 ] && [ "$n_only_a" -eq 0 ] && [ "$n_only_b" -eq 0 ]; then
  echo "IDENTICAL -- the re-run reached the same end state as the clean run across all $na files."
  exit 0
fi

echo "DIFFERENT -- the re-run did NOT reach the same end state."
echo "  files in clean-run only : $n_only_a"
echo "  files in re-run only    : $n_only_b"
echo "  files differing in both : $differing  (grown $grown, shrunk $shrunk, net ${delta_total} bytes)"
echo
if [ -n "$report" ]; then
  echo "  per-file byte deltas:"
  printf '%s' "$report" | head -40
fi

# ACCRETION IS NAMED SEPARATELY FROM MERE DIFFERENCE, because the two have
# different remedies and a reader who cannot tell them apart will chase the
# wrong one. A re-run that differs arbitrarily is non-determinism. A re-run in
# which every changed file GREW and none shrank is the generator re-reading its
# own output -- the shape ic measured at +350 bytes per run with no fixed point,
# where the "do not edit this file" banner ended up inside thread.json three
# copies deep.
if [ "$differing" -gt 0 ] && [ "$shrunk" -eq 0 ] && [ "$delta_total" -gt 0 ]; then
  echo
  echo "  SHAPE: every differing file GREW and none shrank (+$delta_total bytes)."
  echo "  That is accretion, not non-determinism: the generator is re-reading what it wrote."
fi

# A DIFFERENCE THE MIGRATION CANNOT HAVE CAUSED IS NAMED APART FROM ONE IT CAN,
# because the remedies live in different repositories (ic, 2026-08-18, from a real
# caller trap this tool's own third argument invites). ARM 1 already measured
# exactly which paths the clean migration touched, so any path where the two runs
# disagree and the migration NEVER WROTE is, by construction, not the migrator's
# doing -- it is the harness. The known cause is a per-capture provenance stamp:
# `estate_corpus.sh capture` writes `captured_at` into a CAPTURE file at the tree
# root, so TWO separate captures of ONE pinned revision differ in a file no
# migration touches. The natural reading of "the input estate" is a fresh capture,
# which is why the trap is worth catching rather than warning about.
#
# DERIVED, NOT NAMED -- no CAPTURE, no captured_at, no filename anywhere here. A
# needle keyed to today's provenance record stops discriminating the day it is
# renamed, and this arm has to survive the next stamp nobody has invented yet.
# Reported and not gated: it is still a real difference and still exit 1, but the
# reader is told which half of it the migrator could not have produced. A RED THAT
# SENDS SOMEONE HUNTING IN THE WRONG REPOSITORY COSTS MORE THAN A RED THAT SAYS
# NOTHING.
if [ -n "$diff_paths" ]; then
  untouched="$(comm -23 <(printf '%s\n' "$diff_paths") <(printf '%s\n' "$migrated_paths") | grep . || true)"
  n_untouched="$(printf '%s' "$untouched" | grep -c . || true)"
  if [ "$n_untouched" -gt 0 ]; then
    echo
    echo "  NOT THE MIGRATOR: $n_untouched of the differing path(s) were never touched by the clean run."
    echo "  The two runs disagree on files the migration did not write, so that part is the harness."
    echo "  Usual cause: each arm was captured separately and the capture stamps its own provenance."
    echo "  Capture the estate ONCE and copy it to each arm, so both start from identical bytes."
    printf '%s\n' "$untouched" | head -10 | sed 's/^\./    /'
  fi
fi
exit 1
