#!/bin/bash
# same_end_state_check.sh -- does a re-run over an INTERRUPTED estate reach the
# same end state as a CLEAN run?
#
# This is the gate hv authorised for the cutover. hv ruled the hoist "big bang
# and fix forward", which makes RE-RUNNING the normal recovery path rather than
# an exceptional one -- so the property the migrator must have is not rollback
# but re-runnability, and this is what measures it.
#
# WHY THE VERDICT IS A TREE DIFF AND NOT A CONSERVATION RUN. vc's correction,
# taken, and it is load-bearing rather than a preference. `conservation_check.sh`
# compares an ESTATE against CANON; "same end state as a clean run" compares two
# OUTPUTS. Every conservation predicate is anchored on the estate side, so two
# trees can differ in ways no such predicate reads. That is measured, not
# theoretical: ic's accretion passed reachability, presence, DOUBLED **and prose
# conservation itself**, because prose conservation iterates the ESTATE's
# sections and finds each one intact with generated bytes interleaved between
# them. PROSE GAINED IS INVISIBLE TO A CHECK THAT ONLY ASKS WHETHER WHAT LEFT
# ARRIVED. So the diff is the verdict and conservation is corroboration; the
# other way round, this gate would inherit that blind spot with nothing saying
# so.
#
# WHY IT IS A SIBLING OF conservation_check.sh AND NOT AN ARM OF IT (vc's
# ruling, with vc's test rather than vc's verdict, so the next reader can
# re-derive it): DO THE TWO TOOLS HAVE INPUTS THAT OVERLAP? Theirs takes a
# census and a tree; this takes trees. `--out-of-model` means nothing for a
# tree-to-tree comparison, and a census means nothing for one. There is no
# invocation of either that the other could serve, so folding them would not
# merge two checks -- it would put a second unrelated mode behind one name and
# one exit code, and a reader hitting exit 1 could not tell which question had
# failed without parsing the body. Same shape as provenance_check.sh /
# self_provenance_check.sh.
#
# NEITHER SUBSUMES THE OTHER ON ACCRETION, WHICH IS THE ONE PLACE THEY LOOK
# ALIKE. vc's ADDED-PROSE arm catches a section the canon holds that the estate
# never had -- on a FIRST run, with no second run in existence. This catches
# every-file-grew-and-none-shrank across TWO runs, including growth in files
# with no sections at all. Theirs cannot see this (there is only one tree) and
# this cannot see theirs (both trees are equally wrong).
#
# NO DUPLICATED MECHANISM, CHECKED RATHER THAN ASSERTED, because hv's constraint
# is about duped code and not about file count. Measured against
# conservation_check.sh with comments stripped, so prose about a mechanism is
# not counted as one: section extraction vc 6 / here 0; trim normalisation vc 11
# / here 0; path-to-owning-entity 0 / 0; hashing 2 / 2 -- and the hashing
# overlap is a bare `shasum -a 256` invocation on different subjects (vc hashes
# a trimmed section body, this hashes one relative path in two trees). A call to
# a standard tool with no logic in it cannot drift into two wrong behaviours,
# which is what lib_corpus.sh's precedent exists to prevent. If that judgement
# is wrong the remedy is a lib_, not a copy.
#
# EVERY SUBJECT IS NAMED FIRST AND UNCONDITIONALLY. vc's census had four
# members producing four files indistinguishable by inspection, and a consumer
# compared two unrelated estates and reported a NUMBER instead of refusing.
# Migration outputs are likewise anonymous trees. A verdict that cannot say
# which things it describes is not a verdict.
#
# ---------------------------------------------------------------------------
# THE INPUT ESTATE IS A REQUIRED SUBJECT, AND IT CLOSES A FALSE GREEN THIS FILE
# ARGUED ITS WAY TO AND THEN MISSED (dc, 2026-08-18).
#
# The empty-tree refusal below reasons that "an empty tree and a matching tree
# compare equal, so an empty subject REFUSES rather than passing", and states
# the general form: THE WAYS THIS TOOL CAN BE SILENTLY USELESS BOTH LOOK LIKE
# SUCCESS. That argument was written here, the EMPTY case was closed, and the
# UNCHANGED case was left open -- and the unchanged case is the reachable one,
# because two UNMIGRATED trees are not empty. They are full, and equal.
#
# It was reachable the day this landed and nobody had run it yet. Measured at
# `f5b5918c`: `intent upgrade` is advertised in `--help` and returns `error:
# 'upgrade' is a known command that is not implemented yet` at exit 2, because
# `Facade::upgrade` was uncommitted and the dispatch row unwired. Run the rig
# against that binary and every invocation writes nothing, so both outputs are
# byte-identical to the pristine input and this tool reports IDENTICAL, exit 0.
# A GREEN FROM A DOOR THAT NEVER OPENED -- ic's unfired-fixture trap one level
# up: not a kill landing too early, but a migrator that never ran.
#
# EXIT 2 AND NOT 1, DELIBERATELY. A migrator that changed nothing is a defect,
# but it is not the question THIS tool asks, and exit 1 would assert "the re-run
# did NOT reach the same end state", which is false -- both runs agree perfectly.
# Cannot-measure is the honest code and the same family as the empty arm.
#
# DERIVED, NOT NAMED. The cheap version looks for `thread.json` in the clean
# tree and refuses if there is none. That needle stops discriminating silently
# the day canon is renamed -- the allowlist lesson in a different hat. "Did the
# migration change ANYTHING" needs no knowledge of what canon looks like, and it
# reuses the comparison already here rather than adding a second mechanism.
#
# THE ALTERED COUNT PRINTS ON EVERY RUN, PASS OR FAIL, as this tool's own
# positive control -- self_provenance_check.sh's `27 matched` reasoning, which
# is the better form of the rule. A run reporting a plausible number of altered
# files is evidence the instrument reached its subject; a verdict alone is not.
# ---------------------------------------------------------------------------
#
# ROSTER: manual. It takes three tree arguments, so there is no bare invocation
# for a gate to make -- the same clause as guide_refs_check.sh. The run belongs
# to ic, whose harness kills the process for real (`intent upgrade &`, `kill -9`
# mid-run, `intent upgrade` again -- cc ruled against widening `facade::apply`
# or adding a test seam, because a migration dies when the PROCESS dies, not
# inside a function, and a real SIGKILL can leave a stray `.name.intent-tmp`
# from temp-and-rename that a hand-rolled partial write never would; a re-run
# has to be indifferent to that).
#
# Exit codes follow the family: 0 clean, 1 a finding, 2 cannot measure.

set -uo pipefail

die() { echo "same-end-state: $*" >&2; exit 2; }

# ---------------------------------------------------------------------------
# THE STORE IS REPORTED AS NOT JUDGED BY THIS TOOL, AND THE SUBJECT IS NOT NARROWED
# (dc + ic measured independently, vc ruled the subject, 2026-08-18).
#
# A HEADING THAT OUTLIVES THE CODE BENEATH IT IS THE DEFECT THIS FILE KEEPS
# WRITING ABOUT. This block first said COMPARED BY CONTENT and meant it; when the
# mechanism was withdrawn the heading was the last thing to change, which is
# exactly the shape of `f48ed6e9` -- a claim in the part that travels, corrected
# only in the part that does not.
#
# ic's gate run against a commit came back exit 1 on ONE differing path,
# `intent/.cache/intent.db`, after a real SIGKILL at 293 of 295 writes with all
# 1371 other paths identical. Their control is what mattered: TWO CLEAN RUNS, no
# kill, over the same pinned bytes, differ in that file too. So IDENTICAL was
# unreachable by construction and nothing in the output said so -- the empty-tree
# and unchanged-input family arriving a third time.
#
# THE PROPOSED FIX WAS TO EXCLUDE GITIGNORED PATHS AS "NOT CANON". IT WAS
# DECLINED, AND CHECKING THE GROUNDS AT SOURCE IS WHY. Both cited authorities are
# void in canon: D29's "a path git can never commit can never be canon" is the
# derivation D29 ITSELF VOIDS (`design.md:243` -- "nothing follows from that
# premise any more"), and "`rm intent.db` always safe" is named on D01's
# do-not-cite list verbatim (`design.md:187`). D01 is REVERSED -- hv: "the db is
# the SSOT and it's the FILES that are re-creatable" -- so excluding the store
# would have dropped THE ONE ARTEFACT THE MODEL CALLS TRUTH and left a gate over
# the copies. vc ruled the subject accordingly: not narrowed.
#
# THE DEFECT WAS THE PREDICATE, NOT THE SUBJECT. Byte-identity is the wrong test
# for a container format; two byte-different SQLite files can hold identical
# content exactly as two zips can. So the store is compared through `sqlite3
# .dump`, which asks the question the gate actually means.
#
# AND THE CONTENT DIFFERS TOO, FOR A REASON NO CORRECTNESS CAN FIX: the schema
# defaults `created_at`/`updated_at` to `strftime('%Y-%m-%dT%H:%M:%fZ')`, so 705
# rows carry a stamp of WHEN THE MIGRATION RAN. Measured 117ms apart. That is D42
# working exactly as specified -- the stamp is applied BY the write -- so two runs
# of a PERFECT migrator can never produce the same database, permanently. It is
# not nondeterminism: two operators get the same truth with two accurate
# provenance records.
#
# So machine write-stamps are normalised and everything else is compared exactly.
# THE PATTERN MATCHES THE SHAPE OF A MACHINE STAMP, NEVER A COLUMN NAME, so it
# survives `created_at` being renamed or a third stamped column appearing -- the
# `thread.json` lesson applied one layer down.
#
# A NORMALISATION IS A CLAIM THAT THE NEUTRALISED DIFFERENCE DOES NOT MATTER, SO
# IT IS CANARIED AND COUNTED RATHER THAN TRUSTED. Three controls, all measured
# before this landed: 42 distinct AUTHORED dates (`2026-08-14`, no `T`, no
# milliseconds) pass through untouched; a planted content change (one thread
# title) is still SEEN through the normalisation; and two clean runs still agree
# through it. Without the second of those this would be a device for
# manufacturing greens.
#
# The count is printed on every store comparison, because a normalisation nobody
# can see is an exclusion wearing a comparison's clothes.
# ---------------------------------------------------------------------------
STORE_UNJUDGED=0
STORE_PATHS=""

# DERIVED FROM THE FILE'S OWN BYTES, never from its path. A check keyed to
# `.cache/intent.db` stops discriminating the day the store moves or gains a
# WAL sibling, and it would go red for a reason nobody reads as timestamps.
is_sqlite() { [ "$(head -c 15 "$1" 2>/dev/null)" = "SQLite format 3" ]; }

# THE SIDECARS COUNT TOO, AND THE CANARY IS WHAT FOUND THAT. The first version
# tested only the main database and a real migrated estate then failed on
# `intent.db-shm` -- because a `-shm` does NOT begin with `SQLite format 3`, so
# a magic-byte test alone misses it.
#
# CORRECTION, AND THE MEASUREMENT THAT PRODUCED THE CLAIM IS WHAT CREATED THE
# THING IT REPORTED. This block first said "BOTH clean runs of the pinned canary
# leave `intent.db-wal` AND `intent.db-shm` behind, so this is the real estate's
# shape and not a fixture artefact." THAT IS FALSE and it was committed. A fresh
# capture migrated once and inspected with `ls` alone holds `intent.db` and
# NOTHING ELSE; running a single `sqlite3 SELECT` against it then creates the
# 32KB `-shm` and the 0-byte `-wal`. My earlier trees had been dumped repeatedly
# while I was comparing stores, so THE SIDECARS WERE MY OWN QUERIES. ic caught
# it by noticing their `.cache/` held one file where mine held three -- a
# discrepancy between two nodes measuring one estate, which is the only vantage
# point from which it was visible.
#
# The sidecar handling below STAYS, and its reason changes rather than
# evaporating: any tree an operator or an instrument has opened carries them, so
# a comparator that reddens on `-shm` reddens on having been looked at. D21
# named them as runtime siblings, and runtime is exactly when a reader arrives.
#
# DERIVED FROM SQLite's OWN NAMING CONTRACT, not from this project's paths: a
# file is a store sidecar when stripping the `-wal`/`-shm` suffix SQLite itself
# defines yields a path that passes the magic-byte test. Nothing here mentions
# `.cache` or `intent.db`, so it survives the store moving.
is_store_artefact() {
  local p="$1" base
  is_sqlite "$p" && return 0
  case "$p" in
    *-wal|*-shm)
      base="${p%-wal}"; base="${base%-shm}"
      is_sqlite "$base" && return 0
      ;;
  esac
  return 1
}

# ---------------------------------------------------------------------------
# WHY THIS TOOL DOES NOT SHELL OUT TO `sqlite3`, AND WHY THE FIRST VERSION THAT
# DID WAS WITHDRAWN (ic's objection, cc's canon, and a measurement of my own).
#
# The withdrawn version compared a differing store through `sqlite3 <db> .dump`
# with machine write-stamps normalised, and it worked: on the pinned canary it
# turned the one differing path into a match, canaried three ways.
#
# IT ALSO MADE THE VERDICT DEPEND ON WHICHEVER `sqlite3` THE MACHINE CARRIES,
# AND IT FAILED SILENTLY WHEN THERE WAS NONE -- MEASURED, NOT ARGUED. Same three
# trees, `sqlite3` removed from PATH: exit 1 instead of exit 0, with nothing in
# the output saying the content comparison had not run. TWO MACHINES, ONE
# SUBJECT, OPPOSITE VERDICTS, IN SILENCE. That is the exact class every other
# clause in this file exists to refuse, shipped in the clause meant to fix one.
#
# `design.md:290` closes it from the product side and the reasoning binds an
# instrument even though the guard does not: **`.dump` is a feature of the
# `sqlite3` SHELL, not of the SQLite C API**, and Intent bundles SQLite
# (`rusqlite` with `bundled`) *specifically so it does not depend on whatever
# `sqlite3` binary a user's machine happens to carry*. A rostered gate that
# reintroduces that dependency spends a decision canon paid for.
#
# AND THE NORMALISATION HAD A BLIND SPOT WORTH LOSING (ic). It could not
# distinguish "this field correctly holds a machine stamp" from "this field
# should have held an AUTHORED value and was overwritten by a machine stamp":
# both runs make the identical substitution, both normalise to the same token,
# the dumps agree and the estate's history is gone into the audit trail. Not
# hypothetical -- `migration.md` restores an `st.new` carrying the authored date
# and `Envelope.ts` is millisecond-precision by contract.
#
# SO THE STORE IS REPORTED AS NOT JUDGED BY THIS TOOL. That is NOT an exclusion
# and NOT a silent pass: the path is named, the count is printed, and the verdict
# line carries its own scope. vc ruled the subject is not narrowed (reversed D01:
# the DB is the SSOT and the files are re-creatable), and reporting an artefact
# as unjudged keeps it in the subject while admitting which instrument answers
# for it. The store is compared by a typed test inside `intentsvcs`, which may
# use rusqlite, reads rows rather than a regex over text, and lives in the crate
# that owns it -- ic's, with cc.
#
# THE SCOPE IS IN THE VERDICT LINE AND NOT IN A FOOTNOTE, because a caveat in the
# body does not travel. `f48ed6e9` is this estate's own example: a commit whose
# subject claimed a gate measured passing and whose body correctly said otherwise,
# and the subject is the half a reader a week later has.
# ---------------------------------------------------------------------------

INPUT="${1:-}"; A="${2:-}"; B="${3:-}"
[ -n "$INPUT" ] && [ -n "$A" ] && [ -n "$B" ] ||
  die "usage: same_end_state_check.sh <input-estate> <clean-run-tree> <rerun-tree>"
[ -d "$INPUT" ] || die "no tree at $INPUT -- the INPUT estate is missing"
[ -d "$A" ]     || die "no tree at $A -- the CLEAN-run subject is missing"
[ -d "$B" ]     || die "no tree at $B -- the RE-RUN subject is missing"

# TWO SUBJECTS THAT ARE ONE DIRECTORY REFUSE WITH THEIR OWN MESSAGE (vc, 2026-08-18,
# on the first version of the arm below). THE MIGRATION RUNS IN PLACE, so after a
# clean run there is no pristine input left -- `<input-estate>` has to be a copy
# taken BEFORE the run, not the path handed to the migrator. A rig that passes the
# migrated path as both input and clean-run makes the unchanged-arm compare a tree
# with itself, and it then refuses CORRECTLY FOR THE WRONG REASON: the message says
# "the migrator did nothing" and sends someone to debug a migrator that worked, when
# the defect is in the rig. Same axis as naming ACCRETION apart from non-determinism
# -- two conditions with different remedies must not share one message.
ri="$(cd "$INPUT" && pwd -P)"
ra="$(cd "$A" && pwd -P)"
rb="$(cd "$B" && pwd -P)"
[ "$ri" != "$ra" ] || die "the INPUT estate and the CLEAN-run tree are ONE directory ($ri) -- the migration runs in place, so the input must be a copy taken BEFORE the run"
[ "$ri" != "$rb" ] || die "the INPUT estate and the RE-RUN tree are ONE directory ($ri) -- same reason"
[ "$ra" != "$rb" ] || die "the CLEAN-run and RE-RUN trees are ONE directory ($ra) -- a tree compared with itself is IDENTICAL by construction and says nothing about the re-run"

# A PATH CONTAINING A NEWLINE WOULD SPLIT INTO TWO ENTRIES AND BE MISCOMPARED IN
# SILENCE, so it REFUSES instead (cc, 2026-08-18, from the same class in their own
# comparison: `find | xargs shasum` split on a filename with spaces and reported
# IDENTICAL over 1360 of 1361 files -- the skip was symmetric, so the verdict
# survived by luck rather than by method). A COMPARISON THAT SILENTLY OMITS A FILE
# READS EXACTLY LIKE ONE THAT COVERED EVERYTHING, which is this tool's own false
# green one layer down. Spaces and non-ASCII bytes are handled and canaried -- the
# estate really contains them, vc having measured two Lamplight paths carrying a
# curly quote -- and only a literal newline is refused, because that is the one
# `comm` and `read` cannot survive.
line_count() { find "$1" -type f | wc -l | tr -d ' '; }
nul_count()  { find "$1" -type f -print0 | tr -dc '\0' | wc -c | tr -d ' '; }

for subj in "$INPUT" "$A" "$B"; do
  [ "$(line_count "$subj")" = "$(nul_count "$subj")" ] ||
    die "a path under $subj contains a NEWLINE -- this compares line by line, so it would silently miscompare rather than measure"
done

ni="$(nul_count "$INPUT")"
na="$(nul_count "$A")"
nb="$(nul_count "$B")"

# AN EMPTY TREE AND A MATCHING TREE COMPARE EQUAL, so an empty subject REFUSES
# rather than passing. Same instinct as the unchanged-input arm below and as the
# identical-trees arm further down: the ways this tool can be silently useless
# all look like success.
[ "$ni" -gt 0 ] || die "the INPUT estate $INPUT holds no files -- there is nothing for a migration to have done"
[ "$na" -gt 0 ] || die "the CLEAN-run tree $A holds no files -- an empty tree and a matching tree compare equal, so this refuses rather than passes"
[ "$nb" -gt 0 ] || die "the RE-RUN tree $B holds no files -- same reason"

echo "SUBJECT input estate  $INPUT   ($ni files)"
echo "SUBJECT clean-run     $A   ($na files)"
echo "SUBJECT re-run        $B   ($nb files)"
echo

# ONE COMPARISON, TWO CALLERS. There are now two questions of the same shape --
# did the migration change the estate at all, and did the re-run land where the
# clean run did -- and a second inline copy is how two answers to one question
# drift into disagreeing with each other.
CMP_ONLY_A=0
CMP_ONLY_B=0
CMP_DIFFERING=0
CMP_GROWN=0
CMP_SHRUNK=0
CMP_DELTA=0
CMP_REPORT=""
CMP_PATHS=""

tree_delta() {
  local X="$1" Y="$2"
  local only_x only_y both f rc sx sy d

  only_x="$(comm -23 <(cd "$X" && find . -type f | sort) <(cd "$Y" && find . -type f | sort))"
  only_y="$(comm -13 <(cd "$X" && find . -type f | sort) <(cd "$Y" && find . -type f | sort))"
  both="$(comm -12 <(cd "$X" && find . -type f | sort) <(cd "$Y" && find . -type f | sort))"

  CMP_ONLY_A="$(printf '%s' "$only_x" | grep -c . || true)"
  CMP_ONLY_B="$(printf '%s' "$only_y" | grep -c . || true)"
  CMP_DIFFERING=0
  CMP_GROWN=0
  CMP_SHRUNK=0
  CMP_DELTA=0
  CMP_REPORT=""
  CMP_PATHS="$(printf '%s\n%s\n' "$only_x" "$only_y" | grep . || true)"

  while IFS= read -r f; do
    [ -n "$f" ] || continue
    # `cmp -s` RATHER THAN TWO `shasum` INVOCATIONS, and the speed is the lesser
    # of the two reasons.
    #
    # THE REASON THAT IS ABOUT CORRECTNESS: the hash was never read, only
    # compared, and an UNREADABLE file made `shasum` print nothing -- so `hx` and
    # `hy` were both the empty string, compared EQUAL, and the file was counted
    # as UNCHANGED. A silent skip reading as identical. That is cc's own class,
    # which this file refuses for newline paths four screens up, sitting one line
    # away from the refusal that quotes it -- the same "argued to the general
    # form, closed only the instance that prompted it" defect this commit is
    # named for, third instance today. `cmp` separates the three outcomes (0
    # same, 1 differ, 2 cannot read) so unreadable REFUSES instead of passing.
    #
    # AND THE ARM MOST LIKELY TO MEET IT IS THE ONE WHOSE GREEN YOU WOULD MOST
    # WANT TO TRUST (ic). A `kill -9` mid-write is the best generator of a file
    # in a strange state this project has, and their rig exists to make them --
    # so the INTERRUPTED arm, the only arm that produces a green, is exactly
    # where an unreadable file arises. Every run to date was over readable
    # trees, which is luck about the inputs and not a property of the tool.
    #
    # The reason that is about speed: measured on 400 files, two `shasum` runs
    # 12.35s against one `cmp` 4.24s -- 2.9x, because macOS `shasum` is a Perl
    # script and this spawns one interpreter per file per tree. ic hit a
    # five-minute ceiling on the canary once the input arm doubled the file
    # count, and spent minutes reading a working run as a hang.
    cmp -s "$X/$f" "$Y/$f"
    rc=$?
    case "$rc" in
      0) continue ;;
      1) ;;
      *) die "cannot read $f in both trees -- refusing rather than counting an unreadable file as unchanged" ;;
    esac
    # The bytes differ. For a container format that is not an answer -- see the
    # header block. Named, counted, and neither judged nor dropped.
    if is_store_artefact "$X/$f" && is_store_artefact "$Y/$f"; then
      STORE_UNJUDGED=$((STORE_UNJUDGED + 1))
      STORE_PATHS="${STORE_PATHS}    ${f#./}
"
      continue
    fi
    CMP_DIFFERING=$((CMP_DIFFERING + 1))
    CMP_PATHS="${CMP_PATHS}
${f}"
    sx="$(wc -c < "$X/$f" | tr -d ' ')"
    sy="$(wc -c < "$Y/$f" | tr -d ' ')"
    d=$((sy - sx))
    CMP_DELTA=$((CMP_DELTA + d))
    if   [ "$d" -gt 0 ]; then CMP_GROWN=$((CMP_GROWN + 1))
    elif [ "$d" -lt 0 ]; then CMP_SHRUNK=$((CMP_SHRUNK + 1)); fi
    CMP_REPORT="${CMP_REPORT}  ${f#./}  ${sx} -> ${sy} (${d})
"
  done <<EOF
$both
EOF
}

cmp_changed_total() { echo $((CMP_ONLY_A + CMP_ONLY_B + CMP_DIFFERING)); }

# ARM 1 -- DID THE MIGRATION DO ANYTHING AT ALL? See the header block. The count
# is printed unconditionally: it is this tool's positive control, and a verdict
# with no measurement behind it cannot be distinguished from a verdict about
# nothing.
tree_delta "$INPUT" "$A"
altered="$(cmp_changed_total)"
migrated_paths="$(printf '%s\n' "$CMP_PATHS" | grep . | sort || true)"
echo "the clean run altered $altered file(s) of the input estate"
echo "  (added $CMP_ONLY_B, removed $CMP_ONLY_A, rewrote $CMP_DIFFERING)"
echo

if [ "$altered" -eq 0 ]; then
  echo "CANNOT MEASURE -- the clean run left the input estate byte-identical." >&2
  echo "  The migrator wrote nothing, so both output trees are the input and they" >&2
  echo "  compare equal. IDENTICAL here would be a green from a door that never" >&2
  echo "  opened, which is what this arm exists to refuse." >&2
  echo >&2
  # TWO CAUSES, NAMED, AND NEITHER ASSERTED (ic, 2026-08-18). A BLOCKED migration
  # also writes nothing -- and a door that refuses to convert a LIVE thread is the
  # migrator working exactly as migration.md specifies. The first version of this
  # arm printed "check that the door is wired", which is wrong advice for a
  # correctly-blocking estate: it refuses for the right reason and names the wrong
  # cause, which is vc's catch from the same morning in a different clause of this
  # same file. THIS TOOL SEES TREES AND NEVER EXIT CODES, so it genuinely cannot
  # tell them apart, and inventing a discriminator it does not have would be worse
  # than saying so.
  echo "  TWO CAUSES PRODUCE THIS AND THIS TOOL CANNOT TELL THEM APART:" >&2
  echo "    - the migration door is unwired or unreachable from a process; or" >&2
  echo "    - the migration BLOCKED, which is the door working as specified." >&2
  echo "  The migrator's own exit code separates them. This sees only trees." >&2
  exit 2
fi

# ARM 2 -- THE VERDICT. Does the re-run land where the clean run did?
tree_delta "$A" "$B"
differing="$CMP_DIFFERING"
grown="$CMP_GROWN"
shrunk="$CMP_SHRUNK"
delta_total="$CMP_DELTA"
n_only_a="$CMP_ONLY_A"
n_only_b="$CMP_ONLY_B"
report="$CMP_REPORT"
diff_paths="$(printf '%s\n' "$CMP_PATHS" | grep . | sort || true)"

# THE UNJUDGED STORES ARE NAMED ON EVERY RUN THAT FOUND ONE, PASS OR FAIL, AND
# THE VERDICT LINE CARRIES THE SCOPE. An artefact quietly left out of a
# comparison is an exclusion whatever the header calls it; one that is listed,
# counted and named in the verdict is a stated limit of the instrument.
if [ "$STORE_UNJUDGED" -gt 0 ]; then
  echo "  $STORE_UNJUDGED store(s) differ and are NOT JUDGED BY THIS TOOL:"
  printf '%s' "$STORE_PATHS"
  echo "  A SQLite file is a container: byte-identity is the wrong test, and the"
  echo "  schema stamps each row with WHEN it was written, so two runs of a correct"
  echo "  migrator can never match byte for byte. Comparing content needs the"
  echo "  sqlite3 SHELL, which would make this verdict depend on the machine."
  echo "  The store is compared by a typed test inside intentsvcs."
  echo
fi

# THIS TOOL COMPARES TWO RUNS TO EACH OTHER AND IS SILENT ON WHETHER EITHER IS
# USABLE, AND THAT SENTENCE IS PRINTED WITH EVERY PASS RATHER THAN WRITTEN HERE
# FOR MAINTAINERS.
#
# Paid for on 2026-08-17. This tool returned exit 0 and `IDENTICAL IN FILES --
# 1371 file(s) match` against `252f9ed2`, correctly, over a migrated estate in
# which every verb but `info` refused -- `st list`, `todo`, `export`, `search`,
# `ac list`, `wp list`, `st new` all rc=1 (ic, measured on the kept tree). The
# comparison was right. It was A CORRECT COMPARISON OF TWO CORPSES (ic's
# phrase, and it is the one to keep).
#
# THE DESIGN LESSON IS NOT "ADD A LIVENESS CHECK HERE" -- liveness is a property
# of the SUBJECT, and this tool is handed two trees it did not produce, so the
# probe belongs in the rig that makes them, where ic has put it. The lesson is
# about the VERDICT. This tool's scope line already named files-versus-store,
# and that line worked: ic went hunting the store arm precisely because the
# headline said it was missing. But bytes-versus-liveness was in no sentence at
# all, so nothing pointed at it.
#
# A VERDICT THAT NAMES ITS SCOPE IS ONLY AS GOOD AS ITS ENUMERATION OF
# DIMENSIONS, AND THE DIMENSION NOBODY THOUGHT OF DOES NOT READ AS AN OMISSION
# -- IT READS AS COMPLETENESS. That is strictly worse than a missing caveat,
# because a scope line is a signal to stop looking. So the line below is not
# another caveat in a growing list, which would become noise nobody reads: it is
# the one structural fact that bounds every verdict this tool can ever emit,
# whatever dimensions get enumerated later. Same shape as "internal consistency
# is not correspondence", one level up -- agreement between two runs is
# consistency, and whether the result is a working project is correspondence.
if [ "$differing" -eq 0 ] && [ "$n_only_a" -eq 0 ] && [ "$n_only_b" -eq 0 ]; then
  if [ "$STORE_UNJUDGED" -gt 0 ]; then
    echo "IDENTICAL IN FILES -- $((na - STORE_UNJUDGED)) file(s) match; $STORE_UNJUDGED store(s) NOT judged here (see above)."
  else
    echo "IDENTICAL -- the re-run reached the same end state as the clean run across all $na files."
  fi
  echo "  SCOPE: this compares two RUNS to each other and is SILENT on whether either produced a usable project."
  exit 0
fi

echo "DIFFERENT -- the re-run did NOT reach the same end state."
echo "  files in clean-run only : $n_only_a"
echo "  files in re-run only    : $n_only_b"
echo "  files differing in both : $differing  (grown $grown, shrunk $shrunk, net ${delta_total} bytes)"
echo
if [ -n "$report" ]; then
  echo "  per-file byte deltas:"
  printf '%s' "$report" | head -40
fi

# ACCRETION IS NAMED SEPARATELY FROM MERE DIFFERENCE, because the two have
# different remedies and a reader who cannot tell them apart will chase the
# wrong one. A re-run that differs arbitrarily is non-determinism. A re-run in
# which every changed file GREW and none shrank is the generator re-reading its
# own output -- the shape ic measured at +350 bytes per run with no fixed point,
# where the "do not edit this file" banner ended up inside thread.json three
# copies deep.
if [ "$differing" -gt 0 ] && [ "$shrunk" -eq 0 ] && [ "$delta_total" -gt 0 ]; then
  echo
  echo "  SHAPE: every differing file GREW and none shrank (+$delta_total bytes)."
  echo "  That is accretion, not non-determinism: the generator is re-reading what it wrote."
fi

# A DIFFERENCE THE MIGRATION CANNOT HAVE CAUSED IS NAMED APART FROM ONE IT CAN,
# because the remedies live in different repositories (ic, 2026-08-18, from a real
# caller trap this tool's own third argument invites). ARM 1 already measured
# exactly which paths the clean migration touched, so any path where the two runs
# disagree and the migration NEVER WROTE is, by construction, not the migrator's
# doing -- it is the harness. The known cause is a per-capture provenance stamp:
# `estate_corpus.sh capture` writes `captured_at` into a CAPTURE file at the tree
# root, so TWO separate captures of ONE pinned revision differ in a file no
# migration touches. The natural reading of "the input estate" is a fresh capture,
# which is why the trap is worth catching rather than warning about.
#
# DERIVED, NOT NAMED -- no CAPTURE, no captured_at, no filename anywhere here. A
# needle keyed to today's provenance record stops discriminating the day it is
# renamed, and this arm has to survive the next stamp nobody has invented yet.
# Reported and not gated: it is still a real difference and still exit 1, but the
# reader is told which half of it the migrator could not have produced. A RED THAT
# SENDS SOMEONE HUNTING IN THE WRONG REPOSITORY COSTS MORE THAN A RED THAT SAYS
# NOTHING.
if [ -n "$diff_paths" ]; then
  untouched="$(comm -23 <(printf '%s\n' "$diff_paths") <(printf '%s\n' "$migrated_paths") | grep . || true)"
  n_untouched="$(printf '%s' "$untouched" | grep -c . || true)"
  if [ "$n_untouched" -gt 0 ]; then
    echo
    echo "  NOT THE MIGRATOR: $n_untouched of the differing path(s) were never touched by the clean run."
    echo "  The two runs disagree on files the migration did not write, so that part is the harness."
    echo "  Usual cause: each arm was captured separately and the capture stamps its own provenance."
    echo "  Capture the estate ONCE and copy it to each arm, so both start from identical bytes."
    printf '%s\n' "$untouched" | head -10 | sed 's/^\./    /'
  fi
fi
exit 1
