#!/bin/bash
# same_end_state_check.sh -- does a re-run over an INTERRUPTED estate reach the
# same end state as a CLEAN run?
#
# This is the gate hv authorised for the cutover. hv ruled the hoist "big bang
# and fix forward", which makes RE-RUNNING the normal recovery path rather than
# an exceptional one -- so the property the migrator must have is not rollback
# but re-runnability, and this is what measures it.
#
# WHY THE VERDICT IS A TREE DIFF AND NOT A CONSERVATION RUN. vc's correction,
# taken, and it is load-bearing rather than a preference. `conservation_check.sh`
# compares an ESTATE against CANON; "same end state as a clean run" compares two
# OUTPUTS. Every conservation predicate is anchored on the estate side, so two
# trees can differ in ways no such predicate reads. That is measured, not
# theoretical: ic's accretion passed reachability, presence, DOUBLED **and prose
# conservation itself**, because prose conservation iterates the ESTATE's
# sections and finds each one intact with generated bytes interleaved between
# them. PROSE GAINED IS INVISIBLE TO A CHECK THAT ONLY ASKS WHETHER WHAT LEFT
# ARRIVED. So the diff is the verdict and conservation is corroboration; the
# other way round, this gate would inherit that blind spot with nothing saying
# so.
#
# WHY IT IS A SIBLING OF conservation_check.sh AND NOT AN ARM OF IT (vc's
# ruling, with vc's test rather than vc's verdict, so the next reader can
# re-derive it): DO THE TWO TOOLS HAVE INPUTS THAT OVERLAP? Theirs takes a
# census and a tree; this takes two trees. `--out-of-model` means nothing for a
# two-tree comparison, and a census means nothing for one. There is no
# invocation of either that the other could serve, so folding them would not
# merge two checks -- it would put a second unrelated mode behind one name and
# one exit code, and a reader hitting exit 1 could not tell which question had
# failed without parsing the body. Same shape as provenance_check.sh /
# self_provenance_check.sh.
#
# NEITHER SUBSUMES THE OTHER ON ACCRETION, WHICH IS THE ONE PLACE THEY LOOK
# ALIKE. vc's ADDED-PROSE arm catches a section the canon holds that the estate
# never had -- on a FIRST run, with no second run in existence. This catches
# every-file-grew-and-none-shrank across TWO runs, including growth in files
# with no sections at all. Theirs cannot see this (there is only one tree) and
# this cannot see theirs (both trees are equally wrong).
#
# NO DUPLICATED MECHANISM, CHECKED RATHER THAN ASSERTED, because hv's constraint
# is about duped code and not about file count. Measured against
# conservation_check.sh with comments stripped, so prose about a mechanism is
# not counted as one: section extraction vc 6 / here 0; trim normalisation vc 11
# / here 0; path-to-owning-entity 0 / 0; hashing 2 / 2 -- and the hashing
# overlap is a bare `shasum -a 256` invocation on different subjects (vc hashes
# a trimmed section body, this hashes one relative path in two trees). A call to
# a standard tool with no logic in it cannot drift into two wrong behaviours,
# which is what lib_corpus.sh's precedent exists to prevent. If that judgement
# is wrong the remedy is a lib_, not a copy.
#
# BOTH SUBJECTS ARE NAMED FIRST AND UNCONDITIONALLY. vc's census had four
# members producing four files indistinguishable by inspection, and a consumer
# compared two unrelated estates and reported a NUMBER instead of refusing. Two
# migration outputs are likewise two anonymous trees. A verdict that cannot say
# which two things it describes is not a verdict.
#
# ROSTER: manual. It takes two tree arguments, so there is no bare invocation
# for a gate to make -- the same clause as guide_refs_check.sh. The run belongs
# to ic, whose harness kills the process for real (`intent upgrade &`, `kill -9`
# mid-run, `intent upgrade` again -- cc ruled against widening `facade::apply`
# or adding a test seam, because a migration dies when the PROCESS dies, not
# inside a function, and a real SIGKILL can leave a stray `.name.intent-tmp`
# from temp-and-rename that a hand-rolled partial write never would; a re-run
# has to be indifferent to that).
#
# Exit codes follow the family: 0 clean, 1 a finding, 2 cannot measure.

set -uo pipefail

die() { echo "same-end-state: $*" >&2; exit 2; }

A="${1:-}"; B="${2:-}"
[ -n "$A" ] && [ -n "$B" ] || die "usage: same_end_state_check.sh <clean-run-tree> <rerun-tree>"
[ -d "$A" ] || die "no tree at $A -- the CLEAN-run subject is missing"
[ -d "$B" ] || die "no tree at $B -- the RE-RUN subject is missing"

na="$(find "$A" -type f | wc -l | tr -d ' ')"
nb="$(find "$B" -type f | wc -l | tr -d ' ')"

# AN EMPTY TREE AND A MATCHING TREE COMPARE EQUAL, so an empty subject REFUSES
# rather than passing. This is the same instinct as the identical-trees arm
# below: the ways this tool can be silently useless both look like success.
[ "$na" -gt 0 ] || die "the CLEAN-run tree $A holds no files -- an empty tree and a matching tree compare equal, so this refuses rather than passes"
[ "$nb" -gt 0 ] || die "the RE-RUN tree $B holds no files -- same reason"

echo "SUBJECT clean-run   $A   ($na files)"
echo "SUBJECT re-run      $B   ($nb files)"
echo

only_a="$(comm -23 <(cd "$A" && find . -type f | sort) <(cd "$B" && find . -type f | sort))"
only_b="$(comm -13 <(cd "$A" && find . -type f | sort) <(cd "$B" && find . -type f | sort))"
both="$(comm -12 <(cd "$A" && find . -type f | sort) <(cd "$B" && find . -type f | sort))"

differing=0
grown=0
shrunk=0
delta_total=0
report=""

while IFS= read -r f; do
  [ -n "$f" ] || continue
  ha="$(shasum -a 256 "$A/$f" | awk '{print $1}')"
  hb="$(shasum -a 256 "$B/$f" | awk '{print $1}')"
  [ "$ha" = "$hb" ] && continue
  differing=$((differing + 1))
  sa="$(wc -c < "$A/$f" | tr -d ' ')"
  sb="$(wc -c < "$B/$f" | tr -d ' ')"
  d=$((sb - sa))
  delta_total=$((delta_total + d))
  if   [ "$d" -gt 0 ]; then grown=$((grown + 1))
  elif [ "$d" -lt 0 ]; then shrunk=$((shrunk + 1)); fi
  report="${report}  ${f#./}  ${sa} -> ${sb} (${d})
"
done <<EOF
$both
EOF

n_only_a="$(printf '%s' "$only_a" | grep -c . || true)"
n_only_b="$(printf '%s' "$only_b" | grep -c . || true)"

if [ "$differing" -eq 0 ] && [ "$n_only_a" -eq 0 ] && [ "$n_only_b" -eq 0 ]; then
  echo "IDENTICAL -- the re-run reached the same end state as the clean run across all $na files."
  exit 0
fi

echo "DIFFERENT -- the re-run did NOT reach the same end state."
echo "  files in clean-run only : $n_only_a"
echo "  files in re-run only    : $n_only_b"
echo "  files differing in both : $differing  (grown $grown, shrunk $shrunk, net ${delta_total} bytes)"
echo
if [ -n "$report" ]; then
  echo "  per-file byte deltas:"
  printf '%s' "$report" | head -40
fi

# ACCRETION IS NAMED SEPARATELY FROM MERE DIFFERENCE, because the two have
# different remedies and a reader who cannot tell them apart will chase the
# wrong one. A re-run that differs arbitrarily is non-determinism. A re-run in
# which every changed file GREW and none shrank is the generator re-reading its
# own output -- the shape ic measured at +350 bytes per run with no fixed point,
# where the "do not edit this file" banner ended up inside thread.json three
# copies deep.
if [ "$differing" -gt 0 ] && [ "$shrunk" -eq 0 ] && [ "$delta_total" -gt 0 ]; then
  echo
  echo "  SHAPE: every differing file GREW and none shrank (+$delta_total bytes)."
  echo "  That is accretion, not non-determinism: the generator is re-reading what it wrote."
fi
exit 1
