//! **EACH STALE RENDER NAMES THE VERB THAT CLEARS IT, AND `doctor -v` LISTS A
//! DIRECTORY'S RUN OF THEM ON ONE LINE.**
//!
//! The advisory named `intent sync --to-disk` for every view an older Intent
//! rendered. That verb re-renders a view `.intentfiles` realises and leaves an
//! unrealised one exactly as it found it -- the 3.2.1 cut's 62 closed-issue
//! views stood through it -- and `intent sync --apply` is what clears those,
//! by removing them. And hv's first read of the advisory was 62 near-identical
//! lines, so a directory whose members say the same thing prints once, naming
//! every file.
//!
//! **THE ASSERTION IS THE LOOP.** The command is read out of the group's own
//! line and RUN, and doctor is asked again.

use std::path::Path;

fn intent(root: &Path, args: &[&str]) -> (bool, String) {
  let out = crate::common::intent()
    .args(args)
    .current_dir(root)
    .stdin(testkit::lifeline_for(args))
    .output()
    .unwrap_or_else(|e| panic!("could not run `intent {args:?}`: {e}"));
  (
    out.status.success(),
    String::from_utf8_lossy(&out.stdout).into_owned() + &String::from_utf8_lossy(&out.stderr),
  )
}

fn step(root: &Path, args: &[&str]) {
  let (ok, out) = intent(root, args);
  assert!(ok, "`intent {}` failed: {out}", args.join(" "));
}

/// Rewrite each issue view's footer to name an older Intent.
fn age_the_issue_views(root: &Path) -> Vec<String> {
  let dir = root.join("intent/issues");
  let mut names = Vec::new();
  for entry in std::fs::read_dir(&dir).expect("the issue views") {
    let path = entry.expect("an entry").path();
    if path.extension().is_some_and(|e| e == "md") {
      let text = std::fs::read_to_string(&path).expect("a view");
      let at =
        text.rfind("_Generated by Intent v").expect("a footer") + "_Generated by Intent v".len();
      let end = at + text[at..].find(' ').expect("the version ends");
      std::fs::write(&path, format!("{}2{}", &text[..at], &text[end..])).expect("aged");
      names.push(path.file_name().unwrap().to_string_lossy().into_owned());
    }
  }
  names.sort();
  names
}

/// The one `doctor -v` line that lists the issue views, and the command in it.
fn the_issue_line(root: &Path) -> (String, String) {
  let (_, out) = intent(root, &["doctor", "-v"]);
  let line = out
    .lines()
    .find(|l| l.trim_start().starts_with("intent/issues/ -- "))
    .unwrap_or_else(|| panic!("no grouped line for intent/issues/:\n{out}"))
    .to_string();
  let command = line
    .split('`')
    .find(|span| span.starts_with("intent sync"))
    .unwrap_or_else(|| panic!("the line names no verb: {line}"))
    .to_string();
  (line, command)
}

fn three_issues(root: &Path) {
  step(root, &["init", "probe"]);
  for title in ["the first", "the second", "the third"] {
    step(root, &["issues", "add", title]);
  }
  step(root, &["sync", "--apply", "--yes"]);
}

#[test]
fn realised_stale_views_are_one_line_naming_the_verb_that_re_renders_them() {
  let dir = tempfile::tempdir().expect("tempdir");
  let root = dir.path();
  three_issues(root);
  let names = age_the_issue_views(root);
  assert_eq!(names.len(), 3, "three realised issue views: {names:?}");

  let (line, command) = the_issue_line(root);
  assert!(
    line.contains("3 views"),
    "the group counts its members: {line}"
  );
  assert!(
    line.ends_with(&names.join(", ")),
    "every member is named: {line}"
  );
  assert_eq!(command, "intent sync --to-disk");

  let args: Vec<&str> = command.split_whitespace().skip(1).collect();
  step(root, &args);
  let (_, after) = intent(root, &["doctor", "-v"]);
  assert!(
    !after.contains("stale-render"),
    "the named verb cleared them:\n{after}"
  );
}

#[test]
fn unrealised_stale_views_name_the_verb_that_removes_them() {
  let dir = tempfile::tempdir().expect("tempdir");
  let root = dir.path();
  three_issues(root);
  for number in ["0001", "0002", "0003"] {
    step(root, &["issues", "close", number]);
  }
  let names = age_the_issue_views(root);
  assert_eq!(
    names.len(),
    3,
    "the closed issues' views are still on disk: {names:?}"
  );

  let (line, command) = the_issue_line(root);
  assert!(line.contains("not realised by `.intentfiles`"), "{line}");
  assert_eq!(command, "intent sync --apply");

  step(root, &["sync", "--apply", "--yes"]);
  let (_, after) = intent(root, &["doctor", "-v"]);
  assert!(
    !after.contains("stale-render"),
    "the named verb cleared them:\n{after}"
  );
  let (_, shown) = intent(root, &["issues", "show", "0001"]);
  assert!(
    shown.contains("the first"),
    "the store keeps the record:\n{shown}"
  );
}
