//! AT-07.5 / ST0056 AC-07.5: **`intent agents sync` preserves v2's STRUCTURAL
//! CONTRACT, and byte-parity against v2 is refused as the mechanism.**
//!
//! # Why this file asserts properties and not bytes
//!
//! The criterion used to read *matches v2 for a corpus project, modulo ratified
//! deviations*. Driven end to end -- one tree, v2 `agents sync` captured, then
//! `intent upgrade`, then v3 `agents sync` -- that produced eleven deviation
//! classes, and **two facts that make byte-equality unsatisfiable by
//! construction rather than merely difficult**:
//!
//! - **v2's footer stamps a DATE**, so v2's own output differs from itself
//!   across days. An assertion of byte-equality against it would be asserting
//!   staleness.
//! - **v2 renders the DIRECTORY name where the config disagrees** -- `par` for a
//!   project whose config says `parity`. Byte-equality would score v3's
//!   correctness as a failure and enshrine a v2 bug as the contract.
//!
//! So the row was rewritten on AC-11.1's precedent (a row naming a mechanism
//! that made it unsatisfiable), and what is asserted here is the contract:
//! **every section present and non-empty, the name from config, the footer
//! stable.** The permitted divergences are the ratified list in
//! `intent/st/ST0056/parity.md`, `agents sync deviations -- ratified
//! 2026-08-28`.
//!
//! # Testing the list rather than the bytes is the point
//!
//! The ratification is vc's, on this measurement, recorded for hv's review. **If
//! hv reverses a class, the list moves and this test follows it.** A byte
//! fixture would have to be regenerated by hand and would silently re-freeze
//! whatever v3 did on the day it was captured.
//!
//! # The bare-heading arm is (k), and (k) is a DEFECT rather than a deviation
//!
//! Ten of the eleven classes are ratified. The eleventh is not: v3 emitted
//! `### Test commands` followed by nothing at all where v2 emitted `_No
//! automated tests configured yet._`. **An empty section reads as broken
//! output**, and it is not a language-detection artefact -- driven with
//! `languages: []`, so both binaries saw the same empty set and the difference
//! is the template.
//!
//! **The arm asserts the PROPERTY, never a roster of sections.** "No heading is
//! followed by another heading" covers a section added tomorrow by somebody
//! thinking about something else, which a hand-kept list of required sections
//! does not -- the argument `generated_views_are_not_formatted.rs` makes for
//! asking the generator for its own output set.

use std::path::Path;
use std::process::Command;

fn run(cwd: &Path, args: &[&str]) -> (String, i32) {
  let out = Command::new(env!("CARGO_BIN_EXE_intent"))
    .args(args)
    .current_dir(cwd)
    .env("HOME", testkit::fixture_home())
    .output()
    .expect("the intent binary runs");
  let mut text = String::from_utf8_lossy(&out.stdout).into_owned();
  text.push_str(&String::from_utf8_lossy(&out.stderr));
  (text, out.status.code().unwrap_or(-1))
}

/// A corpus project with `AGENTS.md` synced.
///
/// **The project NAME is deliberately not the directory name.** That is the
/// only arrangement in which deviation (f) can be observed at all: a fixture
/// whose config and directory agree passes the name arm for both the right and
/// the wrong reason.
fn synced() -> (tempfile::TempDir, String) {
  let dir = tempfile::tempdir().expect("tempdir");
  let root = dir.path();
  let (out, rc) = run(root, &["init", PROJECT_NAME]);
  assert_eq!(rc, 0, "init a corpus project: {out}");
  let (out, rc) = run(root, &["st", "new", "a thread"]);
  assert_eq!(rc, 0, "create a thread: {out}");
  let (out, rc) = run(root, &["agents", "sync"]);
  assert_eq!(rc, 0, "agents sync: {out}");
  let text = std::fs::read_to_string(root.join("AGENTS.md")).expect("read AGENTS.md");
  (dir, text)
}

const PROJECT_NAME: &str = "corpusproj";

/// Every heading in `text`, paired with whether it is SATISFIED -- carrying
/// either prose of its own or a subsection.
///
/// **THE SUBSECTION CLAUSE IS NOT A LOOSENING, IT IS THE DIFFERENCE BETWEEN
/// BROKEN OUTPUT AND ORDINARY MARKDOWN.** The first version of this scan asked
/// only for prose before the next heading of ANY level, and it reported `##
/// Development Environment` and `## Build and Test Commands` -- parents whose
/// next line is their own first subsection, which is how documents are shaped.
/// Left that way the test would have demanded filler under every parent heading
/// in order to go green, which is a worse document than the one it started
/// from.
///
/// A heading is unsatisfied only when the next heading is at the SAME or a
/// SHALLOWER level and nothing but blank lines sits between: a leaf with
/// nothing in it.
fn headings_with_content(text: &str) -> Vec<(String, bool)> {
  let level = |l: &str| l.len() - l.trim_start_matches('#').len();
  let lines: Vec<&str> = text.lines().collect();
  let is_heading = |l: &str| l.starts_with('#');
  let mut out = Vec::new();
  for (i, line) in lines.iter().enumerate() {
    if !is_heading(line) {
      continue;
    }
    let mut satisfied = false;
    for next in &lines[i + 1..] {
      if is_heading(next) {
        // A deeper heading is this section's content; a same-or-shallower one
        // means this section ended with nothing in it.
        satisfied = level(next) > level(line);
        break;
      }
      if !next.trim().is_empty() {
        satisfied = true;
        break;
      }
    }
    out.push(((*line).to_string(), satisfied));
  }
  out
}

#[test]
fn no_section_is_a_bare_heading() {
  // (k). A section with nothing under it reads as broken output rather than as
  // "none configured", which is what v2 said in the same place.
  let (_dir, text) = synced();
  let empty: Vec<String> = headings_with_content(&text)
    .into_iter()
    .filter(|(_, has)| !has)
    .map(|(h, _)| h)
    .collect();
  assert!(
    empty.is_empty(),
    "these sections render as a bare heading with nothing beneath them, which reads as broken \
     output -- an empty section owes a placeholder line: {empty:?}\n\n{text}"
  );
}

#[test]
fn the_bare_heading_scan_can_actually_find_one() {
  // THE POSITIVE CONTROL FOR THE SCANNER ITSELF. A walk that never reports an
  // empty section agrees with every document ever written, and agrees silently
  // -- so the arm above would pass on a broken template and on a broken walk
  // identically.
  // TWO-SIDED ON PURPOSE. The planted document carries an empty leaf that MUST
  // be reported, a parent whose only content is a subsection that must NOT be
  // (the false positive the first version of this scan actually produced), and
  // a trailing empty leaf at the end of input.
  let planted =
    "# Title\n\ncontent\n\n## Parent\n\n### Child\n\nprose\n\n## Empty One\n\n## Last\n";
  let found = headings_with_content(planted);
  let flagged: Vec<&str> = found
    .iter()
    .filter(|(_, has)| !has)
    .map(|(h, _)| h.as_str())
    .collect();
  assert_eq!(
    flagged,
    vec!["## Empty One", "## Last"],
    "the scan must find a planted empty leaf AND leave a parent-with-subsection alone -- if it \
     finds nothing its silence on the real document means nothing, and if it flags `## Parent` \
     it will demand filler under every heading: {found:?}"
  );
}

#[test]
fn no_declared_language_leaves_a_section_bare() {
  // **THE DEFECT IS WIDER THAN THE CASE IT WAS FOUND IN, AND THIS ARM IS WHY
  // THE FIX IS NOT IN THE TEMPLATE.** (k) was measured on `languages: []`, but
  // the template carries blocks for a SUBSET: `### Building` has no `shell`
  // arm, and neither section has `author`, `content` or `lua`. Measured before
  // the fix: `[shell]` left `### Building` bare and `[author]` left both bare
  // -- 4 of the 7 packs, none of them the empty case that `[[#nolang]]` covers.
  //
  // **THE ROSTER IS ASKED OF THE TOOL, never kept here.** A hand list is one
  // somebody must extend on the day they add a language pack, which is the day
  // they are thinking about something else.
  let dir = tempfile::tempdir().expect("tempdir");
  let (listed, rc) = run(dir.path(), &["lang", "list"]);
  assert_eq!(rc, 0, "read the language roster from the tool: {listed}");
  let languages: Vec<String> = listed
    .lines()
    .map(str::trim)
    .filter(|l| !l.is_empty() && !l.ends_with(':') && !l.contains(' '))
    .map(str::to_string)
    .collect();
  // The guard is not a count. It names the two packs MEASURED BARE before the
  // fix -- `[shell]` left `### Building` empty and `[author]` left both -- so a
  // parse that silently dropped them would be caught here rather than turning
  // this loop into an expensive way to iterate over nothing.
  for measured in ["shell", "author"] {
    assert!(
      languages.iter().any(|l| l == measured),
      "the roster parse lost `{measured}`, which is one of the packs this arm exists for: \
       parsed {languages:?} from:\n{listed}"
    );
  }

  for language in &languages {
    let project = tempfile::tempdir().expect("tempdir");
    let root = project.path();
    let (out, rc) = run(root, &["init", "langprobe"]);
    assert_eq!(rc, 0, "init for {language}: {out}");

    let config = root.join("intent/.config/config.json");
    let text = std::fs::read_to_string(&config).expect("read config");
    let mut value: serde_json::Value = serde_json::from_str(&text).expect("config is json");
    value["languages"] = serde_json::json!([language]);
    std::fs::write(&config, value.to_string()).expect("write config");

    let (out, rc) = run(root, &["agents", "sync"]);
    assert_eq!(rc, 0, "agents sync for {language}: {out}");
    let rendered = std::fs::read_to_string(root.join("AGENTS.md")).expect("read AGENTS.md");
    let empty: Vec<String> = headings_with_content(&rendered)
      .into_iter()
      .filter(|(_, has)| !has)
      .map(|(h, _)| h)
      .collect();
    assert!(
      empty.is_empty(),
      "a project declaring only `{language}` renders bare heading(s) {empty:?} -- the template \
       has no block for that language in those sections, which is exactly why the placeholder \
       cannot be per-language template content"
    );
  }
}

#[test]
fn the_project_name_renders_from_config_and_not_from_the_directory() {
  // (f). v2 rendered the directory; v3 renders the config, and the fixture is
  // built so the two cannot be confused.
  let (dir, text) = synced();
  let dirname = dir
    .path()
    .file_name()
    .expect("the tempdir has a name")
    .to_string_lossy()
    .into_owned();
  assert_ne!(
    dirname, PROJECT_NAME,
    "the fixture must not let the directory and the configured name agree, or this arm passes \
     for either reason"
  );
  assert!(
    text.contains(PROJECT_NAME),
    "the configured project name is absent from the rendered file: {text}"
  );
  assert!(
    !text.contains(&dirname),
    "the directory name reached the output -- this is the v2 bug that byte-parity would have \
     enshrined: {text}"
  );
}

#[test]
fn the_footer_is_stable_across_runs() {
  // (e). v2 stamped the date it generated, so its output differed from itself
  // across days. A generated file that differs from itself is AC-03.17's churn
  // loop with a clock in it, and D42 says the same thing from the other side.
  let (dir, first) = synced();
  let (out, rc) = run(dir.path(), &["agents", "sync"]);
  assert_eq!(rc, 0, "the second sync: {out}");
  let second = std::fs::read_to_string(dir.path().join("AGENTS.md")).expect("re-read AGENTS.md");
  assert_eq!(
    first, second,
    "two syncs of an unchanged project produced different bytes, so something in the render is \
     reading the world rather than the model"
  );
}

// ---------------------------------------------------------------------------
// `agents init` and `agents validate` -- ST0058 AC-00.3
// ---------------------------------------------------------------------------

/// A corpus project with NO `AGENTS.md` yet, which `synced()` cannot give.
fn unsynced() -> tempfile::TempDir {
  let dir = tempfile::tempdir().expect("tempdir");
  let (out, rc) = run(dir.path(), &["init", PROJECT_NAME]);
  assert_eq!(rc, 0, "init a corpus project: {out}");
  dir
}

/// **THE HALF-WIRED FAMILY WAS WORSE THAN AN ABSENT ONE.** `agents sync` and
/// `agents generate` answered while `init` and `validate` returned `is a known
/// command that is not implemented yet`, so a reader who found two of four verbs
/// behaving reasonably concluded the family worked. Both are mandated in
/// `usage-rules.md`, which ships to every project `intent init` touches.
///
/// The exits are the REGISTER's, not invented here: `0 when created`, `1 when
/// already exists`.
#[test]
fn agents_init_creates_and_then_refuses_rather_than_overwriting() {
  let dir = unsynced();
  let root = dir.path();
  let path = root.join("AGENTS.md");
  assert!(!path.exists(), "the fixture must start without one");

  let (out, rc) = run(root, &["agents", "init"]);
  assert_eq!(rc, 0, "init creates at rc=0: {out}");
  assert!(path.exists(), "init must actually write the file: {out}");

  // **THE REFUSAL MUST LEAVE THE FILE ALONE, and that is the arm worth having.**
  // A verb that refuses and still writes is the failure this contract exists to
  // prevent, and the exit code alone cannot see it -- so the bytes are compared
  // across the refusal rather than the message being trusted.
  std::fs::write(&path, "EDITED BY HAND\n").expect("plant an edit");
  let (out, rc) = run(root, &["agents", "init"]);
  assert_eq!(rc, 1, "a second init refuses at rc=1: {out}");
  assert_eq!(
    std::fs::read_to_string(&path).expect("read back"),
    "EDITED BY HAND\n",
    "the refusal discarded a file it did not write: {out}"
  );
  assert!(
    out.contains("agents sync"),
    "the refusal must name the verb that DOES rewrite it, or the operator's \
     only route is to delete the file: {out}"
  );
}

/// `0 when valid`, `1 when findings` -- the register's exits again.
///
/// **THE SECTION SET IS A FLOOR AND NOT A MIRROR OF THE TEMPLATE**, which is
/// why this asserts four named sections where `no_section_is_a_bare_heading`
/// above deliberately asserts a property instead. Those two arms answer
/// different questions: that one asks whether the GENERATOR produced a sane
/// document, this one asks whether a file on disk still meets a minimum. Deriving
/// this set from the template would turn well-formedness into currency and make
/// every project whose file predates a template change start reporting findings
/// -- and `sync` is the verb that answers currency.
#[test]
fn agents_validate_separates_absent_from_symlinked_from_well_formed() {
  let dir = unsynced();
  let root = dir.path();

  let (out, rc) = run(root, &["agents", "validate"]);
  assert_eq!(rc, 1, "absent is a finding: {out}");
  assert!(out.contains("not found"), "and it says which: {out}");

  let (out, rc) = run(root, &["agents", "init"]);
  assert_eq!(rc, 0, "init: {out}");
  let (out, rc) = run(root, &["agents", "validate"]);
  assert_eq!(rc, 0, "a freshly generated file validates: {out}");
  for section in [
    "Project Overview",
    "Development Environment",
    "Build and Test Commands",
    "Code Style",
  ] {
    assert!(
      out.contains(&format!("ok: has section: {section}")),
      "the floor section `{section}` must be reported present, or this arm is \
       passing without looking: {out}"
    );
  }

  // **A SYMLINK WARNS AND DOES NOT FAIL, carried from v2 deliberately.** Legacy
  // canon put `AGENTS.md` at the root as a link to `intent/llm/AGENTS.md`, and a
  // project in that shape is out of date rather than broken -- failing it would
  // make the remedy (`sync`) unreachable behind a red gate in exactly the
  // projects that need it.
  let path = root.join("AGENTS.md");
  std::fs::remove_file(&path).expect("remove the real file");
  std::fs::create_dir_all(root.join("intent/llm")).expect("legacy dir");
  std::fs::write(root.join("intent/llm/AGENTS.md"), "# legacy\n").expect("legacy file");
  std::os::unix::fs::symlink("intent/llm/AGENTS.md", &path).expect("symlink");
  let (out, rc) = run(root, &["agents", "validate"]);
  assert_eq!(rc, 0, "a symlink is a warning, never a failure: {out}");
  assert!(out.contains("symlink"), "and it names the shape: {out}");
}
