//! ST0069 **AT-01.1** -- covering **AC-01.1**: an open issue declared as
//! `ISSUE:<NNNN>` realises to `intent/issues/<NNNN>.md`, a generated view
//! rendered from the store, byte-identical on two renders of the same store,
//! and reported by `intent doctor` as view skew when it is hand-edited.
//!
//! **DRIVEN THROUGH THE BINARY, BECAUSE THE CRITERION IS ABOUT WHAT AN ESTATE
//! LOOKS LIKE AFTER A COMMAND.** A facade-level test can render the view twice
//! and compare, which is the easy half; it cannot tell you that `organize`
//! puts the file where the manifest says, nor that `doctor` -- a different
//! entry point reading a different code path -- notices an edit to it.
//!
//! **THE DISCRIMINATING CASE FOR SKEW IS AN EDITED BODY, NOT AN EDITED
//! FRONTMATTER FIELD**, and the criterion names it for a reason. Frontmatter is
//! rendered from typed record fields, so a test that edits `status:` is really
//! asking whether the renderer round-trips an enum. The body is the field that
//! is carried verbatim and never parsed, so an edit there is the case where a
//! renderer could plausibly reproduce the edit rather than overwrite it -- and
//! the one where a silent overwrite would destroy authored prose.

use std::process::{Command, Output};

fn intent(dir: &std::path::Path, args: &[&str]) -> Output {
  Command::new(env!("CARGO_BIN_EXE_intent"))
    .args(args)
    .current_dir(dir)
    .stdin(std::process::Stdio::null())
    .output()
    .expect("run the v3 binary")
}

fn said(out: &Output) -> String {
  format!(
    "{}{}",
    String::from_utf8_lossy(&out.stdout),
    String::from_utf8_lossy(&out.stderr)
  )
}

/// A project with one open issue and nothing else.
///
/// **`issues add` writes the STORE and does not realise**, exactly as `st new`
/// does not -- so a test that needs the file on disk has to ask for it. That is
/// the same laziness threads already have and is not a gap this criterion
/// closes.
fn project_with_an_issue() -> tempfile::TempDir {
  let dir = tempfile::tempdir().expect("tempdir");
  let root = dir.path();
  assert!(
    intent(root, &["init", "Fixture"]).status.success(),
    "the fixture must initialise"
  );
  let out = intent(root, &["issues", "add", "A defect worth a file"]);
  assert!(
    out.status.success(),
    "issues add must succeed: {}",
    said(&out)
  );
  dir
}

fn issue_view(root: &std::path::Path) -> std::path::PathBuf {
  root.join("intent/issues/0001.md")
}

// ---------------------------------------------------------------------------
// AC-01.1 -- THE REALISED FORM EXISTS AND IS A FUNCTION OF THE STORE
// ---------------------------------------------------------------------------

#[test]
fn an_open_issue_realises_to_a_generated_view_under_intent_issues() {
  let dir = project_with_an_issue();
  let root = dir.path();

  let out = intent(root, &["organize", "--apply"]);
  assert!(out.status.success(), "organize --apply: {}", said(&out));

  let view = issue_view(root);
  assert!(
    view.is_file(),
    "an open issue must realise to intent/issues/0001.md; the estate holds:\n{}",
    said(&intent(root, &["organize"]))
  );

  let text = std::fs::read_to_string(&view).expect("read the realised view");
  assert!(
    text.contains("A defect worth a file"),
    "the view must carry the record's title, got:\n{text}"
  );
  assert!(
    text.contains("Do not edit this file"),
    "the view must carry the generated footer every other view carries, got:\n{text}"
  );
}

#[test]
fn two_renders_of_one_store_produce_the_same_bytes() {
  let dir = project_with_an_issue();
  let root = dir.path();
  assert!(intent(root, &["organize", "--apply"]).status.success());

  let view = issue_view(root);
  let first = std::fs::read(&view).expect("first render");

  // Remove it and realise again from the same store: a second render of
  // unchanged canon must reproduce the bytes exactly. **Deleting rather than
  // re-applying over the top is deliberate** -- an unchanged-file skip in the
  // write set would make a re-apply pass without the renderer running at all,
  // so the assertion would hold on a renderer that had become non-deterministic.
  std::fs::remove_file(&view).expect("remove between renders");
  assert!(intent(root, &["organize", "--apply"]).status.success());

  let second = std::fs::read(&view).expect("second render");
  assert_eq!(
    first, second,
    "two renders of the same store must be byte-identical"
  );
}

// ---------------------------------------------------------------------------
// AC-01.1 -- A HAND EDIT IS SKEW, AND THE BODY IS THE CASE THAT MATTERS
// ---------------------------------------------------------------------------

#[test]
fn a_hand_edited_body_is_reported_by_doctor_as_view_skew() {
  let dir = project_with_an_issue();
  let root = dir.path();
  assert!(intent(root, &["organize", "--apply"]).status.success());

  let view = issue_view(root);
  let clean = intent(root, &["doctor"]);
  assert!(
    !said(&clean).contains("issues/0001.md"),
    "a freshly realised view must not be skewed before anything touches it: {}",
    said(&clean)
  );

  let text = std::fs::read_to_string(&view).expect("read");
  std::fs::write(&view, format!("{text}\nA line no renderer would write.\n")).expect("hand edit");

  let out = intent(root, &["doctor"]);
  assert!(
    said(&out).contains("issues/0001.md"),
    "doctor must report the hand-edited issue view as skew, said:\n{}",
    said(&out)
  );
}
