//! AT-06.10 / AC-06.10: **every published schema face carries `INTENT_VER` and
//! `SCHEMA_<TYPE>_VER`, and the two parts move independently** (D41).
//!
//! **Read from the FACE AS PUBLISHED, never from the constant.** The failure
//! being guarded is a generator that stops injecting -- a face regenerated by a
//! build where the injection was dropped, refactored away, or short-circuited.
//! A test that asks `faces::INTENT_VER` what the version is passes on exactly
//! that defect, because the constant is still there and still right; it is the
//! ARTEFACT that lost it. So every assertion below opens a file under
//! `schema/` and looks inside it.
//!
//! Why two parts at all (hv, 2026-08-15): they answer different questions and
//! move at different rates. `INTENT_VER` says which tool produced the artefact;
//! `SCHEMA_<TYPE>_VER` says whether the contract a consumer compiles against
//! has changed. **A patch release moves the first and must not move the
//! second**, and a consumer deciding whether to re-generate their client needs
//! the second one alone.
//!
//! Measured before the ruling (vc): zero occurrences of "version" in any of the
//! five faces, while the internal never-committed store had carried a schema
//! stamp and a hard refusal since that morning. **The internal artefact was
//! versioned and the external contract was not**, which is backwards -- the
//! store rebuilds from the extract, and a consumer's code rebuilds from nothing
//! we hold.

use intentsvcs::faces::{INTENT_VER, INTENT_VER_KEY, SCHEMA_VER_KEYS};
use testkit::repo_root;

fn published(name: &str) -> String {
  let path = repo_root().join("schema").join(name);
  std::fs::read_to_string(&path)
    .unwrap_or_else(|e| panic!("reading the published face {}: {e}", path.display()))
}

/// The value a face records for a marker, in whichever idiom that face uses.
///
/// One reader for three idioms, because what is being asserted is the same
/// fact in all three and a per-idiom reader would let one of them quietly stop
/// being checked. SQL says `-- KEY: value`, SDL says `# KEY: value`, JSON says
/// `"x-key": value` -- so the search is for the key followed by a separator,
/// and the value is what follows up to the end of the line, stripped of the
/// punctuation each format wraps it in.
fn marker(face: &str, key: &str) -> Option<String> {
  let json_key = format!("\"x-{}\"", key.to_lowercase().replace('_', "-"));
  for line in face.lines() {
    let line = line.trim();
    let rest = if let Some(rest) = line.strip_prefix(&format!("-- {key}:")) {
      rest
    } else if let Some(rest) = line.strip_prefix(&format!("# {key}:")) {
      rest
    } else if let Some(rest) = line.strip_prefix(&format!("{json_key}:")) {
      rest
    } else {
      continue;
    };
    return Some(
      rest
        .trim()
        .trim_end_matches(',')
        .trim()
        .trim_matches('"')
        .to_string(),
    );
  }
  None
}

#[test]
fn every_published_face_carries_both_version_parts() {
  assert_eq!(
    SCHEMA_VER_KEYS.len(),
    5,
    "five published faces (AC-06.5); if a face was added or removed, this count is the thing that \
     notices"
  );

  let mut missing = Vec::new();
  for (name, schema_key) in SCHEMA_VER_KEYS {
    let face = published(name);
    match marker(&face, INTENT_VER_KEY) {
      Some(found) if found == INTENT_VER => {}
      Some(found) => missing.push(format!(
        "{name}: published {INTENT_VER_KEY} is {found}, this build is {INTENT_VER} -- the face was \
         generated by a different build and committed without regenerating"
      )),
      None => missing.push(format!("{name}: no {INTENT_VER_KEY}")),
    }
    match marker(&face, schema_key) {
      Some(found) if found.parse::<u32>().is_ok() => {}
      Some(found) => missing.push(format!("{name}: {schema_key} is {found:?}, not a number")),
      None => missing.push(format!("{name}: no {schema_key}")),
    }
  }

  assert!(
    missing.is_empty(),
    "AC-06.10: a consumer cannot ask what contract they are compiling against --\n  {}\n\
     Regenerate: INTENT_BLESS=1 cargo test -p intentsvcs --test schema_faces_drift",
    missing.join("\n  ")
  );
}

/// **The three contract versions are independent, asserted where it can
/// actually be observed.**
///
/// The point of three constants is that a SQL column moving must not tell a
/// GraphQL consumer to re-check. That property is only real if each face
/// carries its OWN version and no other -- one face carrying two would make
/// "which version applies to me" ambiguous, and a shared version would make the
/// answer wrong.
#[test]
fn each_face_carries_only_its_own_contract_version() {
  let all_keys: Vec<&str> = {
    let mut keys: Vec<&str> = SCHEMA_VER_KEYS.iter().map(|(_, k)| *k).collect();
    keys.sort_unstable();
    keys.dedup();
    keys
  };
  assert_eq!(
    all_keys.len(),
    3,
    "three face types share five files: the JSON Schemas are one contract in three documents"
  );

  for (name, own) in SCHEMA_VER_KEYS {
    let face = published(name);
    for key in &all_keys {
      if key == own {
        continue;
      }
      assert!(
        marker(&face, key).is_none(),
        "{name} carries {key} as well as its own {own}; a face with two contract versions cannot \
         answer which one a consumer compiles against"
      );
    }
  }
}

/// **A face whose CONTRACT changes must bump its `SCHEMA_<TYPE>_VER`.**
///
/// Without this the constants sit at 1 forever and the version says nothing --
/// the hand-kept-number-beside-a-generated-artefact pattern this thread has met
/// repeatedly. It is the same forcing function the store's `SCHEMA_VERSION`
/// has, and that one earned its existence within hours of being written by
/// catching the first schema change after it.
///
/// **The version markers are stripped before hashing**, or the check would be
/// circular: bumping the version changes the face, which changes the hash,
/// which demands a bump. What is hashed is the contract, which is everything
/// else.
///
/// **`INTENT_VER` is stripped for a second reason** -- it moves on every
/// release including a patch, and a patch must not force a contract bump. That
/// is the two-part split doing its job, expressed as which bytes this hash
/// covers.
#[test]
fn a_face_whose_contract_moves_must_bump_that_faces_version() {
  // FNV-1a, written out: the property wanted is "changes when the input
  // changes", which needs no cryptographic strength and should not add a
  // dependency to get.
  fn hash(text: &str) -> u64 {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in text.as_bytes() {
      h ^= u64::from(*byte);
      h = h.wrapping_mul(0x0000_0100_0000_01b3);
    }
    h
  }

  let mut by_type: Vec<(&str, String)> = Vec::new();
  for (name, schema_key) in SCHEMA_VER_KEYS {
    let contract = contract_of(&published(name));
    match by_type.iter_mut().find(|(k, _)| k == schema_key) {
      // The three JSON Schemas are ONE contract, so they hash together --
      // otherwise a change in `issue` alone would not be visible in a check
      // over `thread`.
      Some((_, acc)) => acc.push_str(&contract),
      None => by_type.push((schema_key, contract)),
    }
  }

  // **These three moved once WITHOUT a version bump, and that is the one
  // legitimate reason to re-pin alone** (cc, 2026-08-15): `contract_of` started
  // excluding documentation, so the same contract hashes differently. The
  // versions are unchanged because nothing a consumer compiles against changed
  // -- proven rather than asserted, by stripping the faces at the previous
  // commit with the new rules and diffing: **zero contract lines differ across
  // all five.** A re-pin without that measurement is the failure this whole
  // mechanism exists to prevent.
  //
  // **JSON went 2 -> 3 the next day, and that re-pin is the mechanism working
  // rather than being worked around.** `AcState::Satisfied.evidence` and
  // `Withdrawn.reason` gained `minLength: 1`, which narrows what a consumer may
  // send us, so a consumer generating from this face has to know. The same
  // commit rewrote that type's `description` at length -- and the DDL and SDL
  // hashes did not move at all. Documentation changing while the contract holds
  // still, and the contract changing loudly when it moves, is exactly the
  // discrimination the strip was built for; it was tested against a real change
  // one day after being written.
  // **ALL THREE MOVED AT ONCE, which had not happened before, and the reason is
  // worth recording because it is the case that looks like a broken
  // instrument.** `Issue` gained a `reporter` column: a new SQL column, a new
  // JSON property and a new SDL field are three faces of one change, so a
  // single field on a modelled type is the shape that legitimately moves
  // everything. It is not the discrimination failing -- the same commit rewrote
  // the DDL's comment block at length and the DDL hash did not move at all,
  // which is the strip doing its job in the same breath.
  // **ALL THREE AGAIN, and the second instance confirms the reading rather than
  // weakening it.** `Thread` gained a `body` column: one field on a modelled
  // type is a new SQL column, a new JSON property and a new SDL field. The
  // hashes were IDENTICAL before and after the version bump, which is the strip
  // separating the version from the contract -- so the three numbers below moved
  // for the field and not for their own bump.
  //
  // **THIRD TIME, AND THE FIRST ON TWO TYPES AT ONCE.** `preamble` landed on
  // `Thread` AND `WorkPackage`, so all three faces moved for two fields rather
  // than one -- the same arithmetic, twice, in one commit. It is the region
  // above the first heading, which `legacy.rs` was dropping on the floor
  // entirely; 396 regions / 88,648 bytes across nine projects.
  //
  // **FOURTH AND FIFTH TIME, in one commit, and all three faces both times.**
  // `Issue::body` -- the issue's authored prose, which had no field at all --
  // and then `Thread::attachments`, the authored files beside a thread that no
  // typed document held. Two entities, one subject: prose whose only home was
  // a file on a disk that is about to become optional.
  //
  // Attachments move the DDL further than a column does: they are the first
  // NEW TABLE since the ladder began, so the DDL hash moves for a `CREATE`
  // rather than an `ALTER`.
  //
  // **SIXTH, AND THE FIRST TIME ONLY ONE OF THE THREE MOVED -- which is the
  // discrimination being demonstrated rather than merely claimed.** `ingests`
  // is a new table recording whether the store's last load from canon finished,
  // and it has no modelled type: nothing about it is serialised, so there is no
  // JSON property and no SDL field for it to become. The DDL moves for a
  // `CREATE`; the other two must not move at all, and the pins below are what
  // says so.
  //
  // Every entry above this one is a case where a single field on a modelled
  // type legitimately moved all three, and the comments spend their length
  // arguing that the instrument was not broken. This is the other side of the
  // same evidence: a change that reaches exactly one face, reaching exactly one.
  //
  // **SEVENTH, AND IT SHIPPED IN THE SAME COMMIT AS THE SIXTH, WHICH IS WHY
  // THAT PARAGRAPH IS TRUE OF ic's CHANGE AND NOT OF THIS COMMIT.** ST0057
  // AC-03.1 makes `Attachment::text` OPTIONAL, so a modelled field on a
  // modelled type changed shape: the SDL's `text: String!` became `text:
  // String`, the JSON property's type widened, and the DDL's `text TEXT NOT
  // NULL` became `text TEXT` beside a new `blob BLOB` and a CHECK. Three faces,
  // one cause -- the ordinary case, arriving alongside the extraordinary one.
  //
  // **`blob` itself reaches EXACTLY ONE face, and that is the load-bearing
  // half.** It is `#[serde(skip)]` and `#[graphql(skip)]`, so it appears in the
  // DDL and in NEITHER published contract -- which is AC-03.2 stated where a
  // reader can check it rather than where an author can promise it: opaque
  // bytes cannot be serialised inline because there is no serialisation of them
  // to reach. If `blob` ever shows up in `schema.graphql` or
  // `thread.schema.json`, that skip has been removed and the criterion is
  // broken; these pins are what would say so.
  //
  // So the two entries above and this one are three DIFFERENT results from the
  // same instrument in one commit: one face (ic's table, no modelled type),
  // three faces (an optional field on a modelled type), and one face again for
  // a field deliberately kept out of the published contracts.
  let pinned: &[(&str, u32, u64)] = &[
    ("SCHEMA_DDL_VER", 10, 0x6966_d5f9_6ad7_8928),
    ("SCHEMA_SDL_VER", 8, 0x7712_a811_9724_49a8),
    ("SCHEMA_JSON_VER", 10, 0xb996_589d_af2f_d02b),
  ];

  let mut moved = Vec::new();
  for (key, contract) in &by_type {
    let (_, pinned_ver, pinned_hash) = pinned
      .iter()
      .find(|(k, _, _)| k == key)
      .unwrap_or_else(|| panic!("no pin for {key}; add one in the same commit as the face"));
    let published_ver: u32 = SCHEMA_VER_KEYS
      .iter()
      .find(|(_, k)| k == key)
      .map(|(name, _)| {
        marker(&published(name), key)
          .expect("checked above")
          .parse()
          .expect("checked above")
      })
      .expect("every key has a face");

    let actual = hash(contract);
    if actual != *pinned_hash || published_ver != *pinned_ver {
      moved.push(format!(
        "{key}: published version {published_ver}, pinned {pinned_ver}; contract hash \
         {actual:#018x}, pinned {pinned_hash:#018x}"
      ));
    }
  }

  assert!(
    moved.is_empty(),
    "a published contract changed. Bump that face type's SCHEMA_<TYPE>_VER in \
     `intentsvcs::faces`, re-pin here in the SAME commit, and regenerate the faces. Note which \
     one moved -- the whole point of three versions is that the other two must not:\n  {}",
    moved.join("\n  ")
  );
}

/// Reduce a face to its CONTRACT: the version markers and the documentation
/// removed, everything a consumer compiles against kept.
///
/// **DOCUMENTATION IS NOT CONTRACT, and this hash covered it until a doc edit
/// proved otherwise** (cc, 2026-08-15). Rewriting comments in `store.rs` and
/// field descriptions in `model.rs` -- no table, no column, no constraint, no
/// field, no type -- moved ALL THREE hashes and demanded three version bumps.
/// Obeying that would have told every consumer their contract had changed in
/// order to record that a sentence had been reworded.
///
/// **It is the identical defect `store_schema_version.rs` had already found and
/// fixed one layer down**, whose own note reads: _"the first thing that touched
/// the DDL afterwards was a comment ... a guard that cries wolf on a comment is
/// a guard someone re-pins without reading."_ That lesson was written hours
/// before this file, by the same hand, and this file did not inherit it -- which
/// is the argument for the strip being CANARIED below rather than trusted.
///
/// Each face is stripped in its own syntax, because there is no common one:
/// SQL `--` lines, JSON `"description"` members, GraphQL `"""` blocks.
fn contract_of(face: &str) -> String {
  let mut out: Vec<&str> = Vec::new();
  let mut in_sdl_description = false;
  for line in face.lines() {
    let t = line.trim();

    // GraphQL: a `"""` block is a description. The delimiters are always on
    // their own line in async-graphql's output, so this is a toggle rather than
    // a parse.
    if t == "\"\"\"" {
      in_sdl_description = !in_sdl_description;
      continue;
    }
    if in_sdl_description {
      continue;
    }

    // The injected version markers, or the check is circular and every patch
    // release becomes a contract change.
    if t.contains(INTENT_VER_KEY)
      || SCHEMA_VER_KEYS.iter().any(|(_, k)| t.contains(k))
      || t.starts_with("\"x-intent-ver\"")
      || t.starts_with("\"x-schema-json-ver\"")
    {
      continue;
    }

    // SQL: whole-line comments only. Stripping `--` wherever it appeared would
    // need a tokeniser to avoid eating one inside a string literal, so the
    // absence of in-line comments is CHECKED rather than assumed -- the same
    // posture, and for the same reason, as the schema-hash strip in
    // `store_schema_version.rs`.
    if t.starts_with("--") {
      continue;
    }
    assert!(
      !t.contains("--") || t.contains("\"") || t.contains("->"),
      "the DDL grew an in-line comment, so stripping whole lines no longer isolates the \
       contract: {t}"
    );

    // JSON Schema: a `description` member. Values are single-line with escaped
    // newlines, so a line test is exact here.
    if t.starts_with("\"description\":") {
      continue;
    }

    out.push(line);
  }
  out.join("\n")
}

/// **The strip is canaried in both directions**, because it can fail two ways
/// and only one of them is loud: stripping too little makes the hash cry wolf,
/// and stripping too much makes it green forever.
#[test]
fn the_strip_removes_the_markers_and_the_prose_and_nothing_else() {
  let ddl = contract_of(&published("ddl.sql"));
  assert!(
    marker(&ddl, INTENT_VER_KEY).is_none(),
    "the tool version must not reach the contract hash, or a patch release becomes a contract \
     change"
  );
  assert!(
    marker(&ddl, "SCHEMA_DDL_VER").is_none(),
    "and neither must the contract version, or the check is circular"
  );
  assert!(
    !ddl.contains("--"),
    "a SQL comment reached the contract hash, so rewording one would read as a schema change"
  );
  assert!(
    ddl.contains("CREATE TABLE IF NOT EXISTS threads ("),
    "the strip removed the contract itself, which would make the hash meaningless and green"
  );

  let json = contract_of(&published("thread.schema.json"));
  assert!(
    !json.contains("\"description\""),
    "a JSON Schema description reached the contract hash"
  );
  assert!(
    json.contains("\"required\""),
    "the strip removed the JSON Schema's own contract"
  );

  let sdl = contract_of(&published("schema.graphql"));
  assert!(
    !sdl.contains("\"\"\""),
    "a GraphQL description block reached the contract hash"
  );
  assert!(
    sdl.contains("type Thread {"),
    "the strip removed the SDL's own contract"
  );
  // The toggle must not run away: an odd number of delimiters would swallow the
  // rest of the file and leave a hash over almost nothing, which is the failure
  // that looks like success.
  assert!(
    sdl.lines().count() > published("schema.graphql").lines().count() / 3,
    "the description strip consumed most of the SDL, so the `\"\"\"` toggle did not close"
  );
}

fn run(args: &[&str]) -> String {
  let out = std::process::Command::new(env!("CARGO_BIN_EXE_intent"))
    .args(args)
    .output()
    .expect("run the v3 binary");
  String::from_utf8_lossy(&out.stdout).into_owned()
}

/// **AC-06.10(b): a consumer can ASK what contract they are compiling against**,
/// without opening a file or knowing which idiom it uses.
///
/// The three assertions are not interchangeable, and the third is the one a
/// naive version misses:
///
/// 1. Every face is listed, with BOTH parts. One part alone leaves the reader
///    unable to tell a rebuild from a contract change.
/// 2. `--versions` composes with `face` rather than overriding it -- the mode
///    and the selection are separate axes (ic, declared with the row).
/// 3. What it prints matches the COMMITTED face, so a build reporting a version
///    the committed artefact does not carry fails here.
///
/// **What this test does NOT establish is that the command reads the artefact
/// rather than the constants** -- in a healthy tree those agree, so a
/// `--versions` wired straight to `faces::INTENT_VER` passes every assertion
/// below. That property needs the binary checked against ITSELF and lives in
/// [`what_versions_reports_is_what_the_printed_face_carries`]. Recorded here
/// because a test that quietly implies a stronger claim than it makes is the
/// more expensive kind of gap: it stops anyone writing the test that does.
#[test]
fn the_versions_flag_reports_what_the_faces_actually_carry() {
  let printed = run(&["schema", "--versions"]);
  let lines: Vec<&str> = printed.lines().filter(|l| !l.trim().is_empty()).collect();
  assert_eq!(
    lines.len(),
    SCHEMA_VER_KEYS.len(),
    "one line per face, got:\n{printed}"
  );

  for (name, schema_key) in SCHEMA_VER_KEYS {
    let line = lines
      .iter()
      .find(|l| l.starts_with(name))
      .unwrap_or_else(|| panic!("no line for {name} in:\n{printed}"));

    // The published file is the independent witness: if the generator stopped
    // injecting, the command's value goes empty while this one does not.
    let face = published(name);
    let tool = marker(&face, INTENT_VER_KEY).expect("the published face carries a tool version");
    let contract =
      marker(&face, schema_key).expect("the published face carries its contract version");
    assert!(!tool.is_empty() && !contract.is_empty());

    assert!(
      line.contains(&format!("{INTENT_VER_KEY}={tool}")),
      "{name}: the printed tool version does not match the artefact's -- a build reporting a \
       constant while the face lost its marker is the failure this reads the artefact to catch. \
       got: {line}"
    );
    assert!(
      line.contains(&format!("{schema_key}={contract}")),
      "{name}: the printed contract version does not match the artefact's. got: {line}"
    );
  }
}

/// The mode and the selection are separate axes, so naming a face narrows the
/// listing rather than switching it off.
#[test]
fn the_versions_flag_composes_with_a_named_face() {
  let one = run(&["schema", "ddl.sql", "--versions"]);
  let lines: Vec<&str> = one.lines().filter(|l| !l.trim().is_empty()).collect();
  assert_eq!(
    lines.len(),
    1,
    "a named face narrows to its own line: {one}"
  );
  assert!(lines[0].starts_with("ddl.sql"), "got: {one}");
  assert!(lines[0].contains("SCHEMA_DDL_VER="), "got: {one}");

  // ...and without the flag the same invocation still prints the face itself,
  // so the mode genuinely is a mode and not a hijack of the argument.
  let body = run(&["schema", "ddl.sql"]);
  assert!(
    body.contains("CREATE TABLE IF NOT EXISTS threads ("),
    "the bare form still prints the face body"
  );
}

/// **The command's two outputs must agree with each other**, which is the
/// property that makes reading the artefact load-bearing rather than merely
/// tidy.
///
/// The check above compares `--versions` against the COMMITTED files, and that
/// is worth having -- but it does not pin the mechanism: a `--versions` that
/// reported `faces::INTENT_VER` straight from the constant would pass it, since
/// the constant and the committed file agree in a healthy tree. **The two
/// mutations that matter travel together** -- the generator stops injecting AND
/// the command reports constants -- and against the committed files that pair
/// is invisible.
///
/// So this compares the binary against ITSELF: whatever `intent schema
/// --versions` claims a face's version is, `intent schema <face>` must actually
/// carry. One command cannot answer the same question two ways, and a build
/// that has stopped injecting fails here with nothing else needing to change.
#[test]
fn what_versions_reports_is_what_the_printed_face_carries() {
  for (name, schema_key) in SCHEMA_VER_KEYS {
    let body = run(&["schema", name]);
    let claimed = run(&["schema", name, "--versions"]);

    let in_body_tool = marker(&body, INTENT_VER_KEY).unwrap_or_else(|| {
      panic!("{name}: the face the CLI printed carries no {INTENT_VER_KEY} at all:\n{body}")
    });
    let in_body_contract = marker(&body, schema_key)
      .unwrap_or_else(|| panic!("{name}: the face the CLI printed carries no {schema_key} at all"));

    assert!(
      claimed.contains(&format!("{INTENT_VER_KEY}={in_body_tool}")),
      "{name}: `--versions` and the face itself disagree about the tool version. `--versions` \
       said:\n  {claimed}\nthe face carries {in_body_tool}"
    );
    assert!(
      claimed.contains(&format!("{schema_key}={in_body_contract}")),
      "{name}: `--versions` and the face itself disagree about the contract version. \
       `--versions` said:\n  {claimed}\nthe face carries {in_body_contract}"
    );
  }
}
