//! AT-06.10 / AC-06.10: **every published schema face carries `INTENT_VER` and
//! `SCHEMA_<TYPE>_VER`, and the two parts move independently** (D41).
//!
//! **Read from the FACE AS PUBLISHED, never from the constant.** The failure
//! being guarded is a generator that stops injecting -- a face regenerated by a
//! build where the injection was dropped, refactored away, or short-circuited.
//! A test that asks `faces::INTENT_VER` what the version is passes on exactly
//! that defect, because the constant is still there and still right; it is the
//! ARTEFACT that lost it. So every assertion below opens a file under
//! `schema/` and looks inside it.
//!
//! Why two parts at all (hv, 2026-08-15): they answer different questions and
//! move at different rates. `INTENT_VER` says which tool produced the artefact;
//! `SCHEMA_<TYPE>_VER` says whether the contract a consumer compiles against
//! has changed. **A patch release moves the first and must not move the
//! second**, and a consumer deciding whether to re-generate their client needs
//! the second one alone.
//!
//! Measured before the ruling (vc): zero occurrences of "version" in any of the
//! five faces, while the internal never-committed store had carried a schema
//! stamp and a hard refusal since that morning. **The internal artefact was
//! versioned and the external contract was not**, which is backwards -- the
//! store rebuilds from the extract, and a consumer's code rebuilds from nothing
//! we hold.

use std::path::{Path, PathBuf};

use intentsvcs::faces::{INTENT_VER, INTENT_VER_KEY, SCHEMA_VER_KEYS};

/// The repository root, searched rather than counted.
///
/// **This is the third copy of this helper in the estate** (`intentsvcs`'s
/// `schema_faces_drift.rs` and `intent-cli`'s `no_intent_home.rs` are the
/// others, the latter raised by dc as the second instance). Rust integration
/// tests cannot share a helper across crates without a dev-dependency crate to
/// hold it, so the fix is a workspace change rather than a local one -- and the
/// workspace is dc's lane. Copied knowingly and reported, not copied quietly.
fn repo_root() -> PathBuf {
  Path::new(env!("CARGO_MANIFEST_DIR"))
    .ancestors()
    .find(|d| d.join("schema").is_dir() && d.join("surface").is_dir())
    .expect("a repository root carrying schema/ and surface/ above this crate")
    .to_path_buf()
}

fn published(name: &str) -> String {
  let path = repo_root().join("schema").join(name);
  std::fs::read_to_string(&path)
    .unwrap_or_else(|e| panic!("reading the published face {}: {e}", path.display()))
}

/// The value a face records for a marker, in whichever idiom that face uses.
///
/// One reader for three idioms, because what is being asserted is the same
/// fact in all three and a per-idiom reader would let one of them quietly stop
/// being checked. SQL says `-- KEY: value`, SDL says `# KEY: value`, JSON says
/// `"x-key": value` -- so the search is for the key followed by a separator,
/// and the value is what follows up to the end of the line, stripped of the
/// punctuation each format wraps it in.
fn marker(face: &str, key: &str) -> Option<String> {
  let json_key = format!("\"x-{}\"", key.to_lowercase().replace('_', "-"));
  for line in face.lines() {
    let line = line.trim();
    let rest = if let Some(rest) = line.strip_prefix(&format!("-- {key}:")) {
      rest
    } else if let Some(rest) = line.strip_prefix(&format!("# {key}:")) {
      rest
    } else if let Some(rest) = line.strip_prefix(&format!("{json_key}:")) {
      rest
    } else {
      continue;
    };
    return Some(
      rest
        .trim()
        .trim_end_matches(',')
        .trim()
        .trim_matches('"')
        .to_string(),
    );
  }
  None
}

#[test]
fn every_published_face_carries_both_version_parts() {
  assert_eq!(
    SCHEMA_VER_KEYS.len(),
    5,
    "five published faces (AC-06.5); if a face was added or removed, this count is the thing that \
     notices"
  );

  let mut missing = Vec::new();
  for (name, schema_key) in SCHEMA_VER_KEYS {
    let face = published(name);
    match marker(&face, INTENT_VER_KEY) {
      Some(found) if found == INTENT_VER => {}
      Some(found) => missing.push(format!(
        "{name}: published {INTENT_VER_KEY} is {found}, this build is {INTENT_VER} -- the face was \
         generated by a different build and committed without regenerating"
      )),
      None => missing.push(format!("{name}: no {INTENT_VER_KEY}")),
    }
    match marker(&face, schema_key) {
      Some(found) if found.parse::<u32>().is_ok() => {}
      Some(found) => missing.push(format!("{name}: {schema_key} is {found:?}, not a number")),
      None => missing.push(format!("{name}: no {schema_key}")),
    }
  }

  assert!(
    missing.is_empty(),
    "AC-06.10: a consumer cannot ask what contract they are compiling against --\n  {}\n\
     Regenerate: INTENT_BLESS=1 cargo test -p intentsvcs --test schema_faces_drift",
    missing.join("\n  ")
  );
}

/// **The three contract versions are independent, asserted where it can
/// actually be observed.**
///
/// The point of three constants is that a SQL column moving must not tell a
/// GraphQL consumer to re-check. That property is only real if each face
/// carries its OWN version and no other -- one face carrying two would make
/// "which version applies to me" ambiguous, and a shared version would make the
/// answer wrong.
#[test]
fn each_face_carries_only_its_own_contract_version() {
  let all_keys: Vec<&str> = {
    let mut keys: Vec<&str> = SCHEMA_VER_KEYS.iter().map(|(_, k)| *k).collect();
    keys.sort_unstable();
    keys.dedup();
    keys
  };
  assert_eq!(
    all_keys.len(),
    3,
    "three face types share five files: the JSON Schemas are one contract in three documents"
  );

  for (name, own) in SCHEMA_VER_KEYS {
    let face = published(name);
    for key in &all_keys {
      if key == own {
        continue;
      }
      assert!(
        marker(&face, key).is_none(),
        "{name} carries {key} as well as its own {own}; a face with two contract versions cannot \
         answer which one a consumer compiles against"
      );
    }
  }
}

/// **A face whose CONTRACT changes must bump its `SCHEMA_<TYPE>_VER`.**
///
/// Without this the constants sit at 1 forever and the version says nothing --
/// the hand-kept-number-beside-a-generated-artefact pattern this thread has met
/// repeatedly. It is the same forcing function the store's `SCHEMA_VERSION`
/// has, and that one earned its existence within hours of being written by
/// catching the first schema change after it.
///
/// **The version markers are stripped before hashing**, or the check would be
/// circular: bumping the version changes the face, which changes the hash,
/// which demands a bump. What is hashed is the contract, which is everything
/// else.
///
/// **`INTENT_VER` is stripped for a second reason** -- it moves on every
/// release including a patch, and a patch must not force a contract bump. That
/// is the two-part split doing its job, expressed as which bytes this hash
/// covers.
#[test]
fn a_face_whose_contract_moves_must_bump_that_faces_version() {
  // FNV-1a, written out: the property wanted is "changes when the input
  // changes", which needs no cryptographic strength and should not add a
  // dependency to get.
  fn hash(text: &str) -> u64 {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in text.as_bytes() {
      h ^= u64::from(*byte);
      h = h.wrapping_mul(0x0000_0100_0000_01b3);
    }
    h
  }

  let mut by_type: Vec<(&str, String)> = Vec::new();
  for (name, schema_key) in SCHEMA_VER_KEYS {
    let contract = strip_versions(&published(name));
    match by_type.iter_mut().find(|(k, _)| k == schema_key) {
      // The three JSON Schemas are ONE contract, so they hash together --
      // otherwise a change in `issue` alone would not be visible in a check
      // over `thread`.
      Some((_, acc)) => acc.push_str(&contract),
      None => by_type.push((schema_key, contract)),
    }
  }

  let pinned: &[(&str, u32, u64)] = &[
    ("SCHEMA_DDL_VER", 1, 0x17c0_335d_9ab3_c28f),
    ("SCHEMA_SDL_VER", 1, 0x95cf_14ce_d053_a361),
    ("SCHEMA_JSON_VER", 1, 0xc9c8_7bab_d5c6_5658),
  ];

  let mut moved = Vec::new();
  for (key, contract) in &by_type {
    let (_, pinned_ver, pinned_hash) = pinned
      .iter()
      .find(|(k, _, _)| k == key)
      .unwrap_or_else(|| panic!("no pin for {key}; add one in the same commit as the face"));
    let published_ver: u32 = SCHEMA_VER_KEYS
      .iter()
      .find(|(_, k)| k == key)
      .map(|(name, _)| {
        marker(&published(name), key)
          .expect("checked above")
          .parse()
          .expect("checked above")
      })
      .expect("every key has a face");

    let actual = hash(contract);
    if actual != *pinned_hash || published_ver != *pinned_ver {
      moved.push(format!(
        "{key}: published version {published_ver}, pinned {pinned_ver}; contract hash \
         {actual:#018x}, pinned {pinned_hash:#018x}"
      ));
    }
  }

  assert!(
    moved.is_empty(),
    "a published contract changed. Bump that face type's SCHEMA_<TYPE>_VER in \
     `intentsvcs::faces`, re-pin here in the SAME commit, and regenerate the faces. Note which \
     one moved -- the whole point of three versions is that the other two must not:\n  {}",
    moved.join("\n  ")
  );
}

/// Remove the injected version markers, leaving the contract.
///
/// Shared by the hash above and canaried below, because a stripper that
/// silently stopped stripping would make the hash cover `INTENT_VER` and turn
/// every patch release into a false contract change -- a guard that cries wolf
/// is a guard someone re-pins without reading.
fn strip_versions(face: &str) -> String {
  face
    .lines()
    .filter(|line| {
      let t = line.trim();
      !(t.contains(INTENT_VER_KEY)
        || SCHEMA_VER_KEYS.iter().any(|(_, k)| t.contains(k))
        || t.starts_with("\"x-intent-ver\"")
        || t.starts_with("\"x-schema-json-ver\""))
    })
    .collect::<Vec<_>>()
    .join("\n")
}

#[test]
fn the_stripper_removes_the_markers_and_nothing_else() {
  let face = published("ddl.sql");
  let stripped = strip_versions(&face);

  assert!(
    marker(&stripped, INTENT_VER_KEY).is_none(),
    "the tool version must not reach the contract hash, or a patch release becomes a contract \
     change"
  );
  assert!(
    marker(&stripped, "SCHEMA_DDL_VER").is_none(),
    "and neither must the contract version, or the check is circular"
  );
  assert!(
    stripped.contains("CREATE TABLE IF NOT EXISTS threads ("),
    "the strip removed the contract itself, which would make the hash meaningless and green"
  );
  assert_eq!(
    face.lines().count() - stripped.lines().count(),
    2,
    "exactly the two marker lines came out of ddl.sql"
  );
}
