//! AT-07.6 / ST0056 AC-07.6: **a generated view has one writer IN A CONSUMER
//! REPO, not only in this one.**
//!
//! # The clause this file exists for is the last six words of the criterion
//!
//! AC-03.17 already established one-writer-per-view here, and
//! `generated_views_are_not_formatted.rs` polices it here: it asks
//! `views::render_all` for its own output set and requires every path to be
//! ignored. **That test cannot see the defect this one is about.** It reads
//! THIS repository, whose `.prettierignore` is HAND-AUTHORED -- 40 lines of
//! reasoning somebody sat down and wrote. Nothing lays that file down for
//! anyone else.
//!
//! So the estate is immune and every consumer is exposed, and the two facts are
//! indistinguishable from inside the estate. That is what "in a consumer repo
//! as well as this one" is doing in the criterion, and it is why this file
//! drives `intent init` into a tempdir instead of reading the repository it
//! runs in.
//!
//! # The defect, measured before it was fixed
//!
//! Driven by hand 2026-08-28 against a fresh `intent init` consumer project,
//! with a thread titled `a thread with *emphasis* in it`:
//!
//! ```text
//! - | ST0001 | a thread with *emphasis* in it | Triage | 2026-08-28 |
//! + | ST0001 | a thread with _emphasis_ in it | Triage | 2026-08-28 |
//! ```
//!
//! The rewritten file is `intent/st/steel_threads.md`, whose own last line
//! reads *"Do not edit this file -- it is rendered from the model, and `intent
//! doctor` reports any hand-edit as skew."* **So the formatter edits a file the
//! tool tells the operator not to edit, and the tool then reports the operator
//! for it.** Regenerating restores the renderer's bytes; the next format pass
//! rewrites them again. Forever, with every pass looking like a legitimate
//! repair -- 7 diverged rows and three consecutive commits reporting "1 file
//! changed" when this ran inside the estate.
//!
//! # The control is not decoration and it is not optional
//!
//! `it_can_fail_when_the_exclusion_is_removed` re-runs the identical drive with
//! the exclusion deleted and requires it to REWRITE. Without that arm, a green
//! here is also what you would see if prettier silently did nothing, if the
//! view were never rendered, or if the fixture carried no emphasis to rewrite
//! -- **three ways to pass while measuring nothing**, which is the class this
//! estate keeps meeting. `format_roster_is_honoured.rs` makes the same argument
//! for the same reason: a subject that cannot exhibit the defect cannot clear
//! it.
//!
//! # A missing prettier FAILS here; it does not skip
//!
//! `generated_views_are_not_formatted.rs` prints a loud skip and **still
//! passes**. That was the right call for a test of the repository's own
//! roster; it is the wrong one here, and inheriting it would be the joke this
//! file is about -- a test whose whole subject is instruments that pass without
//! measuring, passing without measuring.
//!
//! A loud skip is only loud to somebody reading the log. In CI nobody is, so
//! the row would read green forever on a machine that never ran the formatter
//! once. **Prettier is not optional tooling in this project** -- the pre-commit
//! hook runs `prettier --write` over every staged markdown file, so any machine
//! that can commit here has it. The default is therefore to FAIL, with
//! `INTENT_ALLOW_MISSING_PRETTIER=1` as an explicit, named waiver for a
//! contributor who has chosen to work without it. **The waiver is an env var
//! rather than a silent probe because someone has to have decided.**

use std::path::Path;
use std::process::Command;

/// Is `name` runnable on the current PATH?
///
/// Split out with no prettier knowledge in it **so the arm below can drive it
/// to both verdicts.** A presence check that has only ever answered "yes" is
/// indistinguishable from one that always answers "yes", and this whole file
/// hangs off its answer.
fn tool_on_path(name: &str) -> bool {
  Command::new(name)
    .arg("--version")
    .output()
    .map(|o| o.status.success())
    .unwrap_or(false)
}

/// Refuse to report a verdict that was never measured.
fn require_prettier() {
  if tool_on_path("prettier") {
    return;
  }
  if std::env::var_os("INTENT_ALLOW_MISSING_PRETTIER").is_some() {
    eprintln!(
      "WAIVED: prettier is absent and INTENT_ALLOW_MISSING_PRETTIER is set, so AC-07.6 was NOT \
       measured on this machine. This is a waiver, not a pass."
    );
    return;
  }
  panic!(
    "prettier is not on PATH, so the one thing this test asserts cannot be measured. It FAILS \
     rather than skipping: a skip here is a green that means nothing, on a criterion about \
     instruments that pass without measuring. Install prettier, or set \
     INTENT_ALLOW_MISSING_PRETTIER=1 to waive it deliberately."
  );
}

fn run(cwd: &Path, args: &[&str]) -> (String, i32) {
  let out = Command::new(env!("CARGO_BIN_EXE_intent"))
    .args(args)
    .current_dir(cwd)
    .env("HOME", testkit::fixture_home())
    .output()
    .expect("the intent binary runs");
  let mut text = String::from_utf8_lossy(&out.stdout).into_owned();
  text.push_str(&String::from_utf8_lossy(&out.stderr));
  (text, out.status.code().unwrap_or(-1))
}

/// A consumer project carrying a rendered view with authored `*emphasis*` in
/// it. The emphasis is the payload: it is the construct prettier rewrites, so
/// a fixture without it cannot exhibit the defect.
fn consumer_with_a_rendered_view() -> tempfile::TempDir {
  let dir = tempfile::tempdir().expect("tempdir");
  let root = dir.path();
  let (out, rc) = run(root, &["init", "consumer"]);
  assert_eq!(rc, 0, "init a consumer project: {out}");
  let (out, rc) = run(root, &["st", "new", "a thread with *emphasis* in it"]);
  assert_eq!(rc, 0, "create the thread: {out}");
  // D02: the store is the SSOT and the view does not exist on disk until this.
  let (out, rc) = run(root, &["sync", "--to-disk"]);
  assert_eq!(rc, 0, "render the view: {out}");
  assert!(
    root.join(VIEW).exists(),
    "the fixture is only a fixture if the view actually rendered"
  );
  dir
}

/// The rendered view under test. Chosen because it is generated, it carries an
/// authored string verbatim, and it exists on a project with one thread in it.
const VIEW: &str = "intent/st/steel_threads.md";

fn prettier_write(root: &Path, rel: &str) {
  let out = Command::new("prettier")
    .args(["--write", rel])
    .current_dir(root)
    .output()
    .expect("prettier runs");
  assert!(
    out.status.success(),
    "prettier --write {rel}: {}",
    String::from_utf8_lossy(&out.stderr)
  );
}

/// Ask prettier's OWN resolution whether it would format this path, so the
/// assertion agrees with the formatter by construction rather than by parsing
/// an ignore file ourselves.
fn ignored_by_prettier(root: &Path, rel: &str) -> Option<bool> {
  let out = Command::new("prettier")
    .args(["--file-info", rel])
    .current_dir(root)
    .output()
    .ok()?;
  if !out.status.success() {
    return None;
  }
  let text = String::from_utf8_lossy(&out.stdout);
  let value: serde_json::Value = serde_json::from_str(&text).ok()?;
  value.get("ignored")?.as_bool()
}

#[test]
fn a_rendered_view_survives_the_formatter_in_a_consumer_repo() {
  require_prettier();
  let dir = consumer_with_a_rendered_view();
  let root = dir.path();
  let before = std::fs::read_to_string(root.join(VIEW)).expect("read the view");
  assert!(
    before.contains("*emphasis*"),
    "the renderer must emit the authored form verbatim, or this test measures nothing: {before}"
  );

  prettier_write(root, VIEW);

  let after = std::fs::read_to_string(root.join(VIEW)).expect("re-read the view");
  assert_eq!(
    before, after,
    "a format pass rewrote a generated view in a consumer repo -- the renderer is no longer its \
     only writer, and `intent doctor` will now report skew on a file nobody edited"
  );
}

#[test]
fn the_consumer_repo_carries_the_exclusion_that_makes_the_arm_above_structural() {
  require_prettier();
  let dir = consumer_with_a_rendered_view();
  // Byte-equality can hold by luck -- a view with no rewritable construct in it
  // passes the arm above forever. The EXCLUSION is the structural claim, and it
  // is what `intent init` owes a consumer.
  assert_eq!(
    ignored_by_prettier(dir.path(), VIEW),
    Some(true),
    "prettier's own resolution says it would format {VIEW} in a freshly-initialised consumer \
     project, so nothing there keeps the formatter off a generated view"
  );
}

#[test]
fn authored_prose_in_a_consumer_repo_is_still_formatted() {
  require_prettier();
  let dir = consumer_with_a_rendered_view();
  let root = dir.path();
  // A `.prettierignore` of `*` satisfies the arm above completely, and would be
  // a tool quietly disabling a consumer's formatter across their whole repo.
  let authored = "notes.md";
  std::fs::write(root.join(authored), "a  hand   written  note\n").expect("write authored prose");
  assert_eq!(
    ignored_by_prettier(root, authored),
    Some(false),
    "the exclusion reaches a file the consumer authored -- Intent excludes what IT generates and \
     has no business switching off a consumer's formatter anywhere else"
  );
}

#[test]
fn it_can_fail_when_the_exclusion_is_removed() {
  require_prettier();
  let dir = consumer_with_a_rendered_view();
  let root = dir.path();
  // THE POSITIVE CONTROL. Identical drive, exclusion deleted. If this does not
  // go red, then the green above is telling us nothing about the exclusion --
  // it would look exactly the same if prettier were a no-op, if the view were
  // never rendered, or if the fixture carried nothing rewritable.
  let _ = std::fs::remove_file(root.join(".prettierignore"));
  let before = std::fs::read_to_string(root.join(VIEW)).expect("read the view");
  prettier_write(root, VIEW);
  let after = std::fs::read_to_string(root.join(VIEW)).expect("re-read the view");
  assert_ne!(
    before, after,
    "with the exclusion removed the formatter left the view alone, so this fixture cannot \
     exhibit the defect and every other arm in this file is decoration"
  );
  assert!(
    before.contains("*emphasis*") && after.contains("_emphasis_"),
    "the specific rewrite this criterion is about did not happen, so the control passed for some \
     other reason: before={before} after={after}"
  );
}

#[test]
fn the_prettier_gate_discriminates_rather_than_always_agreeing() {
  // Two-sided, for the same reason census arm 13 exists: a presence check that
  // always returns true passes every arm above while measuring nothing, and no
  // one-sided assertion can tell that check from a working one.
  assert!(
    tool_on_path("prettier"),
    "prettier is absent; every arm in this file is then a waiver rather than a result"
  );
  assert!(
    !tool_on_path("intent-no-such-tool-exists-here-07-6"),
    "the presence check answers yes for a tool that cannot exist, so its yes for prettier means \
     nothing"
  );
}
