// Embeds the project templates `intent init` writes (ST0056 AC-07.1).
//
// **THE CLASS THIS REMOVES IS ISSUE 0022, AND v2 REPORTS IT IN SO MANY
// WORDS.** `bin/intent_init:225` is `error "Template not found:
// $TEMPLATE_DIR/llm/_CLAUDE.md"` -- a binary that has been separated from its
// install tree cannot initialise a project, and the only thing it can do is
// say so. AC-07.1 requires that class to be **unconstructible**, not
// well-reported: a template compiled into the binary cannot be missing from
// the install, because there is no install for it to be missing from.
//
// **NO `rust-embed`, AND THE TABLE NAMES IT, SO THE DEPARTURE IS RECORDED
// RATHER THAN QUIET.** `surface/dispatch-table.json`'s `family_notes` for
// `init` say *"embedded in the binary (WP-07, rust-embed)"*. That is a
// `family_note` -- descriptive -- rather than a `disposition`, which is the
// field the table uses when it is ruling. A `build.rs` reaches the same place
// with **no new dependency**, and this package already has one for the source
// commit, with its logic in this directory for the reason cargo forces: a
// build script per package, and two copies of one concern drift silently.
//
// **IT WALKS, IT DOES NOT LIST, AND THAT IS THE WHOLE ARGUMENT FOR A BUILD
// SCRIPT OVER A HAND-WRITTEN `include_str!` BLOCK.** A per-file list is a
// roster, and this estate spent 2026-08-20 on a roster that stopped matching
// its population. Nothing here can go stale by omission: add a template and it
// is embedded on the next build.
//
// **WHAT IS DELIBERATELY NOT EMBEDDED, because "embed the templates
// directory" would have been the obvious and wrong instruction.**
//
// - `lib/templates/hooks/**` -- the guards and the guard ROSTER. Those are
//   **read live out of `INTENT_HOME`** by the shipped pre-commit hook, which
//   is what lets a new guard reach every consumer with no reinstall. Embedding
//   them would put a second, frozen copy inside the binary -- **the exact
//   defect removed from that roster the same morning**, rebuilt one layer
//   down. Two mechanisms, two populations, and the rule that separates them is
//   stated rather than implied: **a template is embedded because `init` WRITES
//   it; a guard is read live because the gate DISPATCHES it.**
// - `lib/templates/.claude/**` -- installed and updated by
//   `intent claude upgrade`, which owns its own lifecycle.
// - `intent/plugins/agents/templates/_default/{RULES,ARCHITECTURE}.md` -- v2's
//   `init` lays these down so `intent lang init <lang>` has an anchor. **In
//   this build `lang init` answers 2 (not implemented)**, so laying down an
//   anchor for a command that cannot use it would be furniture. Recorded here
//   so it is a decision with a trigger rather than an omission.

use std::path::Path;

/// Walk the template subtrees `init` draws from and write a generated table to
/// `$OUT_DIR/embedded_templates.rs`.
///
/// Emits `include_str!` rather than inlining the bytes: cargo then tracks each
/// file itself, the generated source stays small, and a template that fails to
/// read is a compile error naming the path instead of a silently short table.
fn emit_embedded_templates() {
  let out_dir = std::env::var("OUT_DIR").expect("cargo sets OUT_DIR");
  let dest = Path::new(&out_dir).join("embedded_templates.rs");

  // Relative to this crate's manifest, which cargo gives us absolutely. Built
  // from `CARGO_MANIFEST_DIR` rather than from a relative literal so the walk
  // does not depend on the working directory cargo happens to use.
  let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR");
  // FOUR, not three: `<root>/native/rust/crates/<pkg>`. The first version said
  // three and the empty-table assert below caught it on the first build --
  // which is the whole reason that assert is an assert. Had the walk merely
  // returned nothing, `init` would have shipped writing no templates and
  // reporting success.
  let root = Path::new(&manifest)
    .ancestors()
    .nth(4)
    .expect("crates/<pkg> sits four levels under the repo root")
    .to_path_buf();
  let templates = root.join("lib/templates");

  let mut rows: Vec<(String, String)> = Vec::new();
  for subtree in ["llm", "prj"] {
    collect(&templates.join(subtree), &templates, &mut rows);
  }
  // SORTED, so the generated file is byte-stable across machines. Directory
  // order is filesystem order, which differs between them -- and an artefact
  // that changes without its inputs changing is one nobody can pin.
  rows.sort();

  let mut src = String::from(
    "// GENERATED by build-support/embed_templates.rs. Do not edit.\n\
     /// Every template `init` writes, as (path relative to lib/templates, contents).\n\
     pub static EMBEDDED_TEMPLATES: &[(&str, &str)] = &[\n",
  );
  for (rel, abs) in &rows {
    src.push_str(&format!("  ({rel:?}, include_str!({abs:?})),\n"));
    println!("cargo:rerun-if-changed={abs}");
  }
  src.push_str("];\n");

  // **A ZERO-LENGTH TABLE IS A BUILD FAILURE, NOT AN EMPTY EMBED.** If the
  // walk finds nothing -- a moved directory, a bad ancestor count -- the
  // binary would still compile and `init` would write a project with no
  // templates in it, reporting success. That is the silent-shortfall shape
  // this whole criterion exists to close, so it fails here instead, loudly,
  // at the one moment somebody can act on it.
  assert!(
    !rows.is_empty(),
    "embedded no templates: looked under {}",
    templates.display()
  );

  std::fs::write(&dest, src).expect("write the generated template table");
  println!("cargo:rerun-if-changed={}", templates.display());
}

/// Every file under `dir`, as (path relative to `base`, absolute path).
fn collect(dir: &Path, base: &Path, out: &mut Vec<(String, String)>) {
  let Ok(entries) = std::fs::read_dir(dir) else {
    return;
  };
  for entry in entries.filter_map(|e| e.ok()) {
    let path = entry.path();
    if path.is_dir() {
      collect(&path, base, out);
      continue;
    }
    // `.DS_Store` is in this tree on macOS and is not a template. Skipped by
    // NAME rather than by extension: it has none, and an extension allow-list
    // would silently drop a future template that also has none.
    if path.file_name().is_some_and(|n| n == ".DS_Store") {
      continue;
    }
    let rel = path
      .strip_prefix(base)
      .expect("collected under base")
      .to_string_lossy()
      .replace('\\', "/");
    out.push((rel, path.to_string_lossy().into_owned()));
  }
}
