#!/usr/bin/env bats
# Tests for scripts/release. Exercises the dry-run path against a scratch
# repo with file:// remotes and a `gh` shim so no real network or GitHub
# state is touched. Real release cuts (no --dry-run) are not exercised here
# -- those are validated in-flight by the operator.

load "../lib/test_helper.bash"

RELEASE="${INTENT_PROJECT_ROOT}/scripts/release"

# --------------------------------------------------------------------
# Scratch repo helper
# --------------------------------------------------------------------

# Build a minimal repo at $1 with: clean working tree on main, a /VERSION
# file at $2, CHANGELOG.md with a section for $3, and `local` + `upstream`
# remotes that point at fresh bare repos under the scratch dir.
create_scratch_release_repo() {
  local repo="$1"
  local current="$2"
  local target_section_version="$3"
  local target_section_status="${4:-in progress}"

  mkdir -p "$repo"
  cd "$repo" || return 1

  git init -q -b main >/dev/null
  git config user.email "test@example.com"
  git config user.name "Test"

  printf '%s\n' "$current" > VERSION

  cat > CHANGELOG.md <<EOF
# Changelog

## [Unreleased]

## [$target_section_version] - $target_section_status

Test section for $target_section_version.

### Added

- A test feature.

## [$current] - 2026-04-27

The previous release.
EOF

  cat > AGENTS.md <<'EOF'
# Test AGENTS.md

Generated by Intent v0.0.0 on 2026-04-01
EOF

  # Minimal bin/ with stub helpers + intent + tests/run_tests.sh
  mkdir -p bin tests
  cat > bin/intent_helpers <<'EOF'
#!/usr/bin/env bash
get_intent_version() { cat "$PROJECT_ROOT/VERSION" 2>/dev/null || echo "0.0.0"; }
EOF
  chmod +x bin/intent_helpers

  # `bin/intent doctor` and `bin/intent agents sync` -- both no-ops in tests.
  cat > bin/intent <<'EOF'
#!/usr/bin/env bash
case "$1" in
  doctor) exit 0 ;;
  agents)
    case "$2" in
      sync) : ;;
    esac
    ;;
esac
exit 0
EOF
  chmod +x bin/intent

  cat > tests/run_tests.sh <<'EOF'
#!/usr/bin/env bash
exit 0
EOF
  chmod +x tests/run_tests.sh

  # Install the release script under test as part of the repo so the working
  # tree is clean by the time `scripts/release --dry-run` runs its checks.
  mkdir -p scripts
  cp "$RELEASE" scripts/release
  chmod +x scripts/release

  git add -A
  git commit -q -m "init"

  # Bare remotes for local + upstream
  git init -q --bare "$repo/../local-remote.git" >/dev/null
  git init -q --bare "$repo/../upstream-remote.git" >/dev/null
  git remote add local "$repo/../local-remote.git"
  git remote add upstream "$repo/../upstream-remote.git"
}

# Build a fake `gh` shim and prepend it to PATH for the test.
shim_gh() {
  local shim_dir="$TEST_TEMP_DIR/shim"
  mkdir -p "$shim_dir"
  cat > "$shim_dir/gh" <<'EOF'
#!/usr/bin/env bash
case "$1" in
  auth)
    case "$2" in
      status) exit 0 ;;
    esac
    ;;
  release)
    case "$2" in
      view) exit 1 ;;
      create) exit 0 ;;
      edit) exit 0 ;;
    esac
    ;;
esac
exit 0
EOF
  chmod +x "$shim_dir/gh"
  export PATH="$shim_dir:$PATH"
}

# --------------------------------------------------------------------
# Dry-run produces no side effects
# --------------------------------------------------------------------

@test "release --dry-run --patch prints plan and does not commit/tag/push" {
  local repo="$TEST_TEMP_DIR/repo"
  create_scratch_release_repo "$repo" "2.10.0" "2.10.1"
  shim_gh

  # The release script lives in the Intent repo; we point at it directly but
  # cd into the scratch repo so PROJECT_ROOT detection picks up the scratch.
  # That detection is `cd "$SCRIPT_DIR/.." && pwd`, so we must symlink the
  # release script into the scratch repo to make it think the scratch IS its
  # project root.
  cd "$repo" || return 1
  run bash scripts/release --dry-run --patch

  [ "$status" -eq 0 ]
  [[ "$output" == *"target version: 2.10.1"* ]]
  [[ "$output" == *"would write '2.10.1'"* ]]
  [[ "$output" == *"would create tag v2.10.1"* ]]
  [[ "$output" == *"would push main + v2.10.1"* ]]
  [[ "$output" == *"would publish GitHub release v2.10.1"* ]]
  [[ "$output" == *"dry-run complete"* ]]

  # No tag, no commit beyond init.
  run git tag -l
  [ -z "$output" ]

  run git log --oneline
  [[ "$(echo "$output" | wc -l | tr -d ' ')" -eq 1 ]]
}

@test "release --dry-run with explicit vX.Y.Z" {
  local repo="$TEST_TEMP_DIR/repo"
  create_scratch_release_repo "$repo" "2.10.0" "2.11.0"
  shim_gh

  cd "$repo" || return 1
  run bash scripts/release --dry-run v2.11.0

  [ "$status" -eq 0 ]
  [[ "$output" == *"target version: 2.11.0"* ]]
  [[ "$output" == *"would create tag v2.11.0"* ]]
}

@test "release --dry-run --major bumps major version" {
  local repo="$TEST_TEMP_DIR/repo"
  create_scratch_release_repo "$repo" "2.10.0" "3.0.0"
  shim_gh

  cd "$repo" || return 1
  run bash scripts/release --dry-run --major

  [ "$status" -eq 0 ]
  [[ "$output" == *"target version: 3.0.0"* ]]
}

# --------------------------------------------------------------------
# Validation failures
# --------------------------------------------------------------------

@test "release fails when no version arg provided" {
  cd "$TEST_TEMP_DIR" || return 1
  run bash "$RELEASE"
  [ "$status" -eq 1 ]
  [[ "$output" == *"must specify --patch, --minor, --major, or vX.Y.Z"* ]]
}

@test "release fails when bump flag mixed with explicit version" {
  cd "$TEST_TEMP_DIR" || return 1
  run bash "$RELEASE" --patch v3.0.0
  [ "$status" -eq 1 ]
  [[ "$output" == *"cannot mix bump flag"* ]]
}

@test "release fails when target is not greater than current" {
  local repo="$TEST_TEMP_DIR/repo"
  create_scratch_release_repo "$repo" "2.10.0" "2.10.0"
  shim_gh

  cd "$repo" || return 1
  run bash scripts/release --dry-run v2.10.0

  [ "$status" -eq 1 ]
  [[ "$output" == *"not greater than current"* ]]
}

@test "release fails when CHANGELOG has no section for target" {
  local repo="$TEST_TEMP_DIR/repo"
  create_scratch_release_repo "$repo" "2.10.0" "2.10.1"
  shim_gh

  cd "$repo" || return 1
  run bash scripts/release --dry-run v9.9.9

  [ "$status" -eq 1 ]
  [[ "$output" == *"no '## [9.9.9]' section in CHANGELOG.md"* ]]
}

@test "release fails on dirty working tree" {
  local repo="$TEST_TEMP_DIR/repo"
  create_scratch_release_repo "$repo" "2.10.0" "2.10.1"
  shim_gh

  cd "$repo" || return 1
  echo "dirty" >> README.dirty
  run bash scripts/release --dry-run --patch

  [ "$status" -eq 1 ]
  [[ "$output" == *"working tree is not clean"* ]]
}

# --------------------------------------------------------------------
# CHANGELOG date handling
# --------------------------------------------------------------------

@test "release accepts CHANGELOG date that is today" {
  local repo="$TEST_TEMP_DIR/repo"
  create_scratch_release_repo "$repo" "2.10.0" "2.10.1" "$(date +%Y-%m-%d)"
  shim_gh

  cd "$repo" || return 1
  run bash scripts/release --dry-run --patch

  [ "$status" -eq 0 ]
  [[ "$output" == *"CHANGELOG date is today"* ]]
}

@test "release rejects stale CHANGELOG date without --allow-stale-date" {
  local repo="$TEST_TEMP_DIR/repo"
  create_scratch_release_repo "$repo" "2.10.0" "2.10.1" "1999-01-01"
  shim_gh

  cd "$repo" || return 1
  run bash scripts/release --dry-run --patch

  [ "$status" -eq 1 ]
  [[ "$output" == *"--allow-stale-date"* ]]
}

@test "release accepts stale CHANGELOG date with --allow-stale-date" {
  local repo="$TEST_TEMP_DIR/repo"
  create_scratch_release_repo "$repo" "2.10.0" "2.10.1" "1999-01-01"
  shim_gh

  cd "$repo" || return 1
  run bash scripts/release --dry-run --allow-stale-date --patch

  [ "$status" -eq 0 ]
  [[ "$output" == *"CHANGELOG date is not today, but --allow-stale-date is set"* ]]
}

# --------------------------------------------------------------------
# Help output
# --------------------------------------------------------------------

@test "release --help shows usage" {
  run bash "$RELEASE" --help
  [ "$status" -eq 0 ]
  [[ "$output" == *"Intent release orchestrator"* ]]
  [[ "$output" == *"--dry-run"* ]]
  [[ "$output" == *"--patch"* ]]
}
