#!/usr/bin/env bats
# Tests for the release orchestrator, now the devbin handler
# bin/.devbin/cmd/build.d/release (`intent build release`). Exercises the
# dry-run path against a scratch
# repo with file:// remotes and a `gh` shim so no real network or GitHub
# state is touched. Real release cuts (no --dry-run) are not exercised here
# -- those are validated in-flight by the operator.

load "../lib/test_helper.bash"

# INTENT_RELEASE_SCRIPT redirects every test in this file at another copy of the
# script, so these guards can be mutation-tested -- pointed at a deliberately
# broken copy to confirm they go red -- without editing the shipped one. Unset,
# which is every normal run, this is byte-identical to the plain path. Same
# mechanism and same name as release_sidecars.bats: one override, not two.
RELEASE="${INTENT_RELEASE_SCRIPT:-${INTENT_PROJECT_ROOT}/bin/.devbin/cmd/build.d/release}"

# --------------------------------------------------------------------
# Scratch repo helper
# --------------------------------------------------------------------

# Build a minimal repo at $1 with: clean working tree on main, a /VERSION
# file at $2, CHANGELOG.md with a section for $3, and `local` + `upstream`
# remotes that point at fresh bare repos under the scratch dir.
create_scratch_release_repo() {
  local repo="$1"
  local current="$2"
  local target_section_version="$3"
  local target_section_status="${4:-in progress}"

  mkdir -p "$repo"
  cd "$repo" || return 1

  git init -q -b main >/dev/null
  git config user.email "test@example.com"
  git config user.name "Test"

  printf '%s\n' "$current" > VERSION

  cat > CHANGELOG.md <<EOF
# Changelog

## [Unreleased]

## [$target_section_version] - $target_section_status

Test section for $target_section_version.

### Added

- A test feature.

## [$current] - 2026-04-27

The previous release.
EOF

  cat > AGENTS.md <<'EOF'
# Test AGENTS.md

Generated by Intent v0.0.0 on 2026-04-01
EOF

  # Minimal bin/ with stub helpers + intent + tests/run_tests.sh
  mkdir -p bin tests
  cat > bin/intent_helpers <<'EOF'
#!/usr/bin/env bash
get_intent_version() { cat "$PROJECT_ROOT/VERSION" 2>/dev/null || echo "0.0.0"; }
EOF
  chmod +x bin/intent_helpers

  # **THE STUB MOVED WITH THE THING IT STANDS IN FOR** (2026-08-30). These calls
  # used to run `$PROJECT_ROOT/bin/intent`, the v2 shell CLI; they now run the v3
  # binary built from the tree being released, resolved by PATH-free path at
  # `native/rust/target/release/intent`. `require_intent_bin` ABORTS when it is
  # absent, so a fixture that did not plant it would fail every release test with
  # a sequencing error rather than exercising anything -- planting it here is
  # what keeps these tests about the release script.
  mkdir -p native/rust/target/release
  cat > native/rust/target/release/intent <<'EOF'
#!/usr/bin/env bash
case "$1" in
  doctor) exit 0 ;;
  agents)
    case "$2" in
      sync) : ;;
    esac
    ;;
  claude)
    case "$2" in
      upgrade) : ;;
    esac
    ;;
esac
exit 0
EOF
  chmod +x native/rust/target/release/intent

  cat > tests/run_tests.sh <<'EOF'
#!/usr/bin/env bash
exit 0
EOF
  chmod +x tests/run_tests.sh

  # Install the handler under test as part of the repo, at the SAME relative
  # path it occupies for real, so the working tree is clean by the time the
  # dry run does its checks.
  mkdir -p bin/.devbin/cmd/build.d
  cp "$RELEASE" bin/.devbin/cmd/build.d/release
  chmod +x bin/.devbin/cmd/build.d/release

  git add -A
  git commit -q -m "init"

  # Bare remotes for local + upstream
  git init -q --bare "$repo/../local-remote.git" >/dev/null
  git init -q --bare "$repo/../upstream-remote.git" >/dev/null
  git remote add local "$repo/../local-remote.git"
  git remote add upstream "$repo/../upstream-remote.git"
}

# Build a fake `gh` shim and prepend it to PATH for the test.
shim_gh() {
  local shim_dir="$TEST_TEMP_DIR/shim"
  mkdir -p "$shim_dir"
  cat > "$shim_dir/gh" <<'EOF'
#!/usr/bin/env bash
case "$1" in
  auth)
    case "$2" in
      status) exit 0 ;;
    esac
    ;;
  release)
    case "$2" in
      view) exit 1 ;;
      create) exit 0 ;;
      edit) exit 0 ;;
    esac
    ;;
esac
exit 0
EOF
  chmod +x "$shim_dir/gh"
  export PATH="$shim_dir:$PATH"
}

# --------------------------------------------------------------------
# Dry-run produces no side effects
# --------------------------------------------------------------------

# run_release -- invoke the handler the way the dispatcher does.
#
# It refuses to run bare (`: "${DEVBIN_LIB:?...}"`), which is the point: it is
# no longer a standalone script. PROJECT_ROOT is what it uses to find the tree
# it is releasing, and the dispatcher resolves that symlink-safe; here the
# scratch repo IS the tree.
run_release() {
  run env DEVBIN_LIB="$PWD/bin/.devbin/lib" PROJECT_ROOT="$PWD" \
    bash bin/.devbin/cmd/build.d/release "$@"
}

# run_release_src -- the handler at its real path, not the scratch copy.
#
# Same dispatcher contract as run_release: the file refuses to run without
# DEVBIN_LIB and PROJECT_ROOT, including for --help, because the guard is at the
# top and you only ever reach a handler through the dispatcher.
run_release_src() {
  # PROJECT_ROOT is the REAL repo, not $PWD. These three cases test argument
  # parsing and --help, which need no scratch repo -- but the handler sources
  # $PROJECT_ROOT/bin/intent_helpers before it parses anything, so a root
  # without that file dies first and the case never reaches its assertion.
  # As bin/release the root was derived from the file's own location and this
  # could not arise; the dispatcher supplies it now, so the harness must too.
  run env DEVBIN_LIB="${INTENT_PROJECT_ROOT}/bin/.devbin/lib" \
    PROJECT_ROOT="${INTENT_PROJECT_ROOT}" \
    bash "$RELEASE" "$@"
}

@test "release --dry-run --patch prints plan and does not commit/tag/push" {
  local repo="$TEST_TEMP_DIR/repo"
  create_scratch_release_repo "$repo" "2.10.0" "2.10.1"
  shim_gh

  # The release script lives in the Intent repo; we point at it directly but
  # cd into the scratch repo so PROJECT_ROOT detection picks up the scratch.
  # That detection is `cd "$SCRIPT_DIR/.." && pwd`, so we must symlink the
  # release script into the scratch repo to make it think the scratch IS its
  # project root.
  cd "$repo" || return 1
  run_release --dry-run --patch

  [ "$status" -eq 0 ]
  [[ "$output" == *"target version: 2.10.1"* ]]
  [[ "$output" == *"would write '2.10.1'"* ]]
  [[ "$output" == *"would create tag v2.10.1"* ]]
  [[ "$output" == *"would push main + v2.10.1"* ]]
  [[ "$output" == *"would publish GitHub release v2.10.1"* ]]
  [[ "$output" == *"dry-run complete"* ]]

  # No tag, no commit beyond init.
  run git tag -l
  [ -z "$output" ]

  run git log --oneline
  [[ "$(echo "$output" | wc -l | tr -d ' ')" -eq 1 ]]
}

@test "release --dry-run with explicit vX.Y.Z" {
  local repo="$TEST_TEMP_DIR/repo"
  create_scratch_release_repo "$repo" "2.10.0" "2.11.0"
  shim_gh

  cd "$repo" || return 1
  run_release --dry-run v2.11.0

  [ "$status" -eq 0 ]
  [[ "$output" == *"target version: 2.11.0"* ]]
  [[ "$output" == *"would create tag v2.11.0"* ]]
}

@test "release --dry-run --major bumps major version" {
  local repo="$TEST_TEMP_DIR/repo"
  create_scratch_release_repo "$repo" "2.10.0" "3.0.0"
  shim_gh

  cd "$repo" || return 1
  run_release --dry-run --major

  [ "$status" -eq 0 ]
  [[ "$output" == *"target version: 3.0.0"* ]]
}

# --------------------------------------------------------------------
# Validation failures
# --------------------------------------------------------------------

@test "release fails when no version arg provided" {
  cd "$TEST_TEMP_DIR" || return 1
  run_release_src
  [ "$status" -eq 1 ]
  [[ "$output" == *"must specify --patch, --minor, --major, or vX.Y.Z"* ]]
}

@test "release fails when bump flag mixed with explicit version" {
  cd "$TEST_TEMP_DIR" || return 1
  run_release_src --patch v3.0.0
  [ "$status" -eq 1 ]
  [[ "$output" == *"cannot mix bump flag"* ]]
}

@test "release fails when target is not greater than current" {
  local repo="$TEST_TEMP_DIR/repo"
  create_scratch_release_repo "$repo" "2.10.0" "2.10.0"
  shim_gh

  cd "$repo" || return 1
  run_release --dry-run v2.10.0

  [ "$status" -eq 1 ]
  [[ "$output" == *"not greater than current"* ]]
}

@test "release fails when CHANGELOG has no section for target" {
  local repo="$TEST_TEMP_DIR/repo"
  create_scratch_release_repo "$repo" "2.10.0" "2.10.1"
  shim_gh

  cd "$repo" || return 1
  run_release --dry-run v9.9.9

  [ "$status" -eq 1 ]
  [[ "$output" == *"no '## [9.9.9]' section in CHANGELOG.md"* ]]
}

@test "release fails on dirty working tree" {
  local repo="$TEST_TEMP_DIR/repo"
  create_scratch_release_repo "$repo" "2.10.0" "2.10.1"
  shim_gh

  cd "$repo" || return 1
  echo "dirty" >> README.dirty
  run_release --dry-run --patch

  [ "$status" -eq 1 ]
  [[ "$output" == *"working tree is not clean"* ]]
}

# --------------------------------------------------------------------
# CHANGELOG date handling
# --------------------------------------------------------------------

@test "release accepts CHANGELOG date that is today" {
  local repo="$TEST_TEMP_DIR/repo"
  create_scratch_release_repo "$repo" "2.10.0" "2.10.1" "$(date +%Y-%m-%d)"
  shim_gh

  cd "$repo" || return 1
  run_release --dry-run --patch

  [ "$status" -eq 0 ]
  [[ "$output" == *"CHANGELOG date is today"* ]]
}

@test "release rejects stale CHANGELOG date without --allow-stale-date" {
  local repo="$TEST_TEMP_DIR/repo"
  create_scratch_release_repo "$repo" "2.10.0" "2.10.1" "1999-01-01"
  shim_gh

  cd "$repo" || return 1
  run_release --dry-run --patch

  [ "$status" -eq 1 ]
  [[ "$output" == *"--allow-stale-date"* ]]
}

@test "release accepts stale CHANGELOG date with --allow-stale-date" {
  local repo="$TEST_TEMP_DIR/repo"
  create_scratch_release_repo "$repo" "2.10.0" "2.10.1" "1999-01-01"
  shim_gh

  cd "$repo" || return 1
  run_release --dry-run --allow-stale-date --patch

  [ "$status" -eq 0 ]
  [[ "$output" == *"CHANGELOG date is not today, but --allow-stale-date is set"* ]]
}

# --------------------------------------------------------------------
# Help output
# --------------------------------------------------------------------

@test "release --help shows usage" {
  run_release_src --help
  [ "$status" -eq 0 ]
  [[ "$output" == *"Intent release orchestrator"* ]]
  [[ "$output" == *"--dry-run"* ]]
  [[ "$output" == *"--patch"* ]]
}

@test "every flag the parser accepts appears in --help" {
  # The test above is a needle list, and it caught the 2026-08-16 defect only
  # because --dry-run happened to be one of its three picks. usage() printed a
  # hardcoded `5,34p` window of the file's own header; the header grew, and
  # --help exited 0 having printed the word "Usage:" and not one flag.
  #
  # So this derives the set instead of spelling it. A needle list forbids only
  # what its author thought of -- it cannot fail for a flag added tomorrow and
  # left undocumented, which is the same class arriving by the other door.
  local flags
  flags="$(sed -n '/^while \[ \$# -gt 0 \]/,/^done/p' "$RELEASE" |
    grep -E '^[[:space:]]+[^ ]*\)' | grep -oE -- '--[A-Za-z0-9-]+' | sort -u)"

  # An empty extraction would pass the loop below without checking anything --
  # the same "could not look" reading as "nothing wrong" that the lock check
  # was fixed for. The parser has flags; finding none means this test is broken.
  [ -n "$flags" ] || fail "could not extract any flag from the argument parser"

  run_release_src --help
  [ "$status" -eq 0 ]

  local flag
  for flag in $flags; do
    [[ "$output" == *"$flag"* ]] || fail "flag $flag is accepted by the parser but absent from --help"
  done
}
